/**************************************************
 ** Software Component SWC_Control
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#ifndef SWC_CONTROL_H
#define SWC_CONTROL_H


/* Runnables */
    
void CONTROL_init_run();
    
void CONTROL_calculateTargetspeed_run();

void CONTROL_limitSpeed_run();

void CONTROL_processCarstate_run();

#endif /* include guard */

