/**************************************************
 ** Software Component SWC_Engine
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#include "rte.h"
#include "rte_signalpool.h"
#include "rte_activation.h"

#include "logging.h"
#include "engine.h"

#include "swc_engine.h"

#include "cardata.h"



/*******************************************************
 ** Runnables
 *******************************************************/

void ENGINE_init_run()
{
    ENG_Init();
}


void ENGINE_getDecoder_run()
{
   //LOG_I("ENGINE_getDecoder_run","");
}




void ENGINE_controlSpeed_run()
{
    
    //Read in the targetspeed and check for validity
    SIGNAL_SPEED_data_t targetspeed = SIGNAL_SPEED_INIT_DATA;
    
    targetspeed = RTE_SIGNAL_SPEED_get(&SO_TARGETSPEED_signal);
    
    //LOG_I("ENGINE_setSpeed_run","ts %d %d",targetspeed.m_vy, targetspeed.m_vphi);
    
    //Translate into engine speed
    SIGNAL_ENGINE_data_t engine = SIGNAL_ENGINE_INIT_DATA;
    
    //Impact of longitude value vy
    engine.m_rpm_fl = K_VY2RPM * targetspeed.m_vy;
    engine.m_rpm_fr = K_VY2RPM * targetspeed.m_vy;
    engine.m_rpm_rl = K_VY2RPM * targetspeed.m_vy;
    engine.m_rpm_rr = K_VY2RPM * targetspeed.m_vy;
    

    //Impact of the rotation
    engine.m_rpm_fl += K_VPHI2RPM * targetspeed.m_vphi;
    engine.m_rpm_fr -= K_VPHI2RPM * targetspeed.m_vphi;
    engine.m_rpm_rl += K_VPHI2RPM * targetspeed.m_vphi;
    engine.m_rpm_rr -= K_VPHI2RPM * targetspeed.m_vphi;

    
    
    //Write to hardware
    RTE_SIGNAL_ENGINE_set(&SO_ENGINE_signal, engine);
    RTE_SIGNAL_ENGINE_pushPort(&SO_ENGINE_signal);
}

