/**************************************************
 ** Software Component SWC_Ultrasonic
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#include "rte.h"
#include "rte_signalpool.h"

#include "logging.h"

#include "swc_ultrasonic.h"

#include "ultrasonic.h"



/* Runnables */


void US_init_run()
{
    SIGNAL_ULTRASONICSENSOR_data_t us = SIGNAL_ULTRASONICSENSOR_INIT_DATA;
    
    //Set the identifiers for the signals
    us.m_id = US_FRONT;
    RTE_SIGNAL_ULTRASONICSENSOR_set(&SO_USFRONT_signal, us);
    
    us.m_id = US_REAR;
    RTE_SIGNAL_ULTRASONICSENSOR_set(&SO_USREAR_signal, us);
    
    SIGNAL_ULTRASONICSENSOR_data_t us_front = RTE_SIGNAL_ULTRASONICSENSOR_get(&SO_USFRONT_signal);
    SIGNAL_ULTRASONICSENSOR_data_t us_rear = RTE_SIGNAL_ULTRASONICSENSOR_get(&SO_USREAR_signal);
    
    //LOG_I("US_init_run","fid %d rid %d",us_front.m_id, us_rear.m_id);
    
    //Init the hardware
    US_Init();
    
}

void US_getDistance_run()
{
    
    static uint8_t sensor = 0;
    
    SIGNAL_ULTRASONICSENSOR_data_t us_front = RTE_SIGNAL_ULTRASONICSENSOR_get(&SO_USFRONT_signal);
    SIGNAL_ULTRASONICSENSOR_data_t us_rear = RTE_SIGNAL_ULTRASONICSENSOR_get(&SO_USREAR_signal);
    
    
    
    //Simply toggle through the sensors
    switch (sensor)
    {
    case 0 : 
        if (US_ISMEASURING != us_front.m_status)
        {
            RTE_SIGNAL_ULTRASONICSENSOR_pullPort(&SO_USFRONT_signal); 
        }
        else
        {
            LOG_I("US_getDistance_run","front unexpected state:  %d ",us_front.m_status);
        }
        break;
    case 1 : 
        if (US_ISMEASURING != us_rear.m_status)
        {
            RTE_SIGNAL_ULTRASONICSENSOR_pullPort(&SO_USREAR_signal); 
        }
        else
        {
            LOG_I("US_getDistance_run","rear unexpected state:  %d ",us_rear.m_status);
        }
        break;
    }
    
    sensor = (sensor + 1) % 2;
}
void US_getDistanceError_run()
{

   /* Enter your code here */
}
