/**************************************************
 ** Software Component SWC_Remote
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#ifndef SWC_REMOTE_H
#define SWC_REMOTE_H

#include "ringbuffer.h"


    
/** --------------------------------- Runnables ---------------------------------- **/
    
void REMOTE_init_run(); 
   
void REMOTE_testProtocol_run();

void REMOTE_readProtocol_run();

void REMOTE_sendProtocol_run();

void REMOTE_readProtocolError_run();

#endif /* include guard */

