/**************************************************
 ** Software Component SWC_Ultrasonic
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#ifndef SWC_ULTRASONIC_H
#define SWC_ULTRASONIC_H


/* Runnables */
    
void US_init_run();
   
void US_getDistance_run();

void US_getDistanceError_run();

#endif /* include guard */

