/**************************************************
 ** Software Component SWC_Engine
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#ifndef SWC_ENGINE_H
#define SWC_ENGINE_H

#include "global.h"

/* Runnables */
    
void ENGINE_init_run();

void ENGINE_controlSpeed_run();

void ENGINE_getDecoder_run();



#endif /* include guard */

