
/*
 * Filename: tsk_control.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Task control will call the application code (control algorithm, ADAS fuctions,..)
 */

#ifndef _H_DEFINE_TSK_CONTROL
#define _H_DEFINE_TSK_CONTROL

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_CONTROL_INCLUDES */

/* USER CODE END TSK_CONTROL_INCLUDES */



/*
 * description: Task control will call the application code (control algorithm, ADAS fuctions,..)
 * events: ev_decoderdelta_onData|ev_eventin_onData|ev_joystick_onData|ev_tick_1ms
 * mode: Cyclic and Event
 * name: tsk_control
 * shortname: control
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: ev_tick_1ms
 * timertickperiod: 1
 */
DeclareTask(tsk_control);


#endif