-- -------------------------------------------------------------
-- 
-- File Name: CodeGen\hdlsrc\PWM\PWM_ip_src_S_H_Frequncy.vhd
-- Created: 2023-01-23 08:19:54
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip_src_S_H_Frequncy
-- Source Path: PWM/S&H Frequncy
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PWM_ip_src_S_H_Frequncy IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        u                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
        S                                 :   IN    std_logic;
        y                                 :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32_En32
        );
END PWM_ip_src_S_H_Frequncy;


ARCHITECTURE rtl OF PWM_ip_src_S_H_Frequncy IS

  -- Component Declarations
  COMPONENT PWM_ip_src_Discrete_block1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          u                               :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
          S                               :   IN    std_logic;
          y                               :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32_En32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : PWM_ip_src_Discrete_block1
    USE ENTITY work.PWM_ip_src_Discrete_block1(rtl);

  -- Signals
  SIGNAL Discrete_out1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_Discrete : PWM_ip_src_Discrete_block1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              u => u,  -- ufix32_En32
              S => S,
              y => Discrete_out1  -- ufix32_En32
              );

  y <= Discrete_out1;

END rtl;

