-- -------------------------------------------------------------
-- 
-- File Name: CodeGen\hdlsrc\PWM\PWM_ip_dut.vhd
-- Created: 2023-01-23 08:19:58
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip_dut
-- Source Path: PWM_ip/PWM_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PWM_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        Deadtime                          :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        Enable                            :   IN    std_logic;  -- ufix1
        Frequency                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
        Duty_U                            :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
        Duty_V                            :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
        Duty_W                            :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
        ce_out                            :   OUT   std_logic;  -- ufix1
        PWM_Trig                          :   OUT   std_logic;  -- ufix1
        PWM_U                             :   OUT   std_logic_vector(1 downto 0);  -- ufix2
        PWM_V                             :   OUT   std_logic_vector(1 downto 0);  -- ufix2
        PWM_W                             :   OUT   std_logic_vector(1 downto 0);  -- ufix2
        PWM_CntDir                        :   OUT   std_logic;  -- ufix1
        PWM_Freq                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32_En32
        );
END PWM_ip_dut;


ARCHITECTURE rtl OF PWM_ip_dut IS

  -- Component Declarations
  COMPONENT pwm
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          Deadtime                        :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          Enable                          :   IN    std_logic;  -- ufix1
          Frequency                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
          Duty_U                          :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
          Duty_V                          :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
          Duty_W                          :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
          ce_out                          :   OUT   std_logic;  -- ufix1
          PWM_Trig                        :   OUT   std_logic;  -- ufix1
          PWM_U                           :   OUT   std_logic_vector(1 downto 0);  -- ufix2
          PWM_V                           :   OUT   std_logic_vector(1 downto 0);  -- ufix2
          PWM_W                           :   OUT   std_logic_vector(1 downto 0);  -- ufix2
          PWM_CntDir                      :   OUT   std_logic;  -- ufix1
          PWM_Freq                        :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32_En32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : pwm
    USE ENTITY work.pwm(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL Enable_sig                       : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL PWM_Trig_sig                     : std_logic;  -- ufix1
  SIGNAL PWM_U_sig                        : std_logic_vector(1 downto 0);  -- ufix2
  SIGNAL PWM_V_sig                        : std_logic_vector(1 downto 0);  -- ufix2
  SIGNAL PWM_W_sig                        : std_logic_vector(1 downto 0);  -- ufix2
  SIGNAL PWM_CntDir_sig                   : std_logic;  -- ufix1
  SIGNAL PWM_Freq_sig                     : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_PWM_ip_src_PWM : pwm
    PORT MAP( clk           => clk,
              clk_enable    => enb,
              reset         => reset,
              Deadtime      => Deadtime,  -- ufix16
              Enable        => Enable_sig,  -- ufix1
              Frequency     => Frequency,  -- ufix32_En32
              Duty_U        => Duty_U,  -- ufix16_En16
              Duty_V        => Duty_V,  -- ufix16_En16
              Duty_W        => Duty_W,  -- ufix16_En16
              ce_out        => ce_out_sig,  -- ufix1
              PWM_Trig      => PWM_Trig_sig,  -- ufix1
              PWM_U         => PWM_U_sig,  -- ufix2
              PWM_V         => PWM_V_sig,  -- ufix2
              PWM_W         => PWM_W_sig,  -- ufix2
              PWM_CntDir    => PWM_CntDir_sig,  -- ufix1
              PWM_Freq      => PWM_Freq_sig  -- ufix32_En32
              );

  Enable_sig <= Enable;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  PWM_Trig <= PWM_Trig_sig;

  PWM_U <= PWM_U_sig;

  PWM_V <= PWM_V_sig;

  PWM_W <= PWM_W_sig;

  PWM_CntDir <= PWM_CntDir_sig;

  PWM_Freq <= PWM_Freq_sig;

END rtl;

