-- -------------------------------------------------------------
-- 
-- File Name: CodeGen\hdlsrc\PWM\PWM_ip_src_Detect_Change.vhd
-- Created: 2023-01-23 08:19:54
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip_src_Detect_Change
-- Source Path: PWM/Triangle Carrier/Detect Change
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PWM_ip_src_Detect_Change IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        U                                 :   IN    std_logic;
        Y                                 :   OUT   std_logic
        );
END PWM_ip_src_Detect_Change;


ARCHITECTURE rtl OF PWM_ip_src_Detect_Change IS

  -- Signals
  SIGNAL U_k_1                            : std_logic;
  SIGNAL FixPt_Relational_Operator_relop1 : std_logic;

BEGIN
  -- Edge
  -- 
  -- U(k)

  -- Store in Global RAM
  Delay_Input1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      U_k_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        U_k_1 <= U;
      END IF;
    END IF;
  END PROCESS Delay_Input1_process;


  
  FixPt_Relational_Operator_relop1 <= '1' WHEN U /= U_k_1 ELSE
      '0';

  Y <= FixPt_Relational_Operator_relop1;

END rtl;

