-- -------------------------------------------------------------
-- 
-- File Name: CodeGen\hdlsrc\PWM\PWM_ip_src_Discrete.vhd
-- Created: 2023-01-23 08:19:54
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip_src_Discrete
-- Source Path: PWM/S&H Duty/Discrete
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.PWM_ip_src_PWM_pkg.ALL;

ENTITY PWM_ip_src_Discrete IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        u                                 :   IN    vector_of_std_logic_vector16(0 TO 2);  -- ufix16_En16 [3]
        S                                 :   IN    std_logic;
        y                                 :   OUT   vector_of_std_logic_vector16(0 TO 2)  -- ufix16_En16 [3]
        );
END PWM_ip_src_Discrete;


ARCHITECTURE rtl OF PWM_ip_src_Discrete IS

  -- Signals
  SIGNAL Data_Type_Conversion_out1        : std_logic;
  SIGNAL u_unsigned                       : vector_of_unsigned16(0 TO 2);  -- ufix16_En16 [3]
  SIGNAL Switch_out1                      : vector_of_unsigned16(0 TO 2);  -- ufix16_En16 [3]
  SIGNAL Unit_Delay_out1                  : vector_of_unsigned16(0 TO 2);  -- ufix16_En16 [3]

BEGIN
  
  Data_Type_Conversion_out1 <= '1' WHEN S /= '0' ELSE
      '0';

  outputgen1: FOR k IN 0 TO 2 GENERATE
    u_unsigned(k) <= unsigned(u(k));
  END GENERATE;

  Unit_Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_out1 <= (OTHERS => to_unsigned(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_out1 <= Switch_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_process;


  
  Switch_out1 <= Unit_Delay_out1 WHEN Data_Type_Conversion_out1 = '0' ELSE
      u_unsigned;

  outputgen: FOR k IN 0 TO 2 GENERATE
    y(k) <= std_logic_vector(Switch_out1(k));
  END GENERATE;

END rtl;

