-- -------------------------------------------------------------
-- 
-- File Name: CodeGen\hdlsrc\PWM\PWM_ip_src_Discrete_block1.vhd
-- Created: 2023-01-23 08:19:54
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip_src_Discrete_block1
-- Source Path: PWM/S&H Frequncy/Discrete
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PWM_ip_src_Discrete_block1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        u                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
        S                                 :   IN    std_logic;
        y                                 :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32_En32
        );
END PWM_ip_src_Discrete_block1;


ARCHITECTURE rtl OF PWM_ip_src_Discrete_block1 IS

  -- Signals
  SIGNAL Data_Type_Conversion_out1        : std_logic;
  SIGNAL u_unsigned                       : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL Switch_out1                      : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL Unit_Delay_out1                  : unsigned(31 DOWNTO 0);  -- ufix32_En32

BEGIN
  
  Data_Type_Conversion_out1 <= '1' WHEN S /= '0' ELSE
      '0';

  u_unsigned <= unsigned(u);

  Unit_Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_out1 <= Switch_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_process;


  
  Switch_out1 <= Unit_Delay_out1 WHEN Data_Type_Conversion_out1 = '0' ELSE
      u_unsigned;

  y <= std_logic_vector(Switch_out1);

END rtl;

