-- -------------------------------------------------------------
-- 
-- File Name: CodeGen\hdlsrc\PWM\PWM_ip_src_PWM_with_deadtime.vhd
-- Created: 2023-01-23 08:19:54
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip_src_PWM_with_deadtime
-- Source Path: PWM/PWM with deadtime
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.PWM_ip_src_PWM_pkg.ALL;

ENTITY PWM_ip_src_PWM_with_deadtime IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Duty                              :   IN    vector_of_std_logic_vector16(0 TO 2);  -- ufix16_En16 [3]
        Carrier                           :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
        PWM                               :   OUT   std_logic_vector(0 TO 5)  -- boolean [6]
        );
END PWM_ip_src_PWM_with_deadtime;


ARCHITECTURE rtl OF PWM_ip_src_PWM_with_deadtime IS

  -- Signals
  SIGNAL Constant_out1                    : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL Duty_0                           : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL GreaterThan1_relop1              : std_logic;
  SIGNAL Duty_1                           : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL GreaterThan1_relop2              : std_logic;
  SIGNAL Duty_2                           : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL GreaterThan1_relop3              : std_logic;
  SIGNAL Equal                            : std_logic_vector(0 TO 2);  -- boolean [3]
  SIGNAL Equal_0                          : std_logic;
  SIGNAL Duty_0_1                         : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL Carrier_unsigned                 : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL GreaterThan_relop1               : std_logic;
  SIGNAL Duty_1_1                         : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL GreaterThan_relop2               : std_logic;
  SIGNAL Duty_2_1                         : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL GreaterThan_relop3               : std_logic;
  SIGNAL PWM_H                            : std_logic_vector(0 TO 2);  -- boolean [3]
  SIGNAL PWM_H_0                          : std_logic;
  SIGNAL Constant1_out1                   : std_logic;
  SIGNAL PWM_H_0_1                        : std_logic;
  SIGNAL Equal_1                          : std_logic;
  SIGNAL PWM_H_1                          : std_logic;
  SIGNAL PWM_H_1_1                        : std_logic;
  SIGNAL Equal_2                          : std_logic;
  SIGNAL PWM_H_2                          : std_logic;
  SIGNAL PWM_H_2_1                        : std_logic;
  SIGNAL PWM_H_3                          : std_logic_vector(0 TO 2);  -- boolean [3]
  SIGNAL PWM_H_0_2                        : std_logic;
  SIGNAL PWM_H_1_2                        : std_logic;
  SIGNAL PWM_H_2_2                        : std_logic;
  SIGNAL PWM_L_0                          : std_logic;
  SIGNAL PWM_L_1                          : std_logic;
  SIGNAL PWM_L_2                          : std_logic;
  SIGNAL Delay1_out_1                     : std_logic;
  SIGNAL Delay1_1_reg                     : std_logic_vector(0 TO 49);  -- ufix1 [50]
  SIGNAL Delay1_out_2                     : std_logic;
  SIGNAL Delay1_out_3                     : std_logic;
  SIGNAL Delay1_out_4                     : std_logic;
  SIGNAL Delay1_out_5                     : std_logic;
  SIGNAL Delay1_out_6                     : std_logic;
  SIGNAL Delay1_1_reg_1                   : std_logic_vector(0 TO 49);  -- ufix1 [50]
  SIGNAL Delay1_1_reg_2                   : std_logic_vector(0 TO 49);  -- ufix1 [50]
  SIGNAL Delay1_1_reg_3                   : std_logic_vector(0 TO 49);  -- ufix1 [50]
  SIGNAL Delay1_1_reg_4                   : std_logic_vector(0 TO 49);  -- ufix1 [50]
  SIGNAL Delay1_1_reg_5                   : std_logic_vector(0 TO 49);  -- ufix1 [50]
  SIGNAL Mux1_out1_0                      : std_logic;
  SIGNAL Mux1_out1_1                      : std_logic;
  SIGNAL Mux1_out1_2                      : std_logic;
  SIGNAL PWM_H_0_3                        : std_logic;
  SIGNAL PWM_H_0_4                        : std_logic;
  SIGNAL PWM_H_1_3                        : std_logic;
  SIGNAL PWM_H_1_4                        : std_logic;
  SIGNAL PWM_H_2_3                        : std_logic;
  SIGNAL PWM_H_2_4                        : std_logic;
  SIGNAL PWM_L                            : std_logic_vector(0 TO 2);  -- boolean [3]
  SIGNAL Mux1_out1_3                      : std_logic;
  SIGNAL Mux1_out1_4                      : std_logic;
  SIGNAL Mux1_out1_5                      : std_logic;

BEGIN
  Constant_out1 <= to_unsigned(16#FFFF#, 16);

  Duty_0 <= unsigned(Duty(0));

  
  GreaterThan1_relop1 <= '1' WHEN Constant_out1 = Duty_0 ELSE
      '0';

  Duty_1 <= unsigned(Duty(1));

  
  GreaterThan1_relop2 <= '1' WHEN Constant_out1 = Duty_1 ELSE
      '0';

  Duty_2 <= unsigned(Duty(2));

  
  GreaterThan1_relop3 <= '1' WHEN Constant_out1 = Duty_2 ELSE
      '0';

  Equal(0) <= GreaterThan1_relop1;
  Equal(1) <= GreaterThan1_relop2;
  Equal(2) <= GreaterThan1_relop3;

  Equal_0 <= Equal(0);

  Duty_0_1 <= unsigned(Duty(0));

  Carrier_unsigned <= unsigned(Carrier);

  
  GreaterThan_relop1 <= '1' WHEN Duty_0_1 > Carrier_unsigned ELSE
      '0';

  Duty_1_1 <= unsigned(Duty(1));

  
  GreaterThan_relop2 <= '1' WHEN Duty_1_1 > Carrier_unsigned ELSE
      '0';

  Duty_2_1 <= unsigned(Duty(2));

  
  GreaterThan_relop3 <= '1' WHEN Duty_2_1 > Carrier_unsigned ELSE
      '0';

  PWM_H(0) <= GreaterThan_relop1;
  PWM_H(1) <= GreaterThan_relop2;
  PWM_H(2) <= GreaterThan_relop3;

  PWM_H_0 <= PWM_H(0);

  Constant1_out1 <= '1';

  
  PWM_H_0_1 <= PWM_H_0 WHEN Equal_0 = '0' ELSE
      Constant1_out1;

  Equal_1 <= Equal(1);

  PWM_H_1 <= PWM_H(1);

  
  PWM_H_1_1 <= PWM_H_1 WHEN Equal_1 = '0' ELSE
      Constant1_out1;

  Equal_2 <= Equal(2);

  PWM_H_2 <= PWM_H(2);

  
  PWM_H_2_1 <= PWM_H_2 WHEN Equal_2 = '0' ELSE
      Constant1_out1;

  PWM_H_3(0) <= PWM_H_0_1;
  PWM_H_3(1) <= PWM_H_1_1;
  PWM_H_3(2) <= PWM_H_2_1;

  PWM_H_0_2 <= PWM_H_3(0);

  Delay1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_1_reg <= (OTHERS => '0');
      Delay1_1_reg_1 <= (OTHERS => '0');
      Delay1_1_reg_2 <= (OTHERS => '0');
      Delay1_1_reg_3 <= (OTHERS => '0');
      Delay1_1_reg_4 <= (OTHERS => '0');
      Delay1_1_reg_5 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_1_reg(0) <= PWM_H_0_2;
        Delay1_1_reg(1 TO 49) <= Delay1_1_reg(0 TO 48);
        Delay1_1_reg_1(0) <= PWM_H_1_2;
        Delay1_1_reg_1(1 TO 49) <= Delay1_1_reg_1(0 TO 48);
        Delay1_1_reg_2(0) <= PWM_H_2_2;
        Delay1_1_reg_2(1 TO 49) <= Delay1_1_reg_2(0 TO 48);
        Delay1_1_reg_3(0) <= PWM_L_0;
        Delay1_1_reg_3(1 TO 49) <= Delay1_1_reg_3(0 TO 48);
        Delay1_1_reg_4(0) <= PWM_L_1;
        Delay1_1_reg_4(1 TO 49) <= Delay1_1_reg_4(0 TO 48);
        Delay1_1_reg_5(0) <= PWM_L_2;
        Delay1_1_reg_5(1 TO 49) <= Delay1_1_reg_5(0 TO 48);
      END IF;
    END IF;
  END PROCESS Delay1_1_process;

  Delay1_out_1 <= Delay1_1_reg(49);
  Delay1_out_2 <= Delay1_1_reg_1(49);
  Delay1_out_3 <= Delay1_1_reg_2(49);
  Delay1_out_4 <= Delay1_1_reg_3(49);
  Delay1_out_5 <= Delay1_1_reg_4(49);
  Delay1_out_6 <= Delay1_1_reg_5(49);

  Mux1_out1_0 <= PWM_H_0_2 AND Delay1_out_1;

  PWM_H_1_2 <= PWM_H_3(1);

  Mux1_out1_1 <= PWM_H_1_2 AND Delay1_out_2;

  PWM_H_2_2 <= PWM_H_3(2);

  Mux1_out1_2 <= PWM_H_2_2 AND Delay1_out_3;

  PWM_H_0_3 <= PWM_H_3(0);

  PWM_H_0_4 <=  NOT PWM_H_0_3;

  PWM_H_1_3 <= PWM_H_3(1);

  PWM_H_1_4 <=  NOT PWM_H_1_3;

  PWM_H_2_3 <= PWM_H_3(2);

  PWM_H_2_4 <=  NOT PWM_H_2_3;

  PWM_L(0) <= PWM_H_0_4;
  PWM_L(1) <= PWM_H_1_4;
  PWM_L(2) <= PWM_H_2_4;

  PWM_L_0 <= PWM_L(0);

  Mux1_out1_3 <= PWM_L_0 AND Delay1_out_4;

  PWM_L_1 <= PWM_L(1);

  Mux1_out1_4 <= PWM_L_1 AND Delay1_out_5;

  PWM_L_2 <= PWM_L(2);

  Mux1_out1_5 <= PWM_L_2 AND Delay1_out_6;

  PWM(0) <= Mux1_out1_0;
  PWM(1) <= Mux1_out1_1;
  PWM(2) <= Mux1_out1_2;
  PWM(3) <= Mux1_out1_3;
  PWM(4) <= Mux1_out1_4;
  PWM(5) <= Mux1_out1_5;



END rtl;

