-- -------------------------------------------------------------
-- 
-- File Name: CodeGen\hdlsrc\PWM\PWM_ip_src_S_H_Enable.vhd
-- Created: 2023-01-23 08:19:54
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip_src_S_H_Enable
-- Source Path: PWM/S&H Enable
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PWM_ip_src_S_H_Enable IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        u                                 :   IN    std_logic;
        S                                 :   IN    std_logic;
        y                                 :   OUT   std_logic
        );
END PWM_ip_src_S_H_Enable;


ARCHITECTURE rtl OF PWM_ip_src_S_H_Enable IS

  -- Component Declarations
  COMPONENT PWM_ip_src_Discrete_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          u                               :   IN    std_logic;
          S                               :   IN    std_logic;
          y                               :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : PWM_ip_src_Discrete_block
    USE ENTITY work.PWM_ip_src_Discrete_block(rtl);

  -- Signals
  SIGNAL Discrete_out1                    : std_logic;

BEGIN
  u_Discrete : PWM_ip_src_Discrete_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              u => u,
              S => S,
              y => Discrete_out1
              );

  y <= Discrete_out1;

END rtl;

