-- -------------------------------------------------------------
-- 
-- File Name: CodeGen\hdlsrc\PWM\PWM_ip_addr_decoder.vhd
-- Created: 2023-01-23 08:19:58
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip_addr_decoder
-- Source Path: PWM_ip/PWM_ip_axi_lite/PWM_ip_addr_decoder
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PWM_ip_addr_decoder IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        data_write                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        addr_sel                          :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
        wr_enb                            :   IN    std_logic;  -- ufix1
        rd_enb                            :   IN    std_logic;  -- ufix1
        read_ip_timestamp                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        read_PWM_Freq                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
        read_PWM_CntDir                   :   IN    std_logic;  -- ufix1
        data_read                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_axi_enable                  :   OUT   std_logic;  -- ufix1
        write_Deadtime                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        write_Frequency                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
        write_Enable                      :   OUT   std_logic;  -- ufix1
        write_Duty_U                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
        write_Duty_V                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
        write_Duty_W                      :   OUT   std_logic_vector(15 DOWNTO 0)  -- ufix16_En16
        );
END PWM_ip_addr_decoder;


ARCHITECTURE rtl OF PWM_ip_addr_decoder IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL addr_sel_unsigned                : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL decode_sel_PWM_Freq_1_1          : std_logic;  -- ufix1
  SIGNAL decode_sel_Duty_W_1_1            : std_logic;  -- ufix1
  SIGNAL decode_sel_Duty_V_1_1            : std_logic;  -- ufix1
  SIGNAL decode_sel_Duty_U_1_1            : std_logic;  -- ufix1
  SIGNAL decode_sel_Enable_1_1            : std_logic;  -- ufix1
  SIGNAL decode_sel_Frequency_1_1         : std_logic;  -- ufix1
  SIGNAL decode_sel_Deadtime_1_1          : std_logic;  -- ufix1
  SIGNAL decode_sel_ip_timestamp_1_1      : std_logic;  -- ufix1
  SIGNAL decode_sel_axi_enable_1_1        : std_logic;  -- ufix1
  SIGNAL const_0                          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reg_enb_axi_enable_1_1           : std_logic;  -- ufix1
  SIGNAL data_write_unsigned              : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL data_in_axi_enable               : std_logic;  -- ufix1
  SIGNAL const_1_1                        : std_logic;  -- ufix1
  SIGNAL data_reg_axi_enable_1_1          : std_logic;  -- ufix1
  SIGNAL write_concats_axi_enable_1       : std_logic;  -- ufix1
  SIGNAL data_slice_axi_enable_1          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_ip_timestamp_unsigned       : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_axi_enable_1_1         : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_reg_ip_timestamp            : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_ip_timestamp_1_1       : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reg_enb_Deadtime_1_1             : std_logic;  -- ufix1
  SIGNAL data_in_Deadtime                 : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL data_reg_Deadtime_1_1            : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL data_slice_Deadtime_1            : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_Deadtime_1_1           : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reg_enb_Frequency_1_1            : std_logic;  -- ufix1
  SIGNAL data_in_Frequency                : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL data_reg_Frequency_1_1           : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL data_slice_Frequency_1           : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_Frequency_1_1          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reg_enb_Enable_1_1               : std_logic;  -- ufix1
  SIGNAL data_in_Enable                   : std_logic;  -- ufix1
  SIGNAL data_reg_Enable_1_1              : std_logic;  -- ufix1
  SIGNAL write_concats_Enable_1           : std_logic;  -- ufix1
  SIGNAL data_slice_Enable_1              : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_Enable_1_1             : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reg_enb_Duty_U_1_1               : std_logic;  -- ufix1
  SIGNAL data_in_Duty_U                   : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL data_reg_Duty_U_1_1              : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL data_slice_Duty_U_1              : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_Duty_U_1_1             : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reg_enb_Duty_V_1_1               : std_logic;  -- ufix1
  SIGNAL data_in_Duty_V                   : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL data_reg_Duty_V_1_1              : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL data_slice_Duty_V_1              : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_Duty_V_1_1             : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reg_enb_Duty_W_1_1               : std_logic;  -- ufix1
  SIGNAL data_in_Duty_W                   : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL data_reg_Duty_W_1_1              : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL data_slice_Duty_W_1              : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_PWM_Freq_unsigned           : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL decode_sel_PWM_CntDir_1_1        : std_logic;  -- ufix1
  SIGNAL decode_rd_Duty_W_1_1             : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_reg_PWM_Freq                : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL data_slice_PWM_Freq_1            : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_PWM_Freq_1_1           : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_reg_PWM_CntDir              : std_logic;  -- ufix1
  SIGNAL data_slice_PWM_CntDir_1          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_PWM_CntDir_1_1         : unsigned(31 DOWNTO 0);  -- ufix32

BEGIN
  addr_sel_unsigned <= unsigned(addr_sel);

  
  decode_sel_PWM_Freq_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0046#, 14) ELSE
      '0';

  
  decode_sel_Duty_W_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0045#, 14) ELSE
      '0';

  
  decode_sel_Duty_V_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0044#, 14) ELSE
      '0';

  
  decode_sel_Duty_U_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0043#, 14) ELSE
      '0';

  
  decode_sel_Enable_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0042#, 14) ELSE
      '0';

  
  decode_sel_Frequency_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0041#, 14) ELSE
      '0';

  
  decode_sel_Deadtime_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0040#, 14) ELSE
      '0';

  
  decode_sel_ip_timestamp_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0002#, 14) ELSE
      '0';

  
  decode_sel_axi_enable_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0001#, 14) ELSE
      '0';

  const_0 <= to_unsigned(0, 32);

  reg_enb_axi_enable_1_1 <= decode_sel_axi_enable_1_1 AND wr_enb;

  data_write_unsigned <= unsigned(data_write);

  data_in_axi_enable <= data_write_unsigned(0);

  const_1_1 <= '1';

  enb <= const_1_1;

  reg_axi_enable_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_axi_enable_1_1 <= '1';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_axi_enable_1_1 = '1' THEN
        data_reg_axi_enable_1_1 <= data_in_axi_enable;
      END IF;
    END IF;
  END PROCESS reg_axi_enable_1_1_process;


  write_concats_axi_enable_1 <= data_reg_axi_enable_1_1;

  data_slice_axi_enable_1 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & write_concats_axi_enable_1;

  read_ip_timestamp_unsigned <= unsigned(read_ip_timestamp);

  
  decode_rd_axi_enable_1_1 <= const_0 WHEN decode_sel_axi_enable_1_1 = '0' ELSE
      data_slice_axi_enable_1;

  reg_ip_timestamp_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      read_reg_ip_timestamp <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_ip_timestamp <= read_ip_timestamp_unsigned;
      END IF;
    END IF;
  END PROCESS reg_ip_timestamp_process;


  
  decode_rd_ip_timestamp_1_1 <= decode_rd_axi_enable_1_1 WHEN decode_sel_ip_timestamp_1_1 = '0' ELSE
      read_reg_ip_timestamp;

  reg_enb_Deadtime_1_1 <= decode_sel_Deadtime_1_1 AND wr_enb;

  data_in_Deadtime <= data_write_unsigned(15 DOWNTO 0);

  reg_Deadtime_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_Deadtime_1_1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_Deadtime_1_1 = '1' THEN
        data_reg_Deadtime_1_1 <= data_in_Deadtime;
      END IF;
    END IF;
  END PROCESS reg_Deadtime_1_1_process;


  data_slice_Deadtime_1 <= resize(data_reg_Deadtime_1_1, 32);

  
  decode_rd_Deadtime_1_1 <= decode_rd_ip_timestamp_1_1 WHEN decode_sel_Deadtime_1_1 = '0' ELSE
      data_slice_Deadtime_1;

  reg_enb_Frequency_1_1 <= decode_sel_Frequency_1_1 AND wr_enb;

  data_in_Frequency <= data_write_unsigned;

  reg_Frequency_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_Frequency_1_1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_Frequency_1_1 = '1' THEN
        data_reg_Frequency_1_1 <= data_in_Frequency;
      END IF;
    END IF;
  END PROCESS reg_Frequency_1_1_process;


  data_slice_Frequency_1 <= data_reg_Frequency_1_1;

  
  decode_rd_Frequency_1_1 <= decode_rd_Deadtime_1_1 WHEN decode_sel_Frequency_1_1 = '0' ELSE
      data_slice_Frequency_1;

  reg_enb_Enable_1_1 <= decode_sel_Enable_1_1 AND wr_enb;

  data_in_Enable <= data_write_unsigned(0);

  reg_Enable_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_Enable_1_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_Enable_1_1 = '1' THEN
        data_reg_Enable_1_1 <= data_in_Enable;
      END IF;
    END IF;
  END PROCESS reg_Enable_1_1_process;


  write_concats_Enable_1 <= data_reg_Enable_1_1;

  data_slice_Enable_1 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & write_concats_Enable_1;

  
  decode_rd_Enable_1_1 <= decode_rd_Frequency_1_1 WHEN decode_sel_Enable_1_1 = '0' ELSE
      data_slice_Enable_1;

  reg_enb_Duty_U_1_1 <= decode_sel_Duty_U_1_1 AND wr_enb;

  data_in_Duty_U <= data_write_unsigned(15 DOWNTO 0);

  reg_Duty_U_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_Duty_U_1_1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_Duty_U_1_1 = '1' THEN
        data_reg_Duty_U_1_1 <= data_in_Duty_U;
      END IF;
    END IF;
  END PROCESS reg_Duty_U_1_1_process;


  data_slice_Duty_U_1 <= resize(data_reg_Duty_U_1_1, 32);

  
  decode_rd_Duty_U_1_1 <= decode_rd_Enable_1_1 WHEN decode_sel_Duty_U_1_1 = '0' ELSE
      data_slice_Duty_U_1;

  reg_enb_Duty_V_1_1 <= decode_sel_Duty_V_1_1 AND wr_enb;

  data_in_Duty_V <= data_write_unsigned(15 DOWNTO 0);

  reg_Duty_V_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_Duty_V_1_1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_Duty_V_1_1 = '1' THEN
        data_reg_Duty_V_1_1 <= data_in_Duty_V;
      END IF;
    END IF;
  END PROCESS reg_Duty_V_1_1_process;


  data_slice_Duty_V_1 <= resize(data_reg_Duty_V_1_1, 32);

  
  decode_rd_Duty_V_1_1 <= decode_rd_Duty_U_1_1 WHEN decode_sel_Duty_V_1_1 = '0' ELSE
      data_slice_Duty_V_1;

  reg_enb_Duty_W_1_1 <= decode_sel_Duty_W_1_1 AND wr_enb;

  data_in_Duty_W <= data_write_unsigned(15 DOWNTO 0);

  reg_Duty_W_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_Duty_W_1_1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_Duty_W_1_1 = '1' THEN
        data_reg_Duty_W_1_1 <= data_in_Duty_W;
      END IF;
    END IF;
  END PROCESS reg_Duty_W_1_1_process;


  data_slice_Duty_W_1 <= resize(data_reg_Duty_W_1_1, 32);

  read_PWM_Freq_unsigned <= unsigned(read_PWM_Freq);

  
  decode_sel_PWM_CntDir_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0047#, 14) ELSE
      '0';

  
  decode_rd_Duty_W_1_1 <= decode_rd_Duty_V_1_1 WHEN decode_sel_Duty_W_1_1 = '0' ELSE
      data_slice_Duty_W_1;

  reg_PWM_Freq_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      read_reg_PWM_Freq <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_PWM_Freq <= read_PWM_Freq_unsigned;
      END IF;
    END IF;
  END PROCESS reg_PWM_Freq_process;


  data_slice_PWM_Freq_1 <= read_reg_PWM_Freq;

  
  decode_rd_PWM_Freq_1_1 <= decode_rd_Duty_W_1_1 WHEN decode_sel_PWM_Freq_1_1 = '0' ELSE
      data_slice_PWM_Freq_1;

  reg_PWM_CntDir_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      read_reg_PWM_CntDir <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_PWM_CntDir <= read_PWM_CntDir;
      END IF;
    END IF;
  END PROCESS reg_PWM_CntDir_process;


  data_slice_PWM_CntDir_1 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & read_reg_PWM_CntDir;

  
  decode_rd_PWM_CntDir_1_1 <= decode_rd_PWM_Freq_1_1 WHEN decode_sel_PWM_CntDir_1_1 = '0' ELSE
      data_slice_PWM_CntDir_1;

  data_read <= std_logic_vector(decode_rd_PWM_CntDir_1_1);

  write_axi_enable <= write_concats_axi_enable_1;

  write_Deadtime <= std_logic_vector(data_reg_Deadtime_1_1);

  write_Frequency <= std_logic_vector(data_reg_Frequency_1_1);

  write_Enable <= write_concats_Enable_1;

  write_Duty_U <= std_logic_vector(data_reg_Duty_U_1_1);

  write_Duty_V <= std_logic_vector(data_reg_Duty_V_1_1);

  write_Duty_W <= std_logic_vector(data_reg_Duty_W_1_1);

END rtl;

