-- -------------------------------------------------------------
-- 
-- File Name: CodeGen\hdlsrc\PWM\PWM_ip_src_PWM.vhd
-- Created: 2023-01-23 08:19:54
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2e-08
-- Target subsystem base rate: 2e-08
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        2e-08
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- PWM_Trig                      ce_out        2e-08
-- PWM_UH                        ce_out        2e-08
-- PWM_UL                        ce_out        2e-08
-- PWM_VH                        ce_out        2e-08
-- PWM_VL                        ce_out        2e-08
-- PWM_WH                        ce_out        2e-08
-- PWM_WL                        ce_out        2e-08
-- PWM_CntDir                    ce_out        2e-08
-- PWM_Freq                      ce_out        2e-08
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip_src_PWM
-- Source Path: PWM
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.PWM_ip_src_PWM_pkg.ALL;

ENTITY PWM_ip_src_PWM IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        Deadtime                          :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Enable                            :   IN    std_logic;
        Frequency                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
        Duty_U                            :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
        Duty_V                            :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
        Duty_W                            :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
        ce_out                            :   OUT   std_logic;
        PWM_Trig                          :   OUT   std_logic;
        PWM_UH                            :   OUT   std_logic;
        PWM_UL                            :   OUT   std_logic;
        PWM_VH                            :   OUT   std_logic;
        PWM_VL                            :   OUT   std_logic;
        PWM_WH                            :   OUT   std_logic;
        PWM_WL                            :   OUT   std_logic;
        PWM_CntDir                        :   OUT   std_logic;
        PWM_Freq                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32_En32
        );
END PWM_ip_src_PWM;


ARCHITECTURE rtl OF PWM_ip_src_PWM IS

  -- Component Declarations
  COMPONENT PWM_ip_src_S_H_Frequncy
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          u                               :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
          S                               :   IN    std_logic;
          y                               :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32_En32
          );
  END COMPONENT;

  COMPONENT PWM_ip_src_Triangle_Carrier
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Frequency                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
          Carrier                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
          Dir                             :   OUT   std_logic;
          Trigger                         :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT PWM_ip_src_S_H_Enable
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          u                               :   IN    std_logic;
          S                               :   IN    std_logic;
          y                               :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT PWM_ip_src_S_H_Duty
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          u                               :   IN    vector_of_std_logic_vector16(0 TO 2);  -- ufix16_En16 [3]
          S                               :   IN    std_logic;
          y                               :   OUT   vector_of_std_logic_vector16(0 TO 2)  -- ufix16_En16 [3]
          );
  END COMPONENT;

  COMPONENT PWM_ip_src_PWM_with_deadtime
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Duty                            :   IN    vector_of_std_logic_vector16(0 TO 2);  -- ufix16_En16 [3]
          Carrier                         :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
          PWM                             :   OUT   std_logic_vector(0 TO 5)  -- boolean [6]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : PWM_ip_src_S_H_Frequncy
    USE ENTITY work.PWM_ip_src_S_H_Frequncy(rtl);

  FOR ALL : PWM_ip_src_Triangle_Carrier
    USE ENTITY work.PWM_ip_src_Triangle_Carrier(rtl);

  FOR ALL : PWM_ip_src_S_H_Enable
    USE ENTITY work.PWM_ip_src_S_H_Enable(rtl);

  FOR ALL : PWM_ip_src_S_H_Duty
    USE ENTITY work.PWM_ip_src_S_H_Duty(rtl);

  FOR ALL : PWM_ip_src_PWM_with_deadtime
    USE ENTITY work.PWM_ip_src_PWM_with_deadtime(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL Triangle_Carrier_out3            : std_logic;
  SIGNAL S_H_Frequncy_out1                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL S_H_Frequncy_out1_unsigned       : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL Saturation_out1                  : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL Carrier                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Dir                              : std_logic;
  SIGNAL Delay3_out1                      : std_logic;
  SIGNAL Data_Type_Conversion5_out1       : std_logic;
  SIGNAL S_H_Enable_out1                  : std_logic;
  SIGNAL Constant_out1                    : std_logic;
  SIGNAL Constant_out1_scalarexpand       : std_logic_vector(0 TO 5);  -- boolean [6]
  SIGNAL Mux_out1                         : vector_of_unsigned16(0 TO 2);  -- ufix16_En16 [3]
  SIGNAL Data_Type_Conversion2_out1       : vector_of_std_logic_vector16(0 TO 2);  -- ufix16 [3]
  SIGNAL S_H_Duty_out1                    : vector_of_std_logic_vector16(0 TO 2);  -- ufix16 [3]
  SIGNAL S_H_Duty_out1_unsigned           : vector_of_unsigned16(0 TO 2);  -- ufix16_En16 [3]
  SIGNAL Delay2_out1                      : vector_of_unsigned16(0 TO 2);  -- ufix16_En16 [3]
  SIGNAL Delay2_out1_1                    : vector_of_std_logic_vector16(0 TO 2);  -- ufix16 [3]
  SIGNAL PWM                              : std_logic_vector(0 TO 5);  -- boolean [6]
  SIGNAL Switch_out1                      : std_logic_vector(0 TO 5);  -- boolean [6]
  SIGNAL Delay1_out1                      : std_logic_vector(0 TO 5);  -- boolean [6]
  SIGNAL Delay5_out1                      : std_logic;
  SIGNAL Delay4_out1                      : unsigned(31 DOWNTO 0);  -- ufix32_En32

BEGIN
  -- !!! Deadtime is fixed to Inverter.Deadtime !!!

  u_S_H_Frequncy : PWM_ip_src_S_H_Frequncy
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              u => Frequency,  -- ufix32_En32
              S => Triangle_Carrier_out3,
              y => S_H_Frequncy_out1  -- ufix32_En32
              );

  u_Triangle_Carrier : PWM_ip_src_Triangle_Carrier
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Frequency => std_logic_vector(Saturation_out1),  -- ufix32_En32
              Carrier => Carrier,  -- ufix16_En16
              Dir => Dir,
              Trigger => Triangle_Carrier_out3
              );

  u_S_H_Enable : PWM_ip_src_S_H_Enable
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              u => Data_Type_Conversion5_out1,
              S => Triangle_Carrier_out3,
              y => S_H_Enable_out1
              );

  u_S_H_Duty : PWM_ip_src_S_H_Duty
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              u => Data_Type_Conversion2_out1,  -- ufix16_En16 [3]
              S => Triangle_Carrier_out3,
              y => S_H_Duty_out1  -- ufix16_En16 [3]
              );

  u_PWM_with_deadtime : PWM_ip_src_PWM_with_deadtime
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Duty => Delay2_out1_1,  -- ufix16_En16 [3]
              Carrier => Carrier,  -- ufix16_En16
              PWM => PWM  -- boolean [6]
              );

  S_H_Frequncy_out1_unsigned <= unsigned(S_H_Frequncy_out1);

  
  Saturation_out1 <= to_unsigned(2748779, 32) WHEN S_H_Frequncy_out1_unsigned > to_unsigned(2748779, 32) ELSE
      to_unsigned(687195, 32) WHEN S_H_Frequncy_out1_unsigned < to_unsigned(687195, 32) ELSE
      S_H_Frequncy_out1_unsigned;

  enb <= clk_enable;

  Delay3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay3_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay3_out1 <= Triangle_Carrier_out3;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  
  Data_Type_Conversion5_out1 <= '1' WHEN Enable /= '0' ELSE
      '0';

  Constant_out1 <= '0';

  Constant_out1_scalarexpand(0) <= Constant_out1;
  Constant_out1_scalarexpand(1) <= Constant_out1;
  Constant_out1_scalarexpand(2) <= Constant_out1;
  Constant_out1_scalarexpand(3) <= Constant_out1;
  Constant_out1_scalarexpand(4) <= Constant_out1;
  Constant_out1_scalarexpand(5) <= Constant_out1;

  Mux_out1(0) <= unsigned(Duty_U);
  Mux_out1(1) <= unsigned(Duty_V);
  Mux_out1(2) <= unsigned(Duty_W);

  outputgen2: FOR k IN 0 TO 2 GENERATE
    Data_Type_Conversion2_out1(k) <= std_logic_vector(Mux_out1(k));
  END GENERATE;

  outputgen1: FOR k IN 0 TO 2 GENERATE
    S_H_Duty_out1_unsigned(k) <= unsigned(S_H_Duty_out1(k));
  END GENERATE;

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1 <= (OTHERS => to_unsigned(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay2_out1 <= S_H_Duty_out1_unsigned;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  outputgen: FOR k IN 0 TO 2 GENERATE
    Delay2_out1_1(k) <= std_logic_vector(Delay2_out1(k));
  END GENERATE;

  
  Switch_out1 <= Constant_out1_scalarexpand WHEN S_H_Enable_out1 = '0' ELSE
      PWM;

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_out1 <= Switch_out1;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  Delay5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay5_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay5_out1 <= Dir;
      END IF;
    END IF;
  END PROCESS Delay5_process;


  Delay4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay4_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay4_out1 <= Saturation_out1;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  PWM_Freq <= std_logic_vector(Delay4_out1);

  ce_out <= clk_enable;


  PWM_Trig <= Delay3_out1;

  PWM_UH <= Delay1_out1(0);

  PWM_UL <= Delay1_out1(3);

  PWM_VH <= Delay1_out1(1);

  PWM_VL <= Delay1_out1(4);

  PWM_WH <= Delay1_out1(2);

  PWM_WL <= Delay1_out1(5);

  PWM_CntDir <= Delay5_out1;

END rtl;

