-- -------------------------------------------------------------
-- 
-- File Name: CodeGen\hdlsrc\PWM\PWM_ip_src_Triangle_Carrier.vhd
-- Created: 2023-01-23 08:19:54
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip_src_Triangle_Carrier
-- Source Path: PWM/Triangle Carrier
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PWM_ip_src_Triangle_Carrier IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Frequency                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
        Carrier                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
        Dir                               :   OUT   std_logic;
        Trigger                           :   OUT   std_logic
        );
END PWM_ip_src_Triangle_Carrier;


ARCHITECTURE rtl OF PWM_ip_src_Triangle_Carrier IS

  -- Component Declarations
  COMPONENT PWM_ip_src_Detect_Change
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          U                               :   IN    std_logic;
          Y                               :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : PWM_ip_src_Detect_Change
    USE ENTITY work.PWM_ip_src_Detect_Change(rtl);

  -- Signals
  SIGNAL Relay_offOp_val                  : std_logic;
  SIGNAL Relay_onOp_val                   : std_logic;
  SIGNAL Frequency_unsigned               : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL Delay_out1                       : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL Sum2_add_cast                    : unsigned(32 DOWNTO 0);  -- ufix33_En32
  SIGNAL Sum2_add_cast_1                  : unsigned(32 DOWNTO 0);  -- ufix33_En32
  SIGNAL Sum2_add_temp                    : unsigned(32 DOWNTO 0);  -- ufix33_En32
  SIGNAL Carrier_1                        : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL Sum3_sub_cast                    : signed(32 DOWNTO 0);  -- sfix33_En32
  SIGNAL Sum3_sub_cast_1                  : signed(32 DOWNTO 0);  -- sfix33_En32
  SIGNAL Sum3_sub_temp                    : signed(32 DOWNTO 0);  -- sfix33_En32
  SIGNAL Sum3_out1                        : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL Dir_1                            : std_logic;
  SIGNAL Relay_FB_sig                     : std_logic;
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Relay_conn_sig                   : std_logic;
  SIGNAL switch_compare_1_1               : std_logic;
  SIGNAL Carrier_2                        : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL Data_Type_Conversion3_out1       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL Detect_Change_out1               : std_logic;

BEGIN
  u_Detect_Change : PWM_ip_src_Detect_Change
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              U => Dir_1,
              Y => Detect_Change_out1
              );

  Relay_offOp_val <= '1';

  Relay_onOp_val <= '0';

  Frequency_unsigned <= unsigned(Frequency);

  Sum2_add_cast <= resize(Delay_out1, 33);
  Sum2_add_cast_1 <= resize(Frequency_unsigned, 33);
  Sum2_add_temp <= Sum2_add_cast + Sum2_add_cast_1;
  
  Carrier_1 <= X"FFFFFFFF" WHEN Sum2_add_temp(32) /= '0' ELSE
      Sum2_add_temp(31 DOWNTO 0);

  Sum3_sub_cast <= signed(resize(Delay_out1, 33));
  Sum3_sub_cast_1 <= signed(resize(Frequency_unsigned, 33));
  Sum3_sub_temp <= Sum3_sub_cast - Sum3_sub_cast_1;
  
  Sum3_out1 <= X"00000000" WHEN Sum3_sub_temp(32) = '1' ELSE
      unsigned(Sum3_sub_temp(31 DOWNTO 0));

  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Relay_FB_sig <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Relay_FB_sig <= Dir_1;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  
  switch_compare_1 <= '1' WHEN Delay_out1 = unsigned'(X"FFFFFFFF") ELSE
      '0';

  
  Relay_conn_sig <= Relay_FB_sig WHEN switch_compare_1 = '0' ELSE
      Relay_onOp_val;

  
  switch_compare_1_1 <= '1' WHEN Delay_out1 > to_unsigned(0, 32) ELSE
      '0';

  
  Dir_1 <= Relay_offOp_val WHEN switch_compare_1_1 = '0' ELSE
      Relay_conn_sig;

  
  Carrier_2 <= Sum3_out1 WHEN Dir_1 = '0' ELSE
      Carrier_1;

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_out1 <= Carrier_2;
      END IF;
    END IF;
  END PROCESS Delay_process;


  Data_Type_Conversion3_out1 <= Delay_out1(31 DOWNTO 16);

  Carrier <= std_logic_vector(Data_Type_Conversion3_out1);

  Dir <= Dir_1;

  Trigger <= Detect_Change_out1;

END rtl;

