-- -------------------------------------------------------------
-- 
-- File Name: CodeGen\hdlsrc\PWM\PWM_ip_src_S_H_Duty.vhd
-- Created: 2023-01-23 08:19:54
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip_src_S_H_Duty
-- Source Path: PWM/S&H Duty
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.PWM_ip_src_PWM_pkg.ALL;

ENTITY PWM_ip_src_S_H_Duty IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        u                                 :   IN    vector_of_std_logic_vector16(0 TO 2);  -- ufix16_En16 [3]
        S                                 :   IN    std_logic;
        y                                 :   OUT   vector_of_std_logic_vector16(0 TO 2)  -- ufix16_En16 [3]
        );
END PWM_ip_src_S_H_Duty;


ARCHITECTURE rtl OF PWM_ip_src_S_H_Duty IS

  -- Component Declarations
  COMPONENT PWM_ip_src_Discrete
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          u                               :   IN    vector_of_std_logic_vector16(0 TO 2);  -- ufix16_En16 [3]
          S                               :   IN    std_logic;
          y                               :   OUT   vector_of_std_logic_vector16(0 TO 2)  -- ufix16_En16 [3]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : PWM_ip_src_Discrete
    USE ENTITY work.PWM_ip_src_Discrete(rtl);

  -- Signals
  SIGNAL Discrete_out1                    : vector_of_std_logic_vector16(0 TO 2);  -- ufix16 [3]

BEGIN
  u_Discrete : PWM_ip_src_Discrete
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              u => u,  -- ufix16_En16 [3]
              S => S,
              y => Discrete_out1  -- ufix16_En16 [3]
              );

  y <= Discrete_out1;

END rtl;

