-- -------------------------------------------------------------
-- 
-- File Name: CodeGen\hdlsrc\PWM\PWM_ip.vhd
-- Created: 2023-01-23 08:19:58
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: -1
-- Target subsystem base rate: -1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip
-- Source Path: PWM_ip
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PWM_ip IS
  PORT( IPCORE_CLK                        :   IN    std_logic;  -- ufix1
        IPCORE_RESETN                     :   IN    std_logic;  -- ufix1
        AXI4_Lite_ACLK                    :   IN    std_logic;  -- ufix1
        AXI4_Lite_ARESETN                 :   IN    std_logic;  -- ufix1
        AXI4_Lite_AWADDR                  :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        AXI4_Lite_AWVALID                 :   IN    std_logic;  -- ufix1
        AXI4_Lite_WDATA                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_Lite_WSTRB                   :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        AXI4_Lite_WVALID                  :   IN    std_logic;  -- ufix1
        AXI4_Lite_BREADY                  :   IN    std_logic;  -- ufix1
        AXI4_Lite_ARADDR                  :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        AXI4_Lite_ARVALID                 :   IN    std_logic;  -- ufix1
        AXI4_Lite_RREADY                  :   IN    std_logic;  -- ufix1
        PWM_Trig                          :   OUT   std_logic;  -- ufix1
        PWM_U                             :   OUT   std_logic_vector(1 downto 0);  -- ufix2
        PWM_V                             :   OUT   std_logic_vector(1 downto 0);  -- ufix2
        PWM_W                             :   OUT   std_logic_vector(1 downto 0);  -- ufix2
        AXI4_Lite_AWREADY                 :   OUT   std_logic;  -- ufix1
        AXI4_Lite_WREADY                  :   OUT   std_logic;  -- ufix1
        AXI4_Lite_BRESP                   :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI4_Lite_BVALID                  :   OUT   std_logic;  -- ufix1
        AXI4_Lite_ARREADY                 :   OUT   std_logic;  -- ufix1
        AXI4_Lite_RDATA                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_Lite_RRESP                   :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI4_Lite_RVALID                  :   OUT   std_logic  -- ufix1
        );
END PWM_ip;


ARCHITECTURE rtl OF PWM_ip IS

  -- Component Declarations
  COMPONENT PWM_ip_reset_sync
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset_in                        :   IN    std_logic;  -- ufix1
          reset_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT PWM_ip_axi_lite
    PORT( reset                           :   IN    std_logic;
          AXI4_Lite_ACLK                  :   IN    std_logic;  -- ufix1
          AXI4_Lite_ARESETN               :   IN    std_logic;  -- ufix1
          AXI4_Lite_AWADDR                :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          AXI4_Lite_AWVALID               :   IN    std_logic;  -- ufix1
          AXI4_Lite_WDATA                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_Lite_WSTRB                 :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          AXI4_Lite_WVALID                :   IN    std_logic;  -- ufix1
          AXI4_Lite_BREADY                :   IN    std_logic;  -- ufix1
          AXI4_Lite_ARADDR                :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          AXI4_Lite_ARVALID               :   IN    std_logic;  -- ufix1
          AXI4_Lite_RREADY                :   IN    std_logic;  -- ufix1
          read_ip_timestamp               :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          read_PWM_Freq                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
          read_PWM_CntDir                 :   IN    std_logic;  -- ufix1
          AXI4_Lite_AWREADY               :   OUT   std_logic;  -- ufix1
          AXI4_Lite_WREADY                :   OUT   std_logic;  -- ufix1
          AXI4_Lite_BRESP                 :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI4_Lite_BVALID                :   OUT   std_logic;  -- ufix1
          AXI4_Lite_ARREADY               :   OUT   std_logic;  -- ufix1
          AXI4_Lite_RDATA                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_Lite_RRESP                 :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI4_Lite_RVALID                :   OUT   std_logic;  -- ufix1
          write_axi_enable                :   OUT   std_logic;  -- ufix1
          write_Deadtime                  :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          write_Frequency                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
          write_Enable                    :   OUT   std_logic;  -- ufix1
          write_Duty_U                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
          write_Duty_V                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
          write_Duty_W                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
          reset_internal                  :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT PWM_ip_dut
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset                           :   IN    std_logic;
          dut_enable                      :   IN    std_logic;  -- ufix1
          Deadtime                        :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          Enable                          :   IN    std_logic;  -- ufix1
          Frequency                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
          Duty_U                          :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
          Duty_V                          :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
          Duty_W                          :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
          ce_out                          :   OUT   std_logic;  -- ufix1
          PWM_Trig                        :   OUT   std_logic;  -- ufix1
          PWM_U                           :   OUT   std_logic_vector(1 downto 0);  -- ufix2
          PWM_V                           :   OUT   std_logic_vector(1 downto 0);  -- ufix2
          PWM_W                           :   OUT   std_logic_vector(1 downto 0);  -- ufix2
          PWM_CntDir                      :   OUT   std_logic;  -- ufix1
          PWM_Freq                        :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32_En32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : PWM_ip_reset_sync
    USE ENTITY work.PWM_ip_reset_sync(rtl);

  FOR ALL : PWM_ip_axi_lite
    USE ENTITY work.PWM_ip_axi_lite(rtl);

  FOR ALL : PWM_ip_dut
    USE ENTITY work.PWM_ip_dut(rtl);

  -- Signals
  SIGNAL reset                            : std_logic;
  SIGNAL ip_timestamp                     : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reset_cm                         : std_logic;  -- ufix1
  SIGNAL reset_internal                   : std_logic;  -- ufix1
  SIGNAL reset_before_sync                : std_logic;  -- ufix1
  SIGNAL PWM_Freq_sig                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL PWM_CntDir_sig                   : std_logic;  -- ufix1
  SIGNAL AXI4_Lite_BRESP_tmp              : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL AXI4_Lite_RDATA_tmp              : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL AXI4_Lite_RRESP_tmp              : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL write_axi_enable                 : std_logic;  -- ufix1
  SIGNAL write_Deadtime                   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL write_Frequency                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_Enable                     : std_logic;  -- ufix1
  SIGNAL write_Duty_U                     : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL write_Duty_V                     : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL write_Duty_W                     : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL PWM_Trig_sig                     : std_logic;  -- ufix1
  SIGNAL PWM_U_sig                        : std_logic_vector(1 downto 0);  -- ufix2
  SIGNAL PWM_V_sig                        : std_logic_vector(1 downto 0);  -- ufix2
  SIGNAL PWM_W_sig                        : std_logic_vector(1 downto 0);  -- ufix2

BEGIN
  u_PWM_ip_reset_sync_inst : PWM_ip_reset_sync
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset_in => reset_before_sync,  -- ufix1
              reset_out => reset
              );

  u_PWM_ip_axi_lite_inst : PWM_ip_axi_lite
    PORT MAP( reset => reset,
              AXI4_Lite_ACLK => AXI4_Lite_ACLK,  -- ufix1
              AXI4_Lite_ARESETN => AXI4_Lite_ARESETN,  -- ufix1
              AXI4_Lite_AWADDR => AXI4_Lite_AWADDR,  -- ufix16
              AXI4_Lite_AWVALID => AXI4_Lite_AWVALID,  -- ufix1
              AXI4_Lite_WDATA => AXI4_Lite_WDATA,  -- ufix32
              AXI4_Lite_WSTRB => AXI4_Lite_WSTRB,  -- ufix4
              AXI4_Lite_WVALID => AXI4_Lite_WVALID,  -- ufix1
              AXI4_Lite_BREADY => AXI4_Lite_BREADY,  -- ufix1
              AXI4_Lite_ARADDR => AXI4_Lite_ARADDR,  -- ufix16
              AXI4_Lite_ARVALID => AXI4_Lite_ARVALID,  -- ufix1
              AXI4_Lite_RREADY => AXI4_Lite_RREADY,  -- ufix1
              read_ip_timestamp => std_logic_vector(ip_timestamp),  -- ufix32
              read_PWM_Freq => PWM_Freq_sig,  -- ufix32_En32
              read_PWM_CntDir => PWM_CntDir_sig,  -- ufix1
              AXI4_Lite_AWREADY => AXI4_Lite_AWREADY,  -- ufix1
              AXI4_Lite_WREADY => AXI4_Lite_WREADY,  -- ufix1
              AXI4_Lite_BRESP => AXI4_Lite_BRESP_tmp,  -- ufix2
              AXI4_Lite_BVALID => AXI4_Lite_BVALID,  -- ufix1
              AXI4_Lite_ARREADY => AXI4_Lite_ARREADY,  -- ufix1
              AXI4_Lite_RDATA => AXI4_Lite_RDATA_tmp,  -- ufix32
              AXI4_Lite_RRESP => AXI4_Lite_RRESP_tmp,  -- ufix2
              AXI4_Lite_RVALID => AXI4_Lite_RVALID,  -- ufix1
              write_axi_enable => write_axi_enable,  -- ufix1
              write_Deadtime => write_Deadtime,  -- ufix16
              write_Frequency => write_Frequency,  -- ufix32_En32
              write_Enable => write_Enable,  -- ufix1
              write_Duty_U => write_Duty_U,  -- ufix16_En16
              write_Duty_V => write_Duty_V,  -- ufix16_En16
              write_Duty_W => write_Duty_W,  -- ufix16_En16
              reset_internal => reset_internal  -- ufix1
              );

  u_PWM_ip_dut_inst : PWM_ip_dut
    PORT MAP( clk           => IPCORE_CLK,  -- ufix1
              reset         => reset,
              dut_enable    => write_axi_enable,  -- ufix1
              Deadtime      => write_Deadtime,  -- ufix16
              Enable        => write_Enable,  -- ufix1
              Frequency     => write_Frequency,  -- ufix32_En32
              Duty_U        => write_Duty_U,  -- ufix16_En16
              Duty_V        => write_Duty_V,  -- ufix16_En16
              Duty_W        => write_Duty_W,  -- ufix16_En16
              ce_out        => ce_out_sig,  -- ufix1
              PWM_Trig      => PWM_Trig_sig,  -- ufix1
              PWM_U         => PWM_U_sig,  -- ufix2
              PWM_V         => PWM_V_sig,  -- ufix2
              PWM_W         => PWM_W_sig,  -- ufix2
              PWM_CntDir    => PWM_CntDir_sig,  -- ufix1
              PWM_Freq      => PWM_Freq_sig  -- ufix32_En32
              );

  ip_timestamp <= unsigned'(X"8929FEE3");
      
  reset_cm <=  NOT IPCORE_RESETN;

  reset_before_sync <= reset_cm OR reset_internal;

  PWM_Trig <= PWM_Trig_sig;

  PWM_U <= PWM_U_sig;

  PWM_V <= PWM_V_sig;

  PWM_W <= PWM_W_sig;

  AXI4_Lite_BRESP <= AXI4_Lite_BRESP_tmp;

  AXI4_Lite_RDATA <= AXI4_Lite_RDATA_tmp;

  AXI4_Lite_RRESP <= AXI4_Lite_RRESP_tmp;

END rtl;

