/**************************************************
 ** Software Component SWC_Engine
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#include "rte.h"
#include "rte_signalpool.h"
#include "rte_activation.h"

#include "logging.h"
#include "engine.h"

#include "swc_engine.h"

/* Runnables */
void ENG_setControlSpeed_run()
{
    RC_t result = RC_SUCCESS;
    
    //Get the ticktime of this runnable
    uint16_t ticktime = RTE_getTickTime(RTE_cyclicActivationTable, RTE_cyclicActivation_size, ENG_setControlSpeed_run);
    
    //Get the targetspeed
    SPEED_data_t targetSpeed = SPEED_INIT_DATA;
    targetSpeed = RTE_SPEED_get(&SO_TARGETSPEED_signal);
    
    //Calculate the controlspeed 
    PWM_data_t controlSpeed = PWM_INIT_DATA;
    
    //And get the measured speed
    result = RTE_SPEED_pullPort(&SO_CURRENTSPEED_signal);
        
    SPEED_data_t measuredSpeed = RTE_SPEED_get(&SO_CURRENTSPEED_signal);
    
    //Calculate controlvalue and get measured speed
    result = ENG_SetEngineClosedLoopPID(ENG_1,ticktime, targetSpeed.m_rpm, measuredSpeed.m_rpm, &controlSpeed.m_dutycycle);
    
    //controlSpeed.m_dutycycle = targetSpeed.m_rpm * 10000 / 250;
    
    //LOG_I("ENG_setControlSpeed_run"," T: %d, M: %d, C: %d",targetSpeed.m_rpm, measuredSpeed.m_rpm, controlSpeed.m_dutycycle);
    
    //And write controlspeed to the engine
    result = RTE_PWM_set(&SO_CONTROLSPEED_signal, controlSpeed);
    result = RTE_PWM_pushPort(&SO_CONTROLSPEED_signal);
    
 
}
void ENG_showStatus_run()
{

   /* Enter your code here */
}
void ENG_errorHandler_run()
{

   LOG_I("ENG_errorHandler_run","Error engine");
}
