/**************************************************
 ** Software Component SWC_Control
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#include "rte.h"
#include "rte_signalpool.h"
#include "rte_activation.h"

#include "logging.h"
#include "ssd1306.h"

#include "engine_cfg.h"

#include "swc_control.h"


/*****************************************************************************/
/* State Machine Actions                                                     */
/*****************************************************************************/

static sint16_t CTRL__timerValue = 0;
static uint16_t CTRL__timerTickTime = 0;

//Actions

static void CTRL__engineStop(CARSTATE_data_t *const cardata);

static void CTRL__engineStart(CARSTATE_data_t *const cardata);

static void CTRL__startTimer(uint16_t timeout);

static void CTRL__decrementTimer(uint16_t ticktime);

static void CTRL__setTargetSpeed(CARSTATE_data_t *const cardata);

static void CTRL__reduceTargetSpeed();

static void CTRL__toggleDirection(CARSTATE_data_t *const cardata);

static void CTRL__setLed(LED_id_t led, LED_mode_t mode);



//Guards

static boolean_t CTRL__timerReachedZero();

static boolean_t CTRL__engineIsStopped();



/*****************************************************************************/
/* Runnables                                                                 */
/*****************************************************************************/


void CTRL_checkUserInput_run()
{
    RC_t result = RC_SUCCESS;
    
    //Set Ticktime upon first call
    if (0 == CTRL__timerTickTime)
    {
        CTRL__timerTickTime = RTE_getTickTime(RTE_cyclicActivationTable, RTE_cyclicActivation_size, CTRL_checkUserInput_run);
    }
    
    //Event signal
    EVENT_data_t ev = EVENT_INIT_DATA;
    
    //Get Button states
    
    //Brake
    result = RTE_BUTTON_pullPort(&SO_BRAKEBUTTON_signal);
    BUTTON_data_t brake = RTE_BUTTON_get(&SO_BRAKEBUTTON_signal);
    
    if (BUTTON_PRESSED == brake.m_button) 
    {
        ev.m_ev = EVENT_brakePressed;
        RTE_EVENT_set(&SO_EVENT_signal, ev);
    }
    
    if (BUTTON_DEPRESSED == brake.m_button) 
    {
        ev.m_ev = EVENT_brakeDepressed;
        RTE_EVENT_set(&SO_EVENT_signal, ev);
    }    
    
    //Ignition
    result = RTE_BUTTON_pullPort(&SO_IGNITIONBUTTON_signal);
    BUTTON_data_t ignition = RTE_BUTTON_get(&SO_IGNITIONBUTTON_signal);
    
    if (BUTTON_PRESSED == ignition.m_button) 
    {
        ev.m_ev = EVENT_ignitionPressed;
        RTE_EVENT_set(&SO_EVENT_signal, ev);
    }
    
    if (BUTTON_DEPRESSED == ignition.m_button) 
    {
        ev.m_ev = EVENT_ignitionDepressed;
        RTE_EVENT_set(&SO_EVENT_signal, ev);
    }    

    //LOG_I("CTRL_checkUserInput_run","B1 = %x",SO_DIRECTIONBUTTON_signal.value.m_button);
    //Direction
    result = RTE_BUTTON_pullPort(&SO_DIRECTIONBUTTON_signal);
    BUTTON_data_t direction = RTE_BUTTON_get(&SO_DIRECTIONBUTTON_signal);
    
    if (BUTTON_PRESSED == direction.m_button) 
    {
        ev.m_ev = EVENT_directionPressed;
        RTE_EVENT_set(&SO_EVENT_signal, ev);
    }
    
    if (BUTTON_DEPRESSED == direction.m_button) 
    {
        ev.m_ev = EVENT_directionDepressed;
        RTE_EVENT_set(&SO_EVENT_signal, ev);
    }    
    
    
    //And don't forget to fire a tick event in every cycle
    ev.m_ev = EVENT_tick;
    RTE_EVENT_set(&SO_EVENT_signal, ev);

}

void CTRL_state_run()
{
    //Get event and state
    EVENT_data_t ev = RTE_EVENT_get(&SO_EVENT_signal);
    CARSTATE_data_t carstate = RTE_CARSTATE_get(&SO_CARSTATE_signal);

    //Just for debugging
    CAR_state_t fromState = carstate.m_state;

    
    switch (carstate.m_state)
    {
    case ISIDLE: 
        if (EVENT_ignitionPressed == ev.m_ev)
        {
            CTRL__startTimer(1000);
            carstate.m_state = ISPRESSEDIGNITION;
        }
        break;
    
    case ISPRESSEDIGNITION:
        if (EVENT_tick == ev.m_ev)
        {
            if (TRUE == CTRL__timerReachedZero())
            {
                //Ignition was pressed for one second
                CTRL__setLed(LED_1, LED_ON);
                CTRL__startTimer(10000);
                carstate.m_state = ISIGNITIONSELFTEST_1;
            }
            else
            {
                CTRL__decrementTimer(CTRL__timerTickTime);
            }
        }
        else if (EVENT_ignitionDepressed == ev.m_ev)
        {
            //Ignition was depressed before timeout
            CTRL__engineStop(&carstate);
            carstate.m_state = ISIDLE;
        }
        
        break;
        
    case ISIGNITIONSELFTEST_1:
        if (EVENT_tick == ev.m_ev)
        {
            if (TRUE == CTRL__timerReachedZero())
            {
                //Brake was not pressed in time
                CTRL__setLed(LED_ALL, LED_OFF);
                carstate.m_state = ISIDLE;
            }
            else
            {
                CTRL__decrementTimer(CTRL__timerTickTime);
            }
        }
        else if (EVENT_brakePressed == ev.m_ev)
        {
            //Brake was pressed
            carstate.m_state = ISIGNITIONSELFTEST_2;
        }
        
        break;
        
    case ISIGNITIONSELFTEST_2:
        if (EVENT_tick == ev.m_ev)
        {
            if (TRUE == CTRL__timerReachedZero())
            {
                //Brake was not depressed in time
                CTRL__setLed(LED_ALL, LED_OFF);
                carstate.m_state = ISIDLE;
            }
            else
            {
                CTRL__decrementTimer(CTRL__timerTickTime);
            }
        }
        else if (EVENT_brakeDepressed == ev.m_ev)
        {
            //Brake was depressed
            CTRL__setLed(LED_2, LED_ON);
            carstate.m_state = ISDRIVING;
        }
        break;
    
    case ISDRIVING:
        if (EVENT_tick == ev.m_ev)
        {
            //Normal driving
            CTRL__setTargetSpeed(&carstate);
        }
        else if (EVENT_directionPressed == ev.m_ev)
        {
            if (TRUE == CTRL__engineIsStopped())
            {
                //Toggle driving direction
                CTRL__toggleDirection(&carstate);
            }
        }
        else if (EVENT_brakePressed == ev.m_ev)
        {
            CTRL__setLed(LED_3, LED_ON);
            carstate.m_state = ISBRAKING;
        }
        else if (EVENT_error == ev.m_ev)
        {
            //Error has occured
            CTRL__engineStop(&carstate);
            CTRL__setLed(LED_3, LED_ON);
            carstate.m_state = ISERROR;
        }
        else if (EVENT_ignitionPressed == ev.m_ev)
        {
            CTRL__engineStop(&carstate);
            CTRL__setLed(LED_ALL, LED_OFF);
            carstate.m_state = ISIDLE;
        }
            
        break;
        
    case ISBRAKING:
        if (EVENT_tick == ev.m_ev)
        {
            CTRL__reduceTargetSpeed();
        }
        else if (EVENT_brakeDepressed == ev.m_ev)
        {
            CTRL__setLed(LED_3, LED_OFF);
            carstate.m_state = ISDRIVING;
        }
        else if (EVENT_error == ev.m_ev)
        {
            //Error has occured
            CTRL__engineStop(&carstate);
            CTRL__setLed(LED_3, LED_ON);
            carstate.m_state = ISERROR;
        }
        else if (EVENT_ignitionPressed == ev.m_ev)
        {
            CTRL__engineStop(&carstate);
            CTRL__setLed(LED_ALL, LED_OFF);
            carstate.m_state = ISIDLE;
        }
            
        break;
    
    case ISERROR:
        if (EVENT_brakePressed == ev.m_ev)
        {
            CTRL__engineStop(&carstate);
            CTRL__setLed(LED_ALL, LED_OFF);
            carstate.m_state = ISIDLE;
        }
        break;
        
    }   
        
    if (ev.m_ev != EVENT_tick) LOG_I("CTRL_state_run","ev = %d fromstate = %d tostate = %d",ev.m_ev, fromState, carstate.m_state);
    
    //Write carstate back to RTE
    RTE_CARSTATE_set(&SO_CARSTATE_signal, carstate);
    

}


//Actions

static void CTRL__engineStop(CARSTATE_data_t *const cardata)
{
    RC_t result = RC_SUCCESS;
    
    cardata->m_maxSpeed = 0;
    cardata->m_direction = DIRECTION_NEUTRAL;
     
    SPEED_data_t targetSpeed = SPEED_INIT_DATA;
    targetSpeed.m_rpm = 0;
        
     SSD1306_write_line(1,"Engine Stopped");
     SSD1306_write_line(2,"");
    
    //Set the targetspeed and write to RTE
    result = RTE_SPEED_set(&SO_TARGETSPEED_signal, targetSpeed);
    
}

static void CTRL__engineStart(CARSTATE_data_t *const cardata)
{
    cardata->m_maxSpeed = ENG_MAXRPM;
}

static void CTRL__startTimer(uint16_t timeout)
{
    CTRL__timerValue = timeout;
}

static void CTRL__decrementTimer(uint16_t ticktime)
{
    CTRL__timerValue -= ticktime;
}

static void CTRL__setTargetSpeed(CARSTATE_data_t *const cardata)
{
    RC_t result = RC_SUCCESS;
    
    //Read in all required signals and check the status
    PEDAL_data_t pedal = RTE_PEDAL_get(&SO_PEDALPOSITION_signal);
    RTE_signalStatus_t pedalStatus = RTE_PEDAL_getStatus(&SO_PEDALPOSITION_signal);
    
    
    if (RTE_SIGNALSTATUS_VALID != pedalStatus) 
    {
        //In case pedal is invalid, automatically the last old value will used. 
        //Better: explizit check of pedal validity and don'T chenge the target signal
        
        return;
    }
    
    SPEED_data_t targetSpeed = SPEED_INIT_DATA;

    
    //Calculate targetspeed based on pedal position
    targetSpeed.m_rpm = (pedal.m_value * ENG_MAXRPM) / 100;
    
    if (DIRECTION_REVERSE == cardata->m_direction)
    {
        targetSpeed.m_rpm = -targetSpeed.m_rpm;
        
        //Limit speed - attention, negative values
        if (targetSpeed.m_rpm < ENG_MAXREVERSERPM)
        {
            targetSpeed.m_rpm = ENG_MAXREVERSERPM;
        }
    }
    else if (DIRECTION_NEUTRAL == cardata->m_direction)
    {
        targetSpeed.m_rpm = 0;
    }
    //Forward: nothing needs to be done;
    
    
    //Set the targetspeed and write to RTE
    result = RTE_SPEED_set(&SO_TARGETSPEED_signal, targetSpeed);
   
}

static void CTRL__reduceTargetSpeed()
{
    RC_t result = RC_SUCCESS;
    
    SPEED_data_t targetSpeed = RTE_SPEED_get(&SO_TARGETSPEED_signal);
    
    if (targetSpeed.m_rpm < 0) targetSpeed.m_rpm++ ;
    else if (targetSpeed.m_rpm > 0) targetSpeed.m_rpm-- ;
    
    //Set the targetspeed and write to RTE
    result = RTE_SPEED_set(&SO_TARGETSPEED_signal, targetSpeed);
    
}

static void CTRL__toggleDirection(CARSTATE_data_t *const cardata)
{
    switch (cardata->m_direction)
    {
        case DIRECTION_NEUTRAL:
            cardata->m_direction = DIRECTION_FORWARD;
            SSD1306_write_line(1,"Direction");
            SSD1306_write_line(2,"  - Forward");
        break;
        case DIRECTION_FORWARD:
            cardata->m_direction = DIRECTION_REVERSE;
            SSD1306_write_line(1,"Direction");
            SSD1306_write_line(2,"  - Reverse");
        break;
        case DIRECTION_REVERSE:
            cardata->m_direction = DIRECTION_NEUTRAL;
            SSD1306_write_line(1,"Direction");
            SSD1306_write_line(2,"  - Neutral");
        break;
    }
}

static void CTRL__setLed(LED_id_t led, LED_mode_t mode)
{
    LED_data_t led_s = RTE_LED_get(&SO_LED_signal);
    
    switch (led){
        case LED_1 : 
            led_s.m_led_1 = mode; 
        break;
        case LED_2 : 
            led_s.m_led_2 = mode; 
        break;
        case LED_3 : 
            led_s.m_led_3 = mode; 
        break;
        case LED_4 : 
            led_s.m_led_4 = mode; 
        break;
        case LED_ALL :
            led_s.m_led_1 = mode;
            led_s.m_led_2 = mode;
            led_s.m_led_3 = mode;
            led_s.m_led_4 = mode;
        break;
    }
    
    RTE_LED_set(&SO_LED_signal, led_s);
    RTE_LED_pushPort(&SO_LED_signal);
    
}



//Guards

static boolean_t CTRL__timerReachedZero()
{
    if (CTRL__timerValue < 0)
    {
        return TRUE;
    }
    else
    {
        return FALSE;
    }
}

static boolean_t CTRL__engineIsStopped()
{
    RC_t result = RC_SUCCESS;
    
    PEDAL_data_t pedal = RTE_PEDAL_get(&SO_PEDALPOSITION_signal);
    
    //No pullport here, this is done in the cyclic engine runnable
    SPEED_data_t currentSpeed = RTE_SPEED_get(&SO_CURRENTSPEED_signal);
    
    if (pedal.m_value < 10 && currentSpeed.m_rpm < 10)
    {
        return TRUE;
    }
    else
    {
        return FALSE;
    }

}
