/**************************************************
 ** Software Component SWC_Pedal
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#include "rte.h"
#include "rte_signalpool.h"

#include "logging.h"

#include "swc_pedal.h"

/* Runnables */
void PEDAL_readCheckAdc_run()
{
    
    RC_t result = RC_SUCCESS;
    
    //Get the pedal signal from the driver
    result = RTE_PEDAL_pullPort(&SO_PEDALPOSITION_signal);
   
}


#define PEDAL_CRITICALAGE 1000

void PEDAL_errorHandler_run()
{
    
    RC_t result = RC_SUCCESS;
    uint32_t pedalAge = RTE_PEDAL_getAge(&SO_PEDALPOSITION_signal);
    
    if (pedalAge > PEDAL_CRITICALAGE)
    {
        LOG_I("PEDAL_errorHandler_run","CRITICAL ERROR - wrong data from ADC ==============");
        
        //Fire event to central state machine
        EVENT_data_t ev = EVENT_INIT_DATA;
        ev.m_ev = EVENT_error;
        result = RTE_EVENT_set(&SO_EVENT_signal, ev);
    }
    else
    {
        LOG_I("PEDAL_errorHandler_run","ERROR - wrong data from ADC : %d",pedalAge);
    }
 
}
