/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ErikaOS_1_ee.h"
#include "ErikaOS_1_ee_tracing.h"
#include "Pin_ledRed_aliases.h"
#include "Pin_ledRed.h"
#include "Pin_ledYellow_aliases.h"
#include "Pin_ledYellow.h"
#include "RGB_PWM_red.h"
#include "RGB_PWM_yellow.h"
#include "RGB_PWM_blue.h"
#include "PWM_Clock.h"
#include "Pin_LedGreen_aliases.h"
#include "Pin_LedGreen.h"
#include "UART_LOG.h"
#include "Control_Reg_1.h"
#include "Pin_sev_segment_1A_aliases.h"
#include "Pin_sev_segment_1A.h"
#include "Pin_sev_segment_1B_aliases.h"
#include "Pin_sev_segment_1B.h"
#include "Pin_sev_segment_1C_aliases.h"
#include "Pin_sev_segment_1C.h"
#include "Pin_sev_segment_1D_aliases.h"
#include "Pin_sev_segment_1D.h"
#include "Pin_sev_segment_1E_aliases.h"
#include "Pin_sev_segment_1E.h"
#include "Pin_sev_segment_1F_aliases.h"
#include "Pin_sev_segment_1F.h"
#include "Pin_sev_segment_1G_aliases.h"
#include "Pin_sev_segment_1G.h"
#include "Pin_sev_segment_1DP_aliases.h"
#include "Pin_sev_segment_1DP.h"
#include "Button1_aliases.h"
#include "Button1.h"
#include "ISR_1.h"
#include "Button2_aliases.h"
#include "Button2.h"
#include "Button3_aliases.h"
#include "Button3.h"
#include "Button4_aliases.h"
#include "Button4.h"
#include "RGB_R_aliases.h"
#include "RGB_R.h"
#include "RGB_G_aliases.h"
#include "RGB_G.h"
#include "RGB_B_aliases.h"
#include "RGB_B.h"
#include "UART_LOG_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

