/**************************************************
 ** The RTE signals (autogenerated)
 **************************************************/

#include "project.h" 
#include "global.h" 
#include "rte_signalpool.h" 


/* Generated signal classes */
#include "signal_protocol_signal.h"
#include "signal_joystick_signal.h"
#include "signal_speed_signal.h"
#include "signal_ultrasonicsensor_signal.h"
#include "signal_engine_signal.h"
#include "signal_decoder_signal.h"
#include "signal_event_signal.h"
#include "signal_carstate_signal.h"
#include "signal_carparameters_signal.h"




/*****************************************************
 ** RTE Object so_protocolRx
 ** Protocol received over XBee
 *****************************************************/


/* signal configuration */

static const SIGNAL_PROTOCOL_cfg_t SO_PROTOCOLRX_cfg = 
{
   /* indriver      */  SIGNAL_PROTOCOL_driverIn,
   /* outdriver     */  0,
   /* onUpdate      */  0,
   /* onError       */  ev_protocolRx_onError
}; /* configuration so_protocolRx */


/* signal data */

SIGNAL_PROTOCOL_t SO_PROTOCOLRX_signal = 
{
   /* init value    */  SIGNAL_PROTOCOL_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_PROTOCOLRX_cfg
}; /* data so_protocolRx */


/*****************************************************
 ** RTE Object so_protocolTx
 ** Protocol send over XBee
 *****************************************************/


/* signal configuration */

static const SIGNAL_PROTOCOL_cfg_t SO_PROTOCOLTX_cfg = 
{
   /* indriver      */  0,
   /* outdriver     */  SIGNAL_PROTOCOL_driverOut,
   /* onUpdate      */  0,
   /* onError       */  0
}; /* configuration so_protocolTx */


/* signal data */

SIGNAL_PROTOCOL_t SO_PROTOCOLTX_signal = 
{
   /* init value    */  SIGNAL_PROTOCOL_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_PROTOCOLTX_cfg
}; /* data so_protocolTx */


/*****************************************************
 ** RTE Object so_joystick
 ** Joystick signal in X and Y coordinates
 *****************************************************/


/* signal configuration */

static const SIGNAL_JOYSTICK_cfg_t SO_JOYSTICK_cfg = 
{
   /* indriver      */  SIGNAL_JOYSTICK_driverIn,
   /* outdriver     */  0,
   /* onUpdate      */  ev_joystick_onUpdate,
   /* onError       */  0
}; /* configuration so_joystick */


/* signal data */

SIGNAL_JOYSTICK_t SO_JOYSTICK_signal = 
{
   /* init value    */  SIGNAL_JOYSTICK_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_JOYSTICK_cfg
}; /* data so_joystick */


/*****************************************************
 ** RTE Object so_carstate
 ** Car Connection State
 *****************************************************/


/* signal configuration */

static const SIGNAL_CARSTATE_cfg_t SO_CARSTATE_cfg = 
{
   /* indriver      */  0,
   /* outdriver     */  0,
   /* onUpdate      */  ev_carstate_onUpdate,
   /* onError       */  0
}; /* configuration so_carstate */


/* signal data */

SIGNAL_CARSTATE_t SO_CARSTATE_signal = 
{
   /* init value    */  SIGNAL_CARSTATE_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_CARSTATE_cfg
}; /* data so_carstate */


/*****************************************************
 ** RTE Object so_event_rx
 ** Event fired to the central state machine
 *****************************************************/


/* signal configuration */

static const SIGNAL_EVENT_cfg_t SO_EVENT_RX_cfg = 
{
   /* indriver      */  0,
   /* outdriver     */  0,
   /* onUpdate      */  ev_event_rx_onUpdate,
   /* onError       */  0
}; /* configuration so_event_rx */


/* signal data */

SIGNAL_EVENT_t SO_EVENT_RX_signal = 
{
   /* init value    */  SIGNAL_EVENT_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_EVENT_RX_cfg
}; /* data so_event_rx */


/*****************************************************
 ** RTE Object so_event_tx
 ** Event fired from the central state machine
 *****************************************************/


/* signal configuration */

static const SIGNAL_EVENT_cfg_t SO_EVENT_TX_cfg = 
{
   /* indriver      */  0,
   /* outdriver     */  0,
   /* onUpdate      */  ev_event_tx_onUpdate,
   /* onError       */  0
}; /* configuration so_event_tx */


/* signal data */

SIGNAL_EVENT_t SO_EVENT_TX_signal = 
{
   /* init value    */  SIGNAL_EVENT_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_EVENT_TX_cfg
}; /* data so_event_tx */


/*****************************************************
 ** RTE Object so_carparameter
 ** Car parameters like algo, maxspeed,...
 *****************************************************/


/* signal configuration */

static const SIGNAL_CARPARAMETERS_cfg_t SO_CARPARAMETER_cfg = 
{
   /* indriver      */  0,
   /* outdriver     */  0,
   /* onUpdate      */  0,
   /* onError       */  0
}; /* configuration so_carparameter */


/* signal data */

SIGNAL_CARPARAMETERS_t SO_CARPARAMETER_signal = 
{
   /* init value    */  SIGNAL_CARPARAMETERS_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_CARPARAMETER_cfg
}; /* data so_carparameter */


/*****************************************************
 ** RTE Object so_targetspeedRequested
 ** Requested targetspeed
 *****************************************************/


/* signal configuration */

static const SIGNAL_SPEED_cfg_t SO_TARGETSPEEDREQUESTED_cfg = 
{
   /* indriver      */  0,
   /* outdriver     */  0,
   /* onUpdate      */  ev_targetspeedRequested_onUpdate,
   /* onError       */  0
}; /* configuration so_targetspeedRequested */


/* signal data */

SIGNAL_SPEED_t SO_TARGETSPEEDREQUESTED_signal = 
{
   /* init value    */  SIGNAL_SPEED_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_TARGETSPEEDREQUESTED_cfg
}; /* data so_targetspeedRequested */


/*****************************************************
 ** RTE Object so_targetspeed
 ** Verified Targetspeed
 *****************************************************/


/* signal configuration */

static const SIGNAL_SPEED_cfg_t SO_TARGETSPEED_cfg = 
{
   /* indriver      */  0,
   /* outdriver     */  0,
   /* onUpdate      */  ev_targetspeed_onUpdate,
   /* onError       */  0
}; /* configuration so_targetspeed */


/* signal data */

SIGNAL_SPEED_t SO_TARGETSPEED_signal = 
{
   /* init value    */  SIGNAL_SPEED_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_TARGETSPEED_cfg
}; /* data so_targetspeed */


/*****************************************************
 ** RTE Object so_currentspeed
 ** Current speed as reported by the decoder
 *****************************************************/


/* signal configuration */

static const SIGNAL_SPEED_cfg_t SO_CURRENTSPEED_cfg = 
{
   /* indriver      */  SIGNAL_SPEED_driverIn,
   /* outdriver     */  0,
   /* onUpdate      */  0,
   /* onError       */  0
}; /* configuration so_currentspeed */


/* signal data */

SIGNAL_SPEED_t SO_CURRENTSPEED_signal = 
{
   /* init value    */  SIGNAL_SPEED_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_CURRENTSPEED_cfg
}; /* data so_currentspeed */


/*****************************************************
 ** RTE Object so_engine
 ** Control speed passed to the engine
 *****************************************************/


/* signal configuration */

static const SIGNAL_ENGINE_cfg_t SO_ENGINE_cfg = 
{
   /* indriver      */  0,
   /* outdriver     */  SIGNAL_ENGINE_driverOut,
   /* onUpdate      */  0,
   /* onError       */  0
}; /* configuration so_engine */


/* signal data */

SIGNAL_ENGINE_t SO_ENGINE_signal = 
{
   /* init value    */  SIGNAL_ENGINE_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_ENGINE_cfg
}; /* data so_engine */


/*****************************************************
 ** RTE Object so_USfront
 ** Ultrasonic sensor front
 *****************************************************/


/* signal configuration */

static const SIGNAL_ULTRASONICSENSOR_cfg_t SO_USFRONT_cfg = 
{
   /* indriver      */  SIGNAL_ULTRASONICSENSOR_driverIn,
   /* outdriver     */  0,
   /* onUpdate      */  0,
   /* onError       */  ev_ultrasonic_onError
}; /* configuration so_USfront */


/* signal data */

volatile SIGNAL_ULTRASONICSENSOR_t SO_USFRONT_signal = 
{
   /* init value    */  SIGNAL_ULTRASONICSENSOR_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_USFRONT_cfg
}; /* data so_USfront */


/*****************************************************
 ** RTE Object so_USrear
 ** Ultrasonic sensor rear
 *****************************************************/


/* signal configuration */

static const SIGNAL_ULTRASONICSENSOR_cfg_t SO_USREAR_cfg = 
{
   /* indriver      */  SIGNAL_ULTRASONICSENSOR_driverIn,
   /* outdriver     */  0,
   /* onUpdate      */  0,
   /* onError       */  ev_ultrasonic_onError
}; /* configuration so_USrear */


/* signal data */

volatile SIGNAL_ULTRASONICSENSOR_t SO_USREAR_signal = 
{
   /* init value    */  SIGNAL_ULTRASONICSENSOR_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_USREAR_cfg
}; /* data so_USrear */


/*******************************************************************************
 ** Central timertick function for ticktime 1 
 *******************************************************************************/ 

void RTE_timertick()
{
    RTE_SIGNAL_PROTOCOL_incAge( &SO_PROTOCOLRX_signal, 1);
    RTE_SIGNAL_PROTOCOL_incAge( &SO_PROTOCOLTX_signal, 1);
    RTE_SIGNAL_JOYSTICK_incAge( &SO_JOYSTICK_signal, 1);
    RTE_SIGNAL_CARSTATE_incAge( &SO_CARSTATE_signal, 1);
    RTE_SIGNAL_EVENT_incAge( &SO_EVENT_RX_signal, 1);
    RTE_SIGNAL_EVENT_incAge( &SO_EVENT_TX_signal, 1);
    RTE_SIGNAL_CARPARAMETERS_incAge( &SO_CARPARAMETER_signal, 1);
    RTE_SIGNAL_SPEED_incAge( &SO_TARGETSPEEDREQUESTED_signal, 1);
    RTE_SIGNAL_SPEED_incAge( &SO_TARGETSPEED_signal, 1);
    RTE_SIGNAL_SPEED_incAge( &SO_CURRENTSPEED_signal, 1);
    RTE_SIGNAL_ENGINE_incAge( &SO_ENGINE_signal, 1);
    RTE_SIGNAL_ULTRASONICSENSOR_incAge( &SO_USFRONT_signal, 1);
    RTE_SIGNAL_ULTRASONICSENSOR_incAge( &SO_USREAR_signal, 1);
}

