/**************************************************
 ** The signal blackboard (autogenerated)
 **************************************************/

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_activation.h" 


/* Software components */
#include "swc_engine.h"
#include "swc_ultrasonic.h"
#include "swc_control.h"
#include "swc_remote.h"


/* Cyclic Table */

const RTE_cyclicTable_t RTE_cyclicActivationTable[] = { 
   { ENGINE_getDecoder_run, 100 },
   { ENGINE_controlSpeed_run, 25 },
   { US_getDistance_run, 25 },
}; 

 const uint16_t RTE_cyclicActivation_size = sizeof (RTE_cyclicActivationTable) / sizeof(RTE_cyclicTable_t); 

/* Event Table */

const RTE_eventTable_t RTE_eventActivationTable[] = { 
   { CONTROL_calculateTargetspeed_run, ev_joystick_onUpdate },
   { CONTROL_limitSpeed_run, ev_targetspeedRequested_onUpdate },
   { CONTROL_limitSpeed_run, ev_carstate_onUpdate },
   { CONTROL_processCarstate_run, ev_event_rx_onUpdate },
   { REMOTE_readProtocol_run, ev_isr_protocolBufferComplete },
   { REMOTE_sendProtocol_run, ev_event_tx_onUpdate },
   { REMOTE_readProtocolError_run, ev_protocolRx_onError },
   { US_getDistanceError_run, ev_ultrasonic_onError },
}; 

 const uint16_t RTE_eventActivation_size = sizeof (RTE_eventActivationTable) / sizeof(RTE_eventTable_t); 

