/**************************************************
 ** The RTE signal blackboard (autogenerated)
 **************************************************/

#ifndef RTE_SIGNALPOOL_H
#define RTE_SIGNALPOOL_H


/* Generated signal classes */
#include "signal_protocol_signal.h"
#include "signal_joystick_signal.h"
#include "signal_speed_signal.h"
#include "signal_ultrasonicsensor_signal.h"
#include "signal_engine_signal.h"
#include "signal_decoder_signal.h"
#include "signal_event_signal.h"
#include "signal_carstate_signal.h"
#include "signal_carparameters_signal.h"


/* Generated objects */

/* Protocol received over XBee */
extern SIGNAL_PROTOCOL_t SO_PROTOCOLRX_signal;

/* Protocol send over XBee */
extern SIGNAL_PROTOCOL_t SO_PROTOCOLTX_signal;

/* Joystick signal in X and Y coordinates */
extern SIGNAL_JOYSTICK_t SO_JOYSTICK_signal;

/* Car Connection State */
extern SIGNAL_CARSTATE_t SO_CARSTATE_signal;

/* Event fired to the central state machine */
extern SIGNAL_EVENT_t SO_EVENT_RX_signal;

/* Event fired from the central state machine */
extern SIGNAL_EVENT_t SO_EVENT_TX_signal;

/* Car parameters like algo, maxspeed,... */
extern SIGNAL_CARPARAMETERS_t SO_CARPARAMETER_signal;

/* Requested targetspeed */
extern SIGNAL_SPEED_t SO_TARGETSPEEDREQUESTED_signal;

/* Verified Targetspeed */
extern SIGNAL_SPEED_t SO_TARGETSPEED_signal;

/* Current speed as reported by the decoder */
extern SIGNAL_SPEED_t SO_CURRENTSPEED_signal;

/* Control speed passed to the engine */
extern SIGNAL_ENGINE_t SO_ENGINE_signal;

/* Ultrasonic sensor front */
extern volatile SIGNAL_ULTRASONICSENSOR_t SO_USFRONT_signal;

/* Ultrasonic sensor rear */
extern volatile SIGNAL_ULTRASONICSENSOR_t SO_USREAR_signal;

/** Central Timertick function 
 *  must be called every 1ms 
 **/  
void RTE_timertick();


#endif
