/*
 * Signal_Joystick_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */



#ifndef SIGNAL_JOYSTICK_TYPE_H_
#define SIGNAL_JOYSTICK_TYPE_H_

#include "global.h"

/*****************************************************************************************
 *************** Type Definition for SIGNAL_JOYSTICK signal                     **************************
 *****************************************************************************************/



typedef struct
{
    sint8_t m_x;  /**< \brief -100...100*/
    sint8_t m_y;  /**< \brief -100...100*/
} SIGNAL_JOYSTICK_data_t;


#define SIGNAL_JOYSTICK_INIT_DATA ((SIGNAL_JOYSTICK_data_t){0, 0})


/**
 * Default IN driver API - may be deleted if not required
 * \param SIGNAL_JOYSTICK_data_t *const data : [OUT] scaled data read from the driver
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t SIGNAL_JOYSTICK_driverIn(SIGNAL_JOYSTICK_data_t *const data);


/**
 * Default IN driver API - may be deleted if not required
 * \param const SIGNAL_JOYSTICK_data_t  *const data : [IN] signal data for the driver, will be scaled in this function
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t SIGNAL_JOYSTICK_driverOut(const SIGNAL_JOYSTICK_data_t  *const data);



#endif /* SIGNAL_JOYSTICK_TYPE_H_ */

