/*
 * Signal_CarParameters_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */



#ifndef SIGNAL_CARPARAMETERS_TYPE_H_
#define SIGNAL_CARPARAMETERS_TYPE_H_

#include "global.h"

/*****************************************************************************************
 *************** Type Definition for SIGNAL_CARPARAMETERS signal                     **************************
 *****************************************************************************************/



typedef struct
{
    uint8_t m_algoIndex;
    uint8_t m_speedReduction;
    
} SIGNAL_CARPARAMETERS_data_t;

#define SIGNAL_CARPARAMETERS_INIT_DATA ((SIGNAL_CARPARAMETERS_data_t){0})


/**
 * Default IN driver API - may be deleted if not required
 * \param SIGNAL_CARPARAMETERS_data_t *const data : [OUT] scaled data read from the driver
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t SIGNAL_CARPARAMETERS_driverIn(SIGNAL_CARPARAMETERS_data_t *const data);


/**
 * Default IN driver API - may be deleted if not required
 * \param const SIGNAL_CARPARAMETERS_data_t  *const data : [IN] signal data for the driver, will be scaled in this function
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t SIGNAL_CARPARAMETERS_driverOut(const SIGNAL_CARPARAMETERS_data_t  *const data);



#endif /* SIGNAL_CARPARAMETERS_TYPE_H_ */

