/*
 * Signal_UltrasonicSensor_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */


#include "project.h"
#include "global.h"
#include "ultrasonic.h"

#include "logging.h"

#include "Signal_UltrasonicSensor_type.h"

/*****************************************************************************************
 *************** Port Wrapper Implementation for SIGNAL_ULTRASONICSENSOR signal                     **************************
 *****************************************************************************************/

#define TESTCASE 3


/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t SIGNAL_ULTRASONICSENSOR_driverIn(SIGNAL_ULTRASONICSENSOR_data_t *const data)
{

    //LOG_I("SIGNAL_ULTRASONICSENSOR_driverIn","id %d",data->m_id);
    
    data->m_status = US_ISMEASURING;
    
    //Testcase 1 - Just firing
    #if TESTCASE == 1
    US_Fire(data->m_id);
    data->m_status = US_ISINVALID;
    #endif
    
    //Testcase 2 - Polling
    #if TESTCASE == 2
    uint16_t distance = 0;
    US_GetDistance_poll(data->m_id,&distance);
    data->m_distance = distance;
    data->m_status = US_ISVALID;
    #endif
    
    //Testcase 3 - ISR
    #if TESTCASE == 3
    //LOG_I("US_driverIn:","Firing %d",data->m_id);
    US_Fire(data->m_id);
    #endif
    
    
	return RC_SUCCESS;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t SIGNAL_ULTRASONICSENSOR_driverOut(const SIGNAL_ULTRASONICSENSOR_data_t  *const data)
{


	//Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
}
