/*
 * Signal_CarState_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */


#include "project.h"
#include "global.h"

#include "Signal_CarState_type.h"

/*****************************************************************************************
 *************** Port Wrapper Implementation for SIGNAL_CARSTATE signal                     **************************
 *****************************************************************************************/


/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t SIGNAL_CARSTATE_driverIn(SIGNAL_CARSTATE_data_t *const data)
{


	//Read data from the MCAL driver

	//Scale it to the application type

	return RC_SUCCESS;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t SIGNAL_CARSTATE_driverOut(const SIGNAL_CARSTATE_data_t  *const data)
{


	//Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
}
