/*
 * Signal_CarParameters_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */


#include "project.h"
#include "global.h"

#include "Signal_CarParameters_type.h"

/*****************************************************************************************
 *************** Port Wrapper Implementation for SIGNAL_CARPARAMETERS signal                     **************************
 *****************************************************************************************/


/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t SIGNAL_CARPARAMETERS_driverIn(SIGNAL_CARPARAMETERS_data_t *const data)
{


	//Read data from the MCAL driver

	//Scale it to the application type

	return RC_SUCCESS;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t SIGNAL_CARPARAMETERS_driverOut(const SIGNAL_CARPARAMETERS_data_t  *const data)
{


	//Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
}
