/*
 * Signal_Engine_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */


#include "project.h"
#include "global.h"

#include "Signal_Engine_type.h"
#include "engine.h"
#include "engine_type.h"

#include "rte.h"
#include "rte_activation.h"
#include "swc_engine.h"

/*****************************************************************************************
 *************** Port Wrapper Implementation for SIGNAL_ENGINE signal   ******************
 *****************************************************************************************/


/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t SIGNAL_ENGINE_driverIn(SIGNAL_ENGINE_data_t *const data)
{
//#error "Add your code here"

	//Read data from the MCAL driver

	//Scale it to the application type

	return RC_SUCCESS;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t SIGNAL_ENGINE_driverOut(const SIGNAL_ENGINE_data_t  *const data)
{
    sint16_t targetspeed, controlspeed, measuredspeed = 0;
    RC_t result = RC_SUCCESS;
    uint16_t ticktime = RTE_getTickTime(RTE_cyclicActivationTable, RTE_cyclicActivation_size, ENGINE_controlSpeed_run);
    
    //Check for valid range and write to driver
    //Front Left
    targetspeed =data->m_rpm_fl;
    
    if (targetspeed < - ENG_MAXRPM) controlspeed = -ENG_MAXRPM;
    if (targetspeed >   ENG_MAXRPM) controlspeed = ENG_MAXRPM;
    
    result = ENG_SetEngineClosedLoopPID(ENG_FL , ticktime, targetspeed, &measuredspeed, &controlspeed);

    //Front Right
	targetspeed = data->m_rpm_fr;
    
    if (targetspeed < - ENG_MAXRPM) controlspeed = -ENG_MAXRPM;
    if (targetspeed >   ENG_MAXRPM) controlspeed = ENG_MAXRPM;
    
       result = ENG_SetEngineClosedLoopPID(ENG_FR , ticktime, targetspeed, &measuredspeed, &controlspeed);

    
    //Rear Left
	targetspeed = data->m_rpm_rl;
    
    if (targetspeed < - ENG_MAXRPM) controlspeed = -ENG_MAXRPM;
    if (targetspeed >   ENG_MAXRPM) controlspeed = ENG_MAXRPM;
    
    result = ENG_SetEngineClosedLoopPID(ENG_RL , ticktime, targetspeed, &measuredspeed, &controlspeed);
    
    
    //Rear Right
	targetspeed = data->m_rpm_rr;
    
    if (targetspeed < - ENG_MAXRPM) controlspeed = -ENG_MAXRPM;
    if (targetspeed >   ENG_MAXRPM) controlspeed = ENG_MAXRPM;
    
    result = ENG_SetEngineClosedLoopPID(ENG_RR , ticktime, targetspeed, &measuredspeed, &controlspeed);
    

	return RC_SUCCESS;
}
