/*
 * axi_reg.h
 *
 *  Created on: 16.07.2025
 *      Author: SESA807379 (Suhas Bangalore Mruthunjaya)
 */

#ifndef SRC_AXI_REG_H_
#define SRC_AXI_REG_H_

// Custom IP - CurrentSense AXI IP defines
#define AXI_PRACTISE_IP_BASE_ADDR XPAR_CURRENTSENSE_AXI_0_S00_AXI_BASEADDR
#define DAC_PHASE_AXIS_REG_OFFSET   	0x0
#define STATIC_DYNAMIC_REG_OFFSET		0x4
#define START_OP_REG_OFFSET				0x8
#define STATIC_DATA_REG_OFFSET			0xC
#define ERROR_REG_OFFSET				0x10
#define CURRENT_ADC_VALUE_REG_OFFSET 	0x14


// Custom IP - PWM Capture AXI IP defines
#define PWMCAPTURE_AXI_IP_BASE_ADDR	XPAR_PWMCAPTURE_AXI_0_S00_AXI_BASEADDR
#define PHASE_UH_FREQUENCY_DUTYCYCLE	0x0
#define PHASE_UL_FREQUENCY_DUTYCYCLE	0x4
#define PHASE_VH_FREQUENCY_DUTYCYCLE	0x8
#define PHASE_VL_FREQUENCY_DUTYCYCLE	0xC
#define PHASE_WH_FREQUENCY_DUTYCYCLE	0x10
#define PHASE_WL_FREQUENCY_DUTYCYCLE	0x14
#define PHASE_U_DEADTIME				0x18
#define PHASE_V_DEADTIME				0x1C
#define PHASE_W_DEADTIME				0x20

#endif /* SRC_AXI_REG_H_ */
