/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ErikaOS_1_ee.h"
#include "ErikaOS_1_ee_tracing.h"
#include "Joystick_ADC_Y_aliases.h"
#include "Joystick_ADC_Y.h"
#include "Joystick_ADC_X_aliases.h"
#include "Joystick_ADC_X.h"
#include "JOYSTICK_ADC_XY.h"
#include "UART_LOG.h"
#include "Pin_RGB_Blue_aliases.h"
#include "Pin_RGB_Blue.h"
#include "Pin_RGB_Red_aliases.h"
#include "Pin_RGB_Red.h"
#include "Pin_RGB_Green_aliases.h"
#include "Pin_RGB_Green.h"
#include "PWM_RGB_Red.h"
#include "PWM_RGB_Green.h"
#include "PWM_RGB_Blue.h"
#include "Clock_1.h"
#include "RED_LED_aliases.h"
#include "RED_LED.h"
#include "Button_1_aliases.h"
#include "Button_1.h"
#include "isr_button.h"
#include "Button_2_aliases.h"
#include "Button_2.h"
#include "Button_3_aliases.h"
#include "Button_3.h"
#include "Button_4_aliases.h"
#include "Button_4.h"
#include "RX_1_aliases.h"
#include "RX_1.h"
#include "TX_1_aliases.h"
#include "TX_1.h"
#include "CAN_1.h"
#include "JOYSTICK_ADC_XY_SAR.h"
#include "JOYSTICK_ADC_XY_IntClock.h"
#include "JOYSTICK_ADC_XY_TempBuf_dma.h"
#include "JOYSTICK_ADC_XY_FinalBuf_dma.h"
#include "JOYSTICK_ADC_XY_IRQ.h"
#include "UART_LOG_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

