/**************************************************
 ** Software Component SWC_Pedal
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#ifndef SWC_PEDAL_H
#define SWC_PEDAL_H


/* Runnables */
void PEDAL_init();
    
void PEDAL_readCheckAdc_run();

void PEDAL_errorHandler_run();

#endif /* include guard */

