
/*
 * Filename: sc_carspeed_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: The car speed in vy [m/s] and vphi [deg/s]
 */

#ifndef _H_DEFINE_SC_CARSPEED_TYPE
#define _H_DEFINE_SC_CARSPEED_TYPE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SC_CARSPEED_INCLUDES */

/* USER CODE END SC_CARSPEED_INCLUDES */



/**********************************************************************
 *       Type Definition for SC_CARSPEED signal    
 **********************************************************************/

/* USER CODE START SC_CARSPEED_USERDEFINITIONS */

/* USER CODE END SC_CARSPEED_USERDEFINITIONS */

typedef 
/* USER CODE START SC_CARSPEED_SIGNALDATADEFINITION */
struct
{
	float m_vy;     /**< \brief forward/reverse driving speed in m/s */
    float m_vphi;   /**< \brief rotational speed in deg/s */
} 
/* USER CODE END SC_CARSPEED_SIGNALDATADEFINITION */
SC_CARSPEED_data_t;

/* USER CODE START InitSC_CARSPEED */
#define SC_CARSPEED_INIT_DATA ((SC_CARSPEED_data_t){0,0})
/* USER CODE END InitSC_CARSPEED */





/* USER CODE START SC_CARSPEED_USERFUNCTIONS */

/* USER CODE END SC_CARSPEED_USERFUNCTIONS */


#endif