/*
 * Filename: sp_common.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: The common global signal pool, all signals will be stored here
 * endaddr: ADR_SP_COMMON_END
 * name: sp_common
 * shortname: common
 * startaddr: ADR_SP_COMMON_START
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sp_common.h"



/* USER CODE START SP_COMMON_INCLUDE */

/* USER CODE END SP_COMMON_INCLUDE */

#include "sc_joystick.h"
#include "sc_joystick_type.h"
#include "sc_carspeed.h"
#include "sc_carspeed_type.h"
#include "sc_enginespeed.h"
#include "sc_enginespeed_type.h"
#include "sc_enginespeed.h"
#include "sc_enginespeed_type.h"
#include "sc_protocol.h"
#include "sc_protocol_type.h"
#include "sc_protocol.h"
#include "sc_protocol_type.h"
#include "sc_carstate.h"
#include "sc_carstate_type.h"
#include "sc_event_in.h"
#include "sc_event_in_type.h"
#include "sc_event_out.h"
#include "sc_event_out_type.h"
#include "sc_carerrorstate.h"
#include "sc_carerrorstate_type.h"
#include "sc_ultrasonicarray.h"
#include "sc_ultrasonicarray_type.h"
#include "sc_diagnosticrequest.h"
#include "sc_diagnosticrequest_type.h"



/* signal configuration */
/*
 * description: Joystick x,y for controlling the car manually
 * indriver: 0
 * name: so_joystick
 * onDataError: 0
 * onDataUpdate: ev_joystick_onData
 * outdriver: 0
 * resource: None
 * shortname: joystick
 * signalclass: sc_joystick
 * signalpool: sp_common
 */


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_joystick_updTasks = { tsk_control };
 

static const SC_JOYSTICK_cfg_t SO_JOYSTICK_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  0,

   /* onUpdate           */  ev_joystick_onData,
   /* onError            */  0,
   /* taskCount onUpdate */  1,
   /* task list onUpdate */  &so_joystick_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_joystick */


/* signal data */

SC_JOYSTICK_t SO_JOYSTICK_signal= 
{
   /* init value    */  SC_JOYSTICK_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_JOYSTICK_cfg,
}; /* data so_joystick */

/* signal configuration */
/*
 * description: Targetspeed defined by the user or ADAS algorithm
 * indriver: 0
 * name: so_targetspeed
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: 0
 * resource: None
 * shortname: targetspeed
 * signalclass: sc_carSpeed
 * signalpool: sp_common
 */

 

static const SC_CARSPEED_cfg_t SO_TARGETSPEED_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  0,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_targetspeed */


/* signal data */

SC_CARSPEED_t SO_TARGETSPEED_signal= 
{
   /* init value    */  SC_CARSPEED_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_TARGETSPEED_cfg,
}; /* data so_targetspeed */

/* signal configuration */
/*
 * description: The currentspeed reported by the engine decoder
 * indriver: default
 * name: so_currentspeed
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: 0
 * resource: None
 * shortname: currentspeed
 * signalclass: sc_engineSpeed
 * signalpool: sp_common
 */

 

static const SC_ENGINESPEED_cfg_t SO_CURRENTSPEED_cfg = 
{
   /* indriver           */  SC_ENGINESPEED_driverIn,
   /* outdriver          */  0,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_currentspeed */


/* signal data */

SC_ENGINESPEED_t SO_CURRENTSPEED_signal= 
{
   /* init value    */  SC_ENGINESPEED_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_CURRENTSPEED_cfg,
}; /* data so_currentspeed */

/* signal configuration */
/*
 * description: Controlspeed being send to the engine
 * indriver: 0
 * name: so_controlspeed
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: default
 * resource: None
 * shortname: controlspeed
 * signalclass: sc_engineSpeed
 * signalpool: sp_common
 */

 

static const SC_ENGINESPEED_cfg_t SO_CONTROLSPEED_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  SC_ENGINESPEED_driverOut,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_controlspeed */


/* signal data */

SC_ENGINESPEED_t SO_CONTROLSPEED_signal= 
{
   /* init value    */  SC_ENGINESPEED_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_CONTROLSPEED_cfg,
}; /* data so_controlspeed */

/* signal configuration */
/*
 * description: Incoming protocol - note, that the data will be set asynchronously.
 * indriver: default
 * name: so_protocolRx
 * onDataError: ev_protocolrx_onError
 * onDataUpdate: 0
 * outdriver: 0
 * resource: None
 * shortname: protocolRx
 * signalclass: sc_protocol
 * signalpool: sp_common
 */

 
/* The following array contains the receiving tasks for onError signal events */
const TaskTypeArray so_protocolRx_errTasks = { tsk_io };


static const SC_PROTOCOL_cfg_t SO_PROTOCOLRX_cfg = 
{
   /* indriver           */  SC_PROTOCOL_driverIn,
   /* outdriver          */  0,

   /* onUpdate           */  0,
   /* onError            */  ev_protocolrx_onError,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  1,
   /* task list onError  */  &so_protocolRx_errTasks,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_protocolrx */


/* signal data */

SC_PROTOCOL_t SO_PROTOCOLRX_signal= 
{
   /* init value    */  SC_PROTOCOL_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_PROTOCOLRX_cfg,
}; /* data so_protocolrx */

/* signal configuration */
/*
 * description: Outgoing Protocol
 * indriver: 0
 * name: so_protocolTx
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: default
 * resource: None
 * shortname: protocolTx
 * signalclass: sc_protocol
 * signalpool: sp_common
 */

 

static const SC_PROTOCOL_cfg_t SO_PROTOCOLTX_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  SC_PROTOCOL_driverOut,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_protocoltx */


/* signal data */

SC_PROTOCOL_t SO_PROTOCOLTX_signal= 
{
   /* init value    */  SC_PROTOCOL_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_PROTOCOLTX_cfg,
}; /* data so_protocoltx */

/* signal configuration */
/*
 * description: Signal containing car state and other central data
 * indriver: 0
 * name: so_carState
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: 0
 * resource: None
 * shortname: carState
 * signalclass: sc_carstate
 * signalpool: sp_common
 */

 

static const SC_CARSTATE_cfg_t SO_CARSTATE_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  0,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_carstate */


/* signal data */

SC_CARSTATE_t SO_CARSTATE_signal= 
{
   /* init value    */  SC_CARSTATE_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_CARSTATE_cfg,
}; /* data so_carstate */

/* signal configuration */
/*
 * description: Incoming Event
 * indriver: 0
 * name: so_eventIn
 * onDataError: 0
 * onDataUpdate: ev_eventin_onData
 * outdriver: 0
 * resource: None
 * shortname: eventIn
 * signalclass: sc_event_in
 * signalpool: sp_common
 */


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_eventIn_updTasks = { tsk_control };
 

static const SC_EVENT_IN_cfg_t SO_EVENTIN_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  0,

   /* onUpdate           */  ev_eventin_onData,
   /* onError            */  0,
   /* taskCount onUpdate */  1,
   /* task list onUpdate */  &so_eventIn_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_eventin */


/* signal data */

SC_EVENT_IN_t SO_EVENTIN_signal= 
{
   /* init value    */  SC_EVENT_IN_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_EVENTIN_cfg,
}; /* data so_eventin */

/* signal configuration */
/*
 * description: Outgoing Event
 * indriver: 0
 * name: so_eventOut
 * onDataError: 0
 * onDataUpdate: ev_eventout_onData
 * outdriver: 0
 * resource: None
 * shortname: eventOut
 * signalclass: sc_event_out
 * signalpool: sp_common
 */


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_eventOut_updTasks = { tsk_io };
 

static const SC_EVENT_OUT_cfg_t SO_EVENTOUT_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  0,

   /* onUpdate           */  ev_eventout_onData,
   /* onError            */  0,
   /* taskCount onUpdate */  1,
   /* task list onUpdate */  &so_eventOut_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_eventout */


/* signal data */

SC_EVENT_OUT_t SO_EVENTOUT_signal= 
{
   /* init value    */  SC_EVENT_OUT_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_EVENTOUT_cfg,
}; /* data so_eventout */

/* signal configuration */
/*
 * description: Signal containing the car error state
 * indriver: 0
 * name: so_carErrorState
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: default
 * resource: None
 * shortname: carErrorState
 * signalclass: sc_carErrorState
 * signalpool: sp_common
 */

 

static const SC_CARERRORSTATE_cfg_t SO_CARERRORSTATE_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  SC_CARERRORSTATE_driverOut,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_carerrorstate */


/* signal data */

SC_CARERRORSTATE_t SO_CARERRORSTATE_signal= 
{
   /* init value    */  SC_CARERRORSTATE_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_CARERRORSTATE_cfg,
}; /* data so_carerrorstate */

/* signal configuration */
/*
 * description: Ultrasonic array
 * indriver: default
 * name: so_ultrasonic
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: 0
 * resource: None
 * shortname: ultrasonic
 * signalclass: sc_ultrasonicArray
 * signalpool: sp_common
 */

 

static const SC_ULTRASONICARRAY_cfg_t SO_ULTRASONIC_cfg = 
{
   /* indriver           */  SC_ULTRASONICARRAY_driverIn,
   /* outdriver          */  0,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_ultrasonic */


/* signal data */

SC_ULTRASONICARRAY_t SO_ULTRASONIC_signal= 
{
   /* init value    */  SC_ULTRASONICARRAY_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_ULTRASONIC_cfg,
}; /* data so_ultrasonic */

/* signal configuration */
/*
 * description: Disgnostic Service Request
 * indriver: 0
 * name: so_diagnosticRequest
 * onDataError: 0
 * onDataUpdate: ev_diagnosticrequest_onData
 * outdriver: 0
 * resource: None
 * shortname: diagnosticRequest
 * signalclass: sc_diagnosticRequest
 * signalpool: sp_common
 */


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_diagnosticRequest_updTasks = { tsk_io };
 

static const SC_DIAGNOSTICREQUEST_cfg_t SO_DIAGNOSTICREQUEST_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  0,

   /* onUpdate           */  ev_diagnosticrequest_onData,
   /* onError            */  0,
   /* taskCount onUpdate */  1,
   /* task list onUpdate */  &so_diagnosticRequest_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_diagnosticrequest */


/* signal data */

SC_DIAGNOSTICREQUEST_t SO_DIAGNOSTICREQUEST_signal= 
{
   /* init value    */  SC_DIAGNOSTICREQUEST_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_DIAGNOSTICREQUEST_cfg,
}; /* data so_diagnosticrequest */



void RTE_timertick_sp_common_tick(uint32_t tick){
   RTE_SC_JOYSTICK_incAge( &SO_JOYSTICK_signal, tick); 
   RTE_SC_CARSPEED_incAge( &SO_TARGETSPEED_signal, tick); 
   RTE_SC_ENGINESPEED_incAge( &SO_CURRENTSPEED_signal, tick); 
   RTE_SC_ENGINESPEED_incAge( &SO_CONTROLSPEED_signal, tick); 
   RTE_SC_PROTOCOL_incAge( &SO_PROTOCOLRX_signal, tick); 
   RTE_SC_PROTOCOL_incAge( &SO_PROTOCOLTX_signal, tick); 
   RTE_SC_CARSTATE_incAge( &SO_CARSTATE_signal, tick); 
   RTE_SC_EVENT_IN_incAge( &SO_EVENTIN_signal, tick); 
   RTE_SC_EVENT_OUT_incAge( &SO_EVENTOUT_signal, tick); 
   RTE_SC_CARERRORSTATE_incAge( &SO_CARERRORSTATE_signal, tick); 
   RTE_SC_ULTRASONICARRAY_incAge( &SO_ULTRASONIC_signal, tick); 
   RTE_SC_DIAGNOSTICREQUEST_incAge( &SO_DIAGNOSTICREQUEST_signal, tick); 
   
}


