
/*
 * Filename: swc_control.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: SWC containing ADAS and manual driving functions
 */

#ifndef _H_DEFINE_SWC_CONTROL
#define _H_DEFINE_SWC_CONTROL

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_CONTROL_INCLUDES */

#include "statemachine.h"
    
/* USER CODE END SWC_CONTROL_INCLUDES */



/* USER CODE START SWC_CONTROL_USERDEFINITIONS */

typedef enum  {
    CONNECTIONSTATE_IS_IDLE,
	CONNECTIONSTATE_IS_CONNECTED,
	CONNECTIONSTATE_IS_DRIVING
} CONNECTION_state_t;
    
/** 
 * The Connection State Machine Object
 */;
extern STATE_t CONTROL_ConnectionFSM;
    
    
/* USER CODE END SWC_CONTROL_USERDEFINITIONS */


/*
 * component: swc_control
 * cycletime: 0
 * description: Central runnable calling the set driving function based on the carstate signal
 * events: ev_joystick_onData
 * name: CONTROL_control_run
 * shortname: control
 * signalIN: so_joystick
 * signalOUT: so_targetspeed
 * task: tsk_control
 */
void CONTROL_control_run(RTE_event ev);

/*
 * component: swc_control
 * cycletime: 0
 * description: Runnable receiving and processing central events, e.g. related to the connection state of the remote.
 * events: ev_eventin_onData
 * name: CONTROL_processCarstate_run
 * shortname: processCarstate
 * signalIN: so_carState|so_eventIn|so_eventOut
 * signalOUT: so_carState|so_eventOut
 * task: tsk_control
 */
void CONTROL_processCarstate_run(RTE_event ev);


#endif