/*
 * Filename: sc_decoderdelta_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Contains the decoder delta values
 * name: sc_decoderDelta
 * shortname: decoderDelta
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_decoderdelta_type.h"



/* USER CODE START SC_DECODERDELTA_INCLUDE */
#include "engine.h"
#include "engine_cfg.h"
/* USER CODE END SC_DECODERDELTA_INCLUDE */




/* USER CODE START SC_DECODERDELTA_USERDEFINITIONS */

/* USER CODE END SC_DECODERDELTA_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_DECODERDELTA signal  ****************
 *****************************************************************************************/
 
 

/**
 * Default IN driver API
 */
inline RC_t SC_DECODERDELTA_driverIn(SC_DECODERDELTA_data_t *const data)
{
	/* USER CODE START driverInSC_DECODERDELTA */

    
    //Read decoder delta from engine objects. Are updated by the engine speed signal, as this data is primarily used for the engine control
    //Therefore this function must be called after the engine pullport command, which is physically reading the decoders.

	//Read data from the MCAL driver - in this case the engine object
    
    ENG_getDecoder(&ENG_FL, &(data->m_fl));
    ENG_getDecoder(&ENG_FR, &(data->m_fr));
    ENG_getDecoder(&ENG_RL, &(data->m_rl));
    ENG_getDecoder(&ENG_RR, &(data->m_rr));

	//Scale it to the application type

	return RC_SUCCESS;
	/* USER CODE END driverInSC_DECODERDELTA */
}



