
/*
 * Filename: sc_joystick_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: joystick payload from XBee protocol
 */

#ifndef _H_DEFINE_SC_JOYSTICK_TYPE
#define _H_DEFINE_SC_JOYSTICK_TYPE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SC_JOYSTICK_INCLUDES */

/* USER CODE END SC_JOYSTICK_INCLUDES */



/**********************************************************************
 *       Type Definition for SC_JOYSTICK signal    
 **********************************************************************/

/* USER CODE START SC_JOYSTICK_USERDEFINITIONS */

/* USER CODE END SC_JOYSTICK_USERDEFINITIONS */

typedef 
/* USER CODE START SC_JOYSTICK_SIGNALDATADEFINITION */
struct
{
	sint8_t m_x;                /**< \brief -100...100 */
    sint8_t m_y;                /**< \brief -100...100 */
    sint8_t m_z;                /**< \brief -100...100 */
    uint8_t m_emergencyStop;    /**< \brief tbd */
    uint8_t m_normalStop;    /**< \brief tbd */
} 
/* USER CODE END SC_JOYSTICK_SIGNALDATADEFINITION */
SC_JOYSTICK_data_t;

/* USER CODE START InitSC_JOYSTICK */

#define SC_JOYSTICK_INIT_DATA ((SC_JOYSTICK_data_t){0,0,0,0,0})
/* USER CODE END InitSC_JOYSTICK */





/* USER CODE START SC_JOYSTICK_USERFUNCTIONS */

/* USER CODE END SC_JOYSTICK_USERFUNCTIONS */


#endif