
/*
 * Filename: sc_position_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Car position based on dead reckoning algorithm
 */

#ifndef _H_DEFINE_SC_POSITION_TYPE
#define _H_DEFINE_SC_POSITION_TYPE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SC_POSITION_INCLUDES */

/* USER CODE END SC_POSITION_INCLUDES */



/**********************************************************************
 *       Type Definition for SC_POSITION signal    
 **********************************************************************/

/* USER CODE START SC_POSITION_USERDEFINITIONS */

/* USER CODE END SC_POSITION_USERDEFINITIONS */

typedef 
/* USER CODE START SC_POSITION_SIGNALDATADEFINITION */
struct
{
	float32_t    m_x;    /*!< brief x Position in [cm] */
    float32_t    m_y;    /*!< brief y Position in [cm] */
    float32_t    m_phi;  /*!< brief Orientation in [degree] */
} 
/* USER CODE END SC_POSITION_SIGNALDATADEFINITION */
SC_POSITION_data_t;

/* USER CODE START InitSC_POSITION */
#define SC_POSITION_INIT_DATA ((SC_POSITION_data_t){0,0,0})
/* USER CODE END InitSC_POSITION */





/* USER CODE START SC_POSITION_USERFUNCTIONS */

/* USER CODE END SC_POSITION_USERFUNCTIONS */


#endif