##############################################################################
# rte_signalclass.py
#
# Description:   Create RTE signal classes
# Author:        Peter Fromm
#
# Input:         XML stream
# Output:        Software Components (header and source files)

import os
from fileinput import filename

################################
## create_one_swc_source
def create_one_swc_source(root, config, swcname):
    #Create and open file    
    out_file = config["path_out"] + "\\" + swcname.lower() + ".c"
    fout = open(out_file,'w')
    
    rline = "/**************************************************\n"
    fout.write(rline)
    
    rline = " ** Software Component "+swcname + "\n"
    fout.write(rline)
  
    rline = " ** autogenerated by H-DA RTE Generator\n"
    fout.write(rline)
    
    rline = " **************************************************/\n\n"
    fout.write(rline)
    
    rline = "#include \"rte.h\"\n"
    fout.write(rline)

    rline = "#include \"rte_signalpool.h\"\n"
    fout.write(rline)

    rline = "\n#include \"" + swcname.lower() + ".h\"\n"
    fout.write(rline)
    
    
    rline = "\n/* Runnables */\n"
    fout.write(rline)

    for runnable in root.iter("runnable"):
        if runnable.get("component") == swcname:
            rline = "void " + runnable.get("name") + "()\n"
            fout.write(rline)
            rline="{\n\n";
            fout.write(rline)
            rline="   /* Enter your code here */\n";
            fout.write(rline)
            rline="}\n";
            fout.write(rline)

    fout.close()    

  
## create_one_swc_header
################################

################################
## create_one_swc_source
def create_one_swc_header(root, config, swcname):

    #Create and open file    
    out_file = config["path_out"] + "\\" + swcname.lower() + ".h"
    fout = open(out_file,'w')
    
    rline = "/**************************************************\n"
    fout.write(rline)
    
    rline = " ** Software Component "+swcname + "\n"
    fout.write(rline)
  
    rline = " ** autogenerated by H-DA RTE Generator\n"
    fout.write(rline)
    
    rline = " **************************************************/\n\n"
    fout.write(rline)
    
    filename = swcname.upper()
    rline = "#ifndef " + filename + "_H\n"
    fout.write(rline)
    
    rline = "#define " + filename + "_H\n\n"
    fout.write(rline)
    
    rline = "\n/* Runnables */\n"
    fout.write(rline)

    for runnable in root.iter("runnable"):
        if runnable.get("component") == swcname:
            rline = "void " + runnable.get("name") + "();\n\n"
            fout.write(rline)

    fout.write("#endif /* include guard */\n\n")  

    fout.close()
  
## create_one_swc_header
################################

################################
## create_one_signal_class
def create(root, config):
    
    #Challenge: We have several entries for the components (historical legacy)
    swc_list = list()
    
    for runnable in root.iter('runnable'):
        swc_name = runnable.get("component")

        if swc_list.count(swc_name) == 0:
            #SWC not considered yet
            print("   Creating SWC: ", swc_name)
            
            create_one_swc_source(root, config, swc_name)
            create_one_swc_header(root, config, swc_name)
            
            #Consider every name only ones
            swc_list.append(swc_name)
  
## create_one_signal_class
################################
################################    