/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "WaveDAC8_1.h"
#include "UART_LOG.h"
#include "Push_button_aliases.h"
#include "Push_button.h"
#include "ADC_VtgDiv.h"
#include "DAC_aliases.h"
#include "DAC.h"
#include "Vlt_div_aliases.h"
#include "Vlt_div.h"
#include "LED_Red_aliases.h"
#include "LED_Red.h"
#include "LED_Yellow_aliases.h"
#include "LED_Yellow.h"
#include "LED_Green_aliases.h"
#include "LED_Green.h"
#include "WaveDAC8_1_DacClk.h"
#include "WaveDAC8_1_Wave1_DMA_dma.h"
#include "WaveDAC8_1_Wave2_DMA_dma.h"
#include "WaveDAC8_1_VDAC8.h"
#include "UART_LOG_IntClock.h"
#include "ADC_VtgDiv_AMux.h"
#include "ADC_VtgDiv_Ext_CP_Clk.h"
#include "ADC_VtgDiv_IRQ.h"
#include "ADC_VtgDiv_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

