/*
 * button_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */


#include "project.h"
#include "global.h"

#include "logging.h"
#include "rte_signalpool.h"

#include "button_type.h"

/*****************************************************************************************
 *************** Port Wrapper Implementation for BUTTON signal                     **************************
 *****************************************************************************************/

void updateButtonState(boolean_t prevPressed, boolean_t pressed, BUTTON_data_t* const data)
{
         if (prevPressed == FALSE && pressed == FALSE) data->m_button = BUTTON_LOW;
    else if (prevPressed == FALSE && pressed == TRUE) data->m_button = BUTTON_PRESSED;
    else if (prevPressed == TRUE && pressed == FALSE) data->m_button = BUTTON_DEPRESSED;
    else if (prevPressed == TRUE && pressed == TRUE) data->m_button = BUTTON_HIGH;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t BUTTON_1_driverIn(BUTTON_data_t *const data)
{
    
    static boolean_t prevPressed = FALSE;
    
	//Read data from the MCAL driver
    boolean_t pressed = BUTTON_IsPressed(BUTTON_1);


	//Scale it to the application type
    updateButtonState(prevPressed, pressed, data);
    
    //Save previous state
    prevPressed = pressed;
    
	return RC_SUCCESS;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t BUTTON_2_driverIn(BUTTON_data_t *const data)
{
    static boolean_t prevPressed = FALSE;
    
	//Read data from the MCAL driver
    boolean_t pressed = BUTTON_IsPressed(BUTTON_2);

	//Scale it to the application type
    updateButtonState(prevPressed, pressed, data);
    
    //Save previous state
    prevPressed = pressed;
    
	return RC_SUCCESS;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t BUTTON_3_driverIn(BUTTON_data_t *const data)
{
    static boolean_t prevPressed = FALSE;
    
	//Read data from the MCAL driver
    boolean_t pressed = BUTTON_IsPressed(BUTTON_3);

	//Scale it to the application type
    updateButtonState(prevPressed, pressed, data);
    
    //Save previous state
    prevPressed = pressed;
    
	return RC_SUCCESS;
}




/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t BUTTON_driverOut(const BUTTON_data_t  *const data)
{


	//Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
}
