/*
 * carState_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */



#ifndef CARSTATE_TYPE_H_
#define CARSTATE_TYPE_H_

#include "global.h"

/*****************************************************************************************
 *************** Type Definition for CARSTATE signal                     **************************
 *****************************************************************************************/

typedef enum { 
    ISIDLE, 
    
    ISPRESSEDIGNITION, 
    ISIGNITIONSELFTEST_1,
    ISIGNITIONSELFTEST_2,
    
    ISDRIVING,
    ISBRAKING,
    
    ISERROR}
CAR_state_t;

typedef enum {
    DIRECTION_NEUTRAL,
    DIRECTION_FORWARD,
    DIRECTION_REVERSE
} CAR_direction_t;


typedef struct
{
    CAR_state_t m_state;
    sint16_t m_maxSpeed;
    CAR_direction_t m_direction;
} CARSTATE_data_t;


#define CARSTATE_INIT_DATA ((CARSTATE_data_t){ISIDLE,0, DIRECTION_NEUTRAL})


/**
 * Default IN driver API - may be deleted if not required
 * \param CARSTATE_data_t *const data : [OUT] scaled data read from the driver
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t CARSTATE_driverIn(CARSTATE_data_t *const data);


/**
 * Default IN driver API - may be deleted if not required
 * \param const CARSTATE_data_t  *const data : [IN] signal data for the driver, will be scaled in this function
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t CARSTATE_driverOut(const CARSTATE_data_t  *const data);



#endif /* CARSTATE_TYPE_H_ */

