/*
 * pwm_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */


#include "project.h"
#include "global.h"

#include "engine.h"

#include "pwm_type.h"

/*****************************************************************************************
 *************** Port Wrapper Implementation for PWM signal                     **************************
 *****************************************************************************************/


/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t PWM_driverIn(PWM_data_t *const data)
{


	//Read data from the MCAL driver
    

	//Scale it to the application type

	return RC_SUCCESS;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t PWM_driverOut(const PWM_data_t  *const data)
{
	//Scale application data to drive format
	//Write scaled data to driver
    ENG_SetPWM(ENG_1, data->m_dutycycle);    

	return RC_SUCCESS;
}
