/**************************************************
 ** The RTE signal blackboard (autogenerated)
 **************************************************/

#ifndef RTE_SIGNALPOOL_H
#define RTE_SIGNALPOOL_H


/* Generated signal classes */
#include "pedal_signal.h"
#include "speed_signal.h"
#include "button_signal.h"
#include "carstate_signal.h"
#include "pwm_signal.h"
#include "event_signal.h"
#include "led_signal.h"


/* Generated objects */

/* Input signal for pedal position (ADC), range -100..100 */
extern PEDAL_t SO_PEDALPOSITION_signal;

/* Brake Button State */
extern BUTTON_t SO_BRAKEBUTTON_signal;

/* Ignition Button State */
extern BUTTON_t SO_IGNITIONBUTTON_signal;

/* Direction Button State */
extern BUTTON_t SO_DIRECTIONBUTTON_signal;

/* Target Speed Signal for engine (SPEED), range 0..MAXRPM */
extern SPEED_t SO_TARGETSPEED_signal;

/* Current Speed Signal for engine (SPEED), range 0..MAXRPM */
extern SPEED_t SO_CURRENTSPEED_signal;

/* Output Signal for engine, range 0..MAXPWM */
extern PWM_t SO_CONTROLSPEED_signal;

/* Central state object for properties like ignition state, maxspeed,... */
extern CARSTATE_t SO_CARSTATE_signal;

/* Events fired to the central state machine */
extern EVENT_t SO_EVENT_signal;

/* Led Signal */
extern LED_t SO_LED_signal;

/** Central Timertick function 
 *  must be called every 10ms 
 **/  
void RTE_timertick();


#endif
