/**************************************************
 ** Software Component SWC_COM
 ** autogenerated by H-DA RTE Generator
 **************************************************/
#include "math.h"

#include "rte.h"
#include "rte_signalpool.h"

#include "ringbuffer.h"
#include "uartprot_type.h"

#include "logging.h"

#include "error.h"

#include "swc_com.h"

/* Runnables */

void COM_init_run()
{
    RC_t result = RC_SUCCESS;
    
    UART_PSOC_Start(); 
    
    //Create RINGBUFFER object
    result = Ringbuffer_Init(&REMOTE_rx_buffer, RINGBUFFER_NO_ERIKA_RES, &REMOTE_uartBuffer, PROT_SIZERXBUF);
}

#define SPEED_MAXDELTA 20
#define CURSPEED_MAXDELTA 1000

//TEstcase : set errorcount to 5 or lower
#define ERRORCOUNTER_MAX 10

void COM_receive_run()
{

    static uint16_t errorCounter = 0;
    
    //Read data out of buffer
    RTE_UARTPROT_pullPort(&SO_UARTPROT_RX_signal);
    UARTPROT_data_t prot = RTE_UARTPROT_get(&SO_UARTPROT_RX_signal);
    
    //LOG_I("COM_receive_run","S: %d TS: %d",prot.m_state, prot.m_targetspeed);
    
    //Get comparison data
    CARSTATE_data_t state = RTE_CARSTATE_get(&SO_CARSTATE_signal);
    SPEED_data_t targetspeed = RTE_SPEED_get(&SO_TARGETSPEED_signal);
    SPEED_data_t currentspeed = RTE_SPEED_get(&SO_CURRENTSPEED_signal);
    

    sint16_t speedDelta = abs(prot.m_targetspeed - targetspeed.m_rpm);
    sint16_t currentDelta = abs(prot.m_currentspeed - currentspeed.m_rpm);
    
    if (prot.m_state != state.m_state || 
        speedDelta > SPEED_MAXDELTA
         )
    {
        errorCounter++;
        LOG_E("COM_receive_run","Error detected: %d count - State (%d|%d) Speed (%d|%d) Current (%d|%d)", errorCounter, prot.m_state, state.m_state, prot.m_targetspeed, targetspeed.m_rpm, prot.m_currentspeed, currentspeed.m_rpm);
    }
    else if (currentDelta > CURSPEED_MAXDELTA)
    {
       //This is a very dangerous error, engine might get out of control!
        errorCounter = ERRORCOUNTER_MAX;
        LOG_E("COM_receive_run","Error detected: %d count - State (%d|%d) Speed (%d|%d) Current (%d|%d)", errorCounter, prot.m_state, state.m_state, prot.m_targetspeed, targetspeed.m_rpm, prot.m_currentspeed, currentspeed.m_rpm);

    }
    else
    {
        errorCounter = 0;
        //LOG_I("COM_receive_run","All ok: %d count - State (%d|%d) Speed (%d|%d)", errorCounter, prot.m_state, state.m_state, prot.m_targetspeed, targetspeed.m_rpm);

    }
        
    if (errorCounter >= ERRORCOUNTER_MAX)
    {
        ERROR_centralHandler(ERROR_LOGIC);
    }
      
}
