/**************************************************
 ** Software Component SWC_COM
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#ifndef SWC_COM_H
#define SWC_COM_H


/* Runnables */
void COM_init_run();
    
void COM_receive_run();

#endif /* include guard */

