/*
 * dip_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */



#ifndef DIP_TYPE_H_
#define DIP_TYPE_H_

#include "global.h"

/*****************************************************************************************
 *************** Type Definition for DIP signal                     **************************
 *****************************************************************************************/



typedef union
{
    uint8_t byte;
    struct
    {
        uint8_t d0 : 1;
        uint8_t d1 : 1;
        uint8_t d2 : 1;
        uint8_t d3 : 1;
        uint8_t d4 : 1;
    } bit;
} DIP_data_t;

#define DIP_INIT_DATA ((DIP_data_t){0})


/**
 * Default IN driver API - may be deleted if not required
 * \param DIP_data_t *const data : [OUT] scaled data read from the driver
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t DIP_driverIn(DIP_data_t *const data);


/**
 * Default IN driver API - may be deleted if not required
 * \param const DIP_data_t  *const data : [IN] signal data for the driver, will be scaled in this function
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t DIP_driverOut(const DIP_data_t  *const data);



#endif /* DIP_TYPE_H_ */

