/*
 * dip_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */


#include "project.h"
#include "global.h"
#include "config.h"

#include "dip_type.h"

/*****************************************************************************************
 *************** Port Wrapper Implementation for DIP signal                     **************************
 *****************************************************************************************/


/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t DIP_driverIn(DIP_data_t *const data)
{

	//Read data from the MCAL driver
#if ERROR == ERROR_NIBBLE_LOW
    data->byte = EB_Status_Reg_1_Read();
#endif

#if ERROR == ERROR_NIBBLE_HIGH
    data->byte = EB_Status_Reg_2_Read();
#endif

	return RC_SUCCESS;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t DIP_driverOut(const DIP_data_t  *const data)
{

	//Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
}
