/*
 * event_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */


#include "project.h"
#include "global.h"

#include "event_type.h"

/*****************************************************************************************
 *************** Port Wrapper Implementation for EVENT signal                     **************************
 *****************************************************************************************/


/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t EVENT_driverIn(EVENT_data_t *const data)
{


	//Read data from the MCAL driver

	//Scale it to the application type

	return RC_SUCCESS;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t EVENT_driverOut(const EVENT_data_t  *const data)
{


	//Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
}
