/**************************************************
 ** The RTE signals (autogenerated)
 **************************************************/

#include "project.h" 
#include "global.h" 
#include "rte_signalpool.h" 


/* Generated signal classes */
#include "pedal_signal.h"
#include "speed_signal.h"
#include "button_signal.h"
#include "carstate_signal.h"
#include "drivingparam_signal.h"
#include "pwm_signal.h"
#include "event_signal.h"
#include "led_signal.h"
#include "dip_signal.h"
#include "uartprot_signal.h"




/*****************************************************
 ** RTE Object so_pedalPosition
 ** Input signal for pedal position (ADC), range -100..100
 *****************************************************/


/* signal configuration */

static const PEDAL_cfg_t SO_PEDALPOSITION_cfg = 
{
   /* indriver      */  PEDAL_driverIn,
   /* outdriver     */  0,
   /* onUpdate      */  0,
   /* onError       */  ev_pedalPosition_onError
}; /* configuration so_pedalPosition */


/* signal data */

PEDAL_t SO_PEDALPOSITION_signal = 
{
   /* init value    */  PEDAL_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_PEDALPOSITION_cfg
}; /* data so_pedalPosition */


/*****************************************************
 ** RTE Object so_brakeButton
 ** Brake Button State
 *****************************************************/


/* signal configuration */

static const BUTTON_cfg_t SO_BRAKEBUTTON_cfg = 
{
   /* indriver      */  BUTTON_2_driverIn,
   /* outdriver     */  0,
   /* onUpdate      */  0,
   /* onError       */  0
}; /* configuration so_brakeButton */


/* signal data */

BUTTON_t SO_BRAKEBUTTON_signal = 
{
   /* init value    */  BUTTON_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_BRAKEBUTTON_cfg
}; /* data so_brakeButton */


/*****************************************************
 ** RTE Object so_ignitionButton
 ** Ignition Button State
 *****************************************************/


/* signal configuration */

static const BUTTON_cfg_t SO_IGNITIONBUTTON_cfg = 
{
   /* indriver      */  BUTTON_1_driverIn,
   /* outdriver     */  0,
   /* onUpdate      */  0,
   /* onError       */  0
}; /* configuration so_ignitionButton */


/* signal data */

BUTTON_t SO_IGNITIONBUTTON_signal = 
{
   /* init value    */  BUTTON_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_IGNITIONBUTTON_cfg
}; /* data so_ignitionButton */


/*****************************************************
 ** RTE Object so_directionButton
 ** Direction Button State
 *****************************************************/


/* signal configuration */

static const BUTTON_cfg_t SO_DIRECTIONBUTTON_cfg = 
{
   /* indriver      */  BUTTON_3_driverIn,
   /* outdriver     */  0,
   /* onUpdate      */  0,
   /* onError       */  0
}; /* configuration so_directionButton */


/* signal data */

BUTTON_t SO_DIRECTIONBUTTON_signal = 
{
   /* init value    */  BUTTON_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_DIRECTIONBUTTON_cfg
}; /* data so_directionButton */


/*****************************************************
 ** RTE Object so_targetSpeed
 ** Target Speed Signal for engine (SPEED), range 0..MAXRPM
 *****************************************************/


/* signal configuration */

static const SPEED_cfg_t SO_TARGETSPEED_cfg = 
{
   /* indriver      */  0,
   /* outdriver     */  0,
   /* onUpdate      */  0,
   /* onError       */  0
}; /* configuration so_targetSpeed */


/* signal data */

SPEED_t SO_TARGETSPEED_signal = 
{
   /* init value    */  SPEED_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_TARGETSPEED_cfg
}; /* data so_targetSpeed */


/*****************************************************
 ** RTE Object so_currentSpeed
 ** Current Speed Signal for engine (SPEED), range 0..MAXRPM
 *****************************************************/


/* signal configuration */

static const SPEED_cfg_t SO_CURRENTSPEED_cfg = 
{
   /* indriver      */  SPEED_driverIn,
   /* outdriver     */  0,
   /* onUpdate      */  0,
   /* onError       */  ev_currentSpeed_onError
}; /* configuration so_currentSpeed */


/* signal data */

SPEED_t SO_CURRENTSPEED_signal = 
{
   /* init value    */  SPEED_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_CURRENTSPEED_cfg
}; /* data so_currentSpeed */


/*****************************************************
 ** RTE Object so_controlSpeed
 ** Output Signal for engine, range 0..MAXPWM
 *****************************************************/


/* signal configuration */

static const PWM_cfg_t SO_CONTROLSPEED_cfg = 
{
   /* indriver      */  0,
   /* outdriver     */  0,
   /* onUpdate      */  0,
   /* onError       */  ev_controlSpeed_onError
}; /* configuration so_controlSpeed */


/* signal data */

PWM_t SO_CONTROLSPEED_signal = 
{
   /* init value    */  PWM_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_CONTROLSPEED_cfg
}; /* data so_controlSpeed */


/*****************************************************
 ** RTE Object so_carState
 ** Central state object for properties like ignition state, maxspeed,...
 *****************************************************/


/* signal configuration */

static const CARSTATE_cfg_t SO_CARSTATE_cfg = 
{
   /* indriver      */  0,
   /* outdriver     */  0,
   /* onUpdate      */  ev_drivingParam_onUpdate,
   /* onError       */  0
}; /* configuration so_carState */


/* signal data */

CARSTATE_t SO_CARSTATE_signal = 
{
   /* init value    */  CARSTATE_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_CARSTATE_cfg
}; /* data so_carState */


/*****************************************************
 ** RTE Object so_event
 ** Events fired to the central state machine
 *****************************************************/


/* signal configuration */

static const EVENT_cfg_t SO_EVENT_cfg = 
{
   /* indriver      */  0,
   /* outdriver     */  0,
   /* onUpdate      */  ev_event_onUpdate,
   /* onError       */  0
}; /* configuration so_event */


/* signal data */

EVENT_t SO_EVENT_signal = 
{
   /* init value    */  EVENT_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_EVENT_cfg
}; /* data so_event */


/*****************************************************
 ** RTE Object so_drivingParam
 ** Driving parameters like maxspeed, error...Will also be used for the display
 *****************************************************/


/* signal configuration */

static const DRIVINGPARAM_cfg_t SO_DRIVINGPARAM_cfg = 
{
   /* indriver      */  0,
   /* outdriver     */  0,
   /* onUpdate      */  ev_drivingParam_onUpdate,
   /* onError       */  0
}; /* configuration so_drivingParam */


/* signal data */

DRIVINGPARAM_t SO_DRIVINGPARAM_signal = 
{
   /* init value    */  DRIVINGPARAM_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_DRIVINGPARAM_cfg
}; /* data so_drivingParam */


/*****************************************************
 ** RTE Object so_led
 ** Led Signal
 *****************************************************/


/* signal configuration */

static const LED_cfg_t SO_LED_cfg = 
{
   /* indriver      */  0,
   /* outdriver     */  0,
   /* onUpdate      */  0,
   /* onError       */  0
}; /* configuration so_led */


/* signal data */

LED_t SO_LED_signal = 
{
   /* init value    */  LED_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_LED_cfg
}; /* data so_led */


/*****************************************************
 ** RTE Object so_dip
 ** DIP switch State
 *****************************************************/


/* signal configuration */

static const DIP_cfg_t SO_DIP_cfg = 
{
   /* indriver      */  DIP_driverIn,
   /* outdriver     */  0,
   /* onUpdate      */  0,
   /* onError       */  0
}; /* configuration so_dip */


/* signal data */

DIP_t SO_DIP_signal = 
{
   /* init value    */  DIP_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_DIP_cfg
}; /* data so_dip */


/*****************************************************
 ** RTE Object so_uartprot_rx
 ** State communication from control PSOC
 *****************************************************/


/* signal configuration */

static const UARTPROT_cfg_t SO_UARTPROT_RX_cfg = 
{
   /* indriver      */  UARTPROT_driverIn,
   /* outdriver     */  0,
   /* onUpdate      */  0,
   /* onError       */  0
}; /* configuration so_uartprot_rx */


/* signal data */

UARTPROT_t SO_UARTPROT_RX_signal = 
{
   /* init value    */  UARTPROT_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_UARTPROT_RX_cfg
}; /* data so_uartprot_rx */


/*******************************************************************************
 ** Central timertick function for ticktime 10 
 *******************************************************************************/ 

void RTE_timertick()
{
    RTE_PEDAL_incAge( &SO_PEDALPOSITION_signal, 10);
    RTE_BUTTON_incAge( &SO_BRAKEBUTTON_signal, 10);
    RTE_BUTTON_incAge( &SO_IGNITIONBUTTON_signal, 10);
    RTE_BUTTON_incAge( &SO_DIRECTIONBUTTON_signal, 10);
    RTE_SPEED_incAge( &SO_TARGETSPEED_signal, 10);
    RTE_SPEED_incAge( &SO_CURRENTSPEED_signal, 10);
    RTE_PWM_incAge( &SO_CONTROLSPEED_signal, 10);
    RTE_CARSTATE_incAge( &SO_CARSTATE_signal, 10);
    RTE_EVENT_incAge( &SO_EVENT_signal, 10);
    RTE_DRIVINGPARAM_incAge( &SO_DRIVINGPARAM_signal, 10);
    RTE_LED_incAge( &SO_LED_signal, 10);
    RTE_DIP_incAge( &SO_DIP_signal, 10);
    RTE_UARTPROT_incAge( &SO_UARTPROT_RX_signal, 10);
}

