/*
 * uartprot_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */


#include "project.h"
#include "global.h"

#include "logging.h"

#include "uartprot_type.h"


/** ------------------------ Global UART buffers ---------------------------------- **/

uint8_t REMOTE_uartBuffer[PROT_SIZERXBUF] = {0};
ringbuffer_hdl_t REMOTE_rx_buffer;

/** ------------------------ Driver ---------------------------------- **/

static boolean_t UARTPROT__isSynced = FALSE;

/**
 * As the sender and receiver possibly do not start at the same time and we might suffer from boot-bytes, 
 * all bytes are ignored until we find the first true byte in the sequence
 * later on, this concept may also be used for resynchronisation
 * \param uint8_t data  : IN Byte currently received
 * \ return: TRUE if system is in sync, false otherwise
 */
boolean_t UARTPROT_SyncProtocol(uint8_t data)
{
    //Identify valid start of protocol identifier
    if (UARTPROT_SOP == data )
    {
        UARTPROT__isSynced = TRUE;
    }
    
    return UARTPROT__isSynced;
}

uint8_t calcCRC(const UARTPROT_data_t  *const data)
{
    uint8_t crc = 0;
    crc = (uint8_t)data->m_state ^ (uint8_t) data->m_targetspeed ^(uint8_t) (data->m_targetspeed >> 8) ^ (uint8_t) data->m_currentspeed ^(uint8_t) (data->m_currentspeed >> 8);
    
    return crc;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t UARTPROT_driverIn(UARTPROT_data_t *const data)
{

	//Read data from the MCAL driver
    uint8_t byte = 0;
    RC_t res = RC_ERROR;
    
    //SOP

    
    res = Ringbuffer_Get(&REMOTE_rx_buffer, &byte);
    if (RC_SUCCESS != res) return res;
    if (UARTPROT_SOP != byte) 
    {
        Ringbuffer_Clear(&REMOTE_rx_buffer);
        UARTPROT__isSynced = FALSE;
        return RC_ERROR_BAD_DATA;
    }
    
    //State
    
    res = Ringbuffer_Get(&REMOTE_rx_buffer, &byte);
    if (RC_SUCCESS != res) return res;
    data->m_state = (CAR_state_t)byte;
    
    //Targetspeed
    
    uint32_t buffer = 0;
    res = Ringbuffer_Get(&REMOTE_rx_buffer, &byte);
    if (RC_SUCCESS != res) return res;
    buffer = byte;

    res = Ringbuffer_Get(&REMOTE_rx_buffer, &byte);
    if (RC_SUCCESS != res) return res;
    buffer = buffer + (byte << 8);

    data->m_targetspeed = (sint16_t)buffer;
    
    //Currentspeed
    
    buffer = 0;
    res = Ringbuffer_Get(&REMOTE_rx_buffer, &byte);
    if (RC_SUCCESS != res) return res;
    buffer = byte;

    res = Ringbuffer_Get(&REMOTE_rx_buffer, &byte);
    if (RC_SUCCESS != res) return res;
    buffer = buffer + (byte << 8);

    data->m_currentspeed = (sint16_t)buffer;
    
    //CRC
    uint8_t crccalc = calcCRC(data);
    
    res = Ringbuffer_Get(&REMOTE_rx_buffer, &byte);
    if (RC_SUCCESS != res) return res;
    if (crccalc != byte)
    {
        return RC_ERROR_CHECKSUM;
    }

    //EOP
    
    res = Ringbuffer_Get(&REMOTE_rx_buffer, &byte);
    if (RC_SUCCESS != res) return res;
    if (UARTPROT_EOP1 != byte)
    {
        return RC_ERROR_BAD_DATA;;
    }

    res = Ringbuffer_Get(&REMOTE_rx_buffer, &byte);
    if (RC_SUCCESS != res) return res;
    if (UARTPROT_EOP2 != byte)
    {
        return RC_ERROR_BAD_DATA;
    }
    
    return RC_SUCCESS;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t UARTPROT_driverOut(const UARTPROT_data_t  *const data)
{


	//Scale application data to drive format
    //Write scaled data to driver
    
    uint8_t byte = 0;
    
    UART_PSOC_WriteTxData(UARTPROT_SOP);
    
    byte = (uint8_t) data->m_state;
    UART_PSOC_WriteTxData(byte);
    
    byte=(uint8_t) (data->m_targetspeed);
    UART_PSOC_WriteTxData(byte);
    
    byte=(uint8_t) (data->m_targetspeed >> 8);
    UART_PSOC_WriteTxData(byte);
    
    byte=(uint8_t) (data->m_currentspeed);
    UART_PSOC_WriteTxData(byte);
    
    byte=(uint8_t) (data->m_currentspeed >> 8);
    UART_PSOC_WriteTxData(byte);
    
    byte=calcCRC(data);
    UART_PSOC_WriteTxData(byte);
    
    UART_PSOC_WriteTxData(UARTPROT_EOP1);
    UART_PSOC_WriteTxData(UARTPROT_EOP2);

	

	return RC_SUCCESS;
}
