
/*
 * Filename: swc_display.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Software component for HMI runnable
 */

#ifndef _H_DEFINE_SWC_DISPLAY
#define _H_DEFINE_SWC_DISPLAY

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_DISPLAY_INCLUDES */

/* USER CODE END SWC_DISPLAY_INCLUDES */



/* USER CODE START SWC_DISPLAY_USERDEFINITIONS */

/* USER CODE END SWC_DISPLAY_USERDEFINITIONS */


/*
 * component: swc_Display
 * cycletime: 250
 * description: Runnable for HMI runnable 
 * events: 
 * name: DISPLAY_Clock_Display_run
 * shortname: Clock_Display
 * signalIN: so_Control_Out
 * signalOUT: so_Display
 * task: tsk_HMI
 */
void DISPLAY_Clock_Display_run(RTE_event ev);


#endif