/*
 * Filename: swc_control.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component for Control runnable containing state machine
 * name: swc_Control
 * shortname: Control
 *
 */





/* USER CODE START SWC_CONTROL_INCLUDE */
#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_control.h"
#include "statemachine.h"
#include "statemachine_cfg.h"
#include "sp_common.h"
#include "stdlib.h"

/* USER CODE END SWC_CONTROL_INCLUDE */




/* USER CODE START SWC_CONTROL_USERDEFINITIONS */

/* USER CODE END SWC_CONTROL_USERDEFINITIONS */




/* USER CODE START SWC_CONTROL_FUNCTIONS */
    
static void CLOCK__dispatch_keyLeft_to_WdgHour();
static void CLOCK__dispatch_keyRight_to_WdgHour();
static void CLOCK__dispatch_keyRightLongPress_to_WdgHour();
static void CLOCK__dispatch_ev_250_to_WdgHour();
static void CLOCK__dispatch_keyleft_to_WdgMinute();
static void CLOCK__dispatch_keyRight_to_WdgMinute();
static void CLOCK__dispatch_keyRightLongPress_to_WdgMinute();
static void CLOCK__dispatch_ev_250_to_WdgMinute();
static void CLOCK__dispatch_keyleft_to_IS_Displaying();
static void CLOCK__update_Timer();
static void CLOCK__update_Display();

// Hour Functions
static void CLOCK__IncrementHours();
static void CLOCK__updateHour_Display();

static void CLOCK__updateHour_Display_AutoIncrement();
static void CLOCK__IncrementHours_AutoIncrement();

//Minute Functions
static void CLOCK__IncrementMinute();
static void CLOCK__updateMinute_Display();

static void CLOCK__updateMinute_Display_AutoIncrement();
static void CLOCK__IncrementMinute_AutoIncrement();


/* USER CODE END SWC_CONTROL_FUNCTIONS */


/** ---------------------------------- Transitions ---------------------------------------- **/

/**  ===== IS_DISPLAYING ====   */
static const STATE_stateInnerTransitionTable_t STATE_IS_Displaying = {
/*    Event                   ToState                 Guard                 Action                       */
    { EV_KEYLEFT,         IS_ContainerHour,            0,             CLOCK__dispatch_keyLeft_to_WdgHour},
    { EV_1MIN,            IS_Displaying,               0,                 CLOCK__update_Timer},
    {0,0,0,0},
};

/**  ===== IS_CONATINER_HOUR ====   */
static const STATE_stateInnerTransitionTable_t STATE_IS_ContainerHour = {
/*    Event                            ToState                     Guard               Action                       */
    { EV_KEYRIGHT,                IS_ContainerHour,                 0,            CLOCK__dispatch_keyRight_to_WdgHour},
    { EV_KEYRIGHTLONGPRESS,       IS_ContainerHour,                 0,            CLOCK__dispatch_keyRightLongPress_to_WdgHour},
    { EV_250MS,                   IS_ContainerHour,                 0,            CLOCK__dispatch_ev_250_to_WdgHour},
    { EV_KEYLEFT,                 IS_ContainerMinute,               0,            CLOCK__dispatch_keyleft_to_WdgMinute},    
    {0,0,0,0},
};

/**  ===== IS_CONTAINER_MINUTE ====   */
static const STATE_stateInnerTransitionTable_t STATE_IS_ContainerMinute = {
/*    Event                         ToState                     Guard                       Action                       */
    { EV_KEYRIGHT,              IS_ContainerMinute,             0,            CLOCK__dispatch_keyRight_to_WdgMinute},
    { EV_KEYRIGHTLONGPRESS,     IS_ContainerMinute,             0,            CLOCK__dispatch_keyRightLongPress_to_WdgMinute},
    { EV_250MS,                 IS_ContainerMinute,             0,            CLOCK__dispatch_ev_250_to_WdgMinute},
    { EV_KEYLEFT,               IS_Displaying,                  0,            CLOCK__dispatch_keyleft_to_IS_Displaying},
    {0,0,0,0},
    
};

/** ======= CONTAINER_OUTERTRANSITION_TABLE =======   */
static const STATE_stateOuterTransitionTable_t STATE_Container_StateMachine = {
/*    fromState                    Pointer to table                            Size of table [Elements]    */
    { IS_Displaying,            &STATE_IS_Displaying,                 sizeof(STATE_IS_Displaying)/sizeof(STATE_stateInnerTransition_t)},
    { IS_ContainerMinute,       &STATE_IS_ContainerMinute,            sizeof(STATE_IS_ContainerMinute)/sizeof(STATE_stateInnerTransition_t)},
    { IS_ContainerHour,         &STATE_IS_ContainerHour,              sizeof(STATE_IS_ContainerHour)/sizeof(STATE_stateInnerTransition_t)},
    {0,0,0},
};
static const uint16_t STATE_Container_StateMachine_size = sizeof(STATE_Container_StateMachine)/sizeof(STATE_stateOuterTransition_t);

/** ---------------------------------- Action ------------------------------------------- **/

static const STATE_stateActionTable_t STATE_Container_StateActions = {
/*  fromState                          Entry                         Exit    */
  { IS_Displaying,              CLOCK__update_Display,                0   },
  { IS_ContainerMinute,                  0,                           0   },
  { IS_ContainerHour,                    0,                           0   },
  {0,0,0},
};
static const uint16_t STATE_Container_StateActions_size = sizeof(STATE_Container_StateActions)/sizeof(STATE_stateAction_t);


/** ---------------------------------- Child Transitions (HOUR WIDGET) ---------------------------------------- **/

/**  ===== IS_HOUR_FOCUS ====   */
static const STATE_stateInnerTransitionTable_t STATE_IS_HourFocus = {
/*    Event                         ToState                 Guard                 Action                       */
    { EV_KEYLEFT,               IS_MinuteFocus,               0,                       0},
    { EV_KEYRIGHT,              IS_HourFocus,                 0,                 CLOCK__IncrementHours},
    { EV_KEYRIGHTLONGPRESS,     IS_HourAutoIncrement,         0,                 CLOCK__IncrementHours},
    {0,0,0,0},
};

/**  ===== IS_HOUR_AUTO_INCREMENT ====   */
static const STATE_stateInnerTransitionTable_t STATE_IS_HourAutoIncrement = {
/*    Event                            ToState                     Guard               Action                       */
    { EV_250MS,                   IS_HourAutoIncrement,             0,            CLOCK__IncrementHours},
    { EV_KEYRIGHT,                IS_HourFocus,                     0,                    0},
    {0,0,0,0},
};

/** ======= HOUR_WIDGET_OUTERTRANSITION_TABLE ======= */
static const STATE_stateOuterTransitionTable_t STATE_IS_Hour_StateMachine = {
/*    fromState                    Pointer to table                            Size of table [Elements]    */
    { IS_HourFocus,               &STATE_IS_HourFocus,                 sizeof(STATE_IS_HourFocus)/sizeof(STATE_stateInnerTransition_t)},
    { IS_HourAutoIncrement,       &STATE_IS_HourAutoIncrement,         sizeof(STATE_IS_HourAutoIncrement)/sizeof(STATE_stateInnerTransition_t)},
    {0,0,0},
};
static const uint16_t STATE_IS_Hour_StateMachine_size = sizeof(STATE_IS_Hour_StateMachine)/sizeof(STATE_stateOuterTransition_t);

/** ---------------------------------- Action (HOUR_WIDGET) ------------------------------------------- **/

static const STATE_stateActionTable_t STATE_IS_Hour_StateActions = {
/*  fromState                          Entry                                       Exit    */
 
  { IS_HourFocus,               CLOCK__updateHour_Display,                              0   },
  { IS_HourAutoIncrement,       CLOCK__updateHour_Display,                              0   },
  {0,0,0},
};
static const uint16_t STATE_IS_Hour_StateActions_size = sizeof(STATE_IS_Hour_StateActions)/sizeof(STATE_stateAction_t);

/** ---------------------------------- Child Transitions (MINUTE WIDGET) ---------------------------------------- **/

/**  ===== IS_MINUTE_FOCUS ====   */
static const STATE_stateInnerTransitionTable_t STATE_IS_MinuteFocus = {
/*    Event                         ToState                     Guard                 Action                       */
    { EV_KEYLEFT,               IS_Displaying,                  0,                       0},
    { EV_KEYRIGHT,              IS_MinuteFocus,                 0,                 CLOCK__IncrementMinute},
    { EV_KEYRIGHTLONGPRESS,     IS_MinuteAutoIncrement,         0,                 CLOCK__IncrementMinute},
    {0,0,0,0},
};

/**  ===== IS_MINUTE_AUTO_INCREMENT ====   */
static const STATE_stateInnerTransitionTable_t STATE_IS_MinuteAutoIncrement = {
/*    Event                            ToState                      Guard               Action                       */
    { EV_250MS,                   IS_MinuteAutoIncrement,             0,            CLOCK__IncrementMinute},
    { EV_KEYRIGHT,                IS_MinuteFocus,                     0,                    0},
    {0,0,0,0},
};

/** ======= MINUTE_WIDGET_OUTERTRANSITION_TABLE ======= */
static const STATE_stateOuterTransitionTable_t STATE_IS_Minute_StateMachine = {
/*    fromState                    Pointer to table                            Size of table [Elements]    */
    { IS_MinuteFocus,               &STATE_IS_MinuteFocus,                 sizeof(STATE_IS_MinuteFocus)/sizeof(STATE_stateInnerTransition_t)},
    { IS_MinuteAutoIncrement,       &STATE_IS_MinuteAutoIncrement,         sizeof(STATE_IS_MinuteAutoIncrement)/sizeof(STATE_stateInnerTransition_t)},
    {0,0,0},
};
static const uint16_t STATE_IS_Minute_StateMachine_size = sizeof(STATE_IS_Minute_StateMachine)/sizeof(STATE_stateOuterTransition_t);

/** ---------------------------------- Action (MINUTE_WIDGET) ------------------------------------------- **/

static const STATE_stateActionTable_t STATE_IS_Minute_StateActions = {
/*  fromState                          Entry                                       Exit    */
  { IS_MinuteFocus,               CLOCK__updateMinute_Display,                                0   },
  { IS_MinuteAutoIncrement,       CLOCK__updateMinute_Display,                                0   },
  {0,0,0},
};
static const uint16_t STATE_IS_Minute_StateActions_size = sizeof(STATE_IS_Hour_StateActions)/sizeof(STATE_stateAction_t);


static Active_object Container = {{&STATE_Container_StateMachine,&STATE_Container_StateActions,&STATE_Container_StateMachine_size,&STATE_Container_StateActions_size,IS_Displaying}};
static Active_object widget_HOUR = {{&STATE_IS_Hour_StateMachine,&STATE_IS_Hour_StateActions,&STATE_IS_Hour_StateMachine_size,&STATE_IS_Hour_StateActions_size,IS_ContainerHour}};
static Active_object widget_MINUTE = {{&STATE_IS_Minute_StateMachine,&STATE_IS_Minute_StateActions,&STATE_IS_Minute_StateMachine_size,&STATE_IS_Minute_StateActions_size,IS_ContainerMinute}};

static CLOCK_time_t time = CLOCK_time_INIT_DATA;

static void CLOCK__dispatch_keyLeft_to_WdgHour()
{ 
    Widget_Hour_statemachine_INIT();
}
static void CLOCK__dispatch_keyRight_to_WdgHour()
{
    Widget_Hour_statemachine_RUN(EV_KEYRIGHT,&widget_HOUR); 
}

static void CLOCK__dispatch_keyRightLongPress_to_WdgHour()
{
    Widget_Hour_statemachine_RUN(EV_KEYRIGHTLONGPRESS,&widget_HOUR);   
}
static void CLOCK__dispatch_ev_250_to_WdgHour()
{
    Widget_Hour_statemachine_RUN(EV_250MS,&widget_HOUR);
}
static void CLOCK__dispatch_keyleft_to_WdgMinute()
{
    Widget_Minute_statemachine_INIT(&widget_MINUTE);
}
static void CLOCK__dispatch_keyRight_to_WdgMinute()
{
    Widget_Minute_statemachine_RUN(EV_KEYRIGHT,&widget_MINUTE); 
}
static void CLOCK__dispatch_keyRightLongPress_to_WdgMinute()
{
     Widget_Minute_statemachine_RUN(EV_KEYRIGHTLONGPRESS,&widget_MINUTE);   
}
static void CLOCK__dispatch_ev_250_to_WdgMinute()
{
    Widget_Minute_statemachine_RUN(EV_250MS,&widget_MINUTE);
}
static void CLOCK__dispatch_keyleft_to_IS_Displaying()
{
    UART_LOG_PutString("Keyleft pressed and went to IDLE State\r"); 
}
static void CLOCK__update_Timer()
{
    UART_LOG_PutString("Update timer.\r"); 
    CLOCK__IncrementMinute();
      
}
static void CLOCK__update_Display()
{
    
    SC_CONTROL_OUT_data_t display_cmd;
    
    display_cmd.time = time;
    display_cmd.mode = DISPLAYING_MODE;
    
    RTE_SC_CONTROL_OUT_set(&SO_CONTROL_OUT_signal,display_cmd);
    
    
}


// Is_Hour Functions

static void CLOCK__IncrementHours()
{
    UART_LOG_PutString("Increment Hours\r");
    if(time.Hour == Hour_Maximum)
    {
        time.Hour = 0;
    }
    else
    {
        time.Hour ++;
    }
    
    
}

static void CLOCK__updateHour_Display()
{
    SC_CONTROL_OUT_data_t display_cmd;
    
    display_cmd.time = time;
    display_cmd.mode = EDITING_MODE_HOUR;
    
    RTE_SC_CONTROL_OUT_set(&SO_CONTROL_OUT_signal,display_cmd);
}

static void CLOCK__IncrementHours_AutoIncrement()
{
    UART_LOG_PutString("Increment Hours Automatically\r");
}

static void CLOCK__updateHour_Display_AutoIncrement()
{
    UART_LOG_PutString("Updating Hour Display Automatically\r");
}

// Is_Minute Functions

static void CLOCK__IncrementMinute()
{
    UART_LOG_PutString("Increment Minute\r");
    if(time.Minute < Minute_Maximum)
    {
        time.Minute++;
    }
    else if(time.Minute == Minute_Maximum)
    {
        CLOCK__IncrementHours();
        time.Minute = 0;
    }
    
}

static void CLOCK__updateMinute_Display()
{
    SC_CONTROL_OUT_data_t display_cmd;
    
    display_cmd.time = time;
    display_cmd.mode = EDITING_MODE_MINUTE;
    
    RTE_SC_CONTROL_OUT_set(&SO_CONTROL_OUT_signal,display_cmd);
}

static void CLOCK__IncrementMinute_AutoIncrement()
{
    UART_LOG_PutString("Increment Minute Automatically\r");
    CLOCK__IncrementMinute();
}

static void CLOCK__updateMinute_Display_AutoIncrement()
{
    UART_LOG_PutString("Updating Minute Display Automatically\r");
    
}

void Container_statemachine_INIT()
{
    STATE_initState(*Container.state_machine.p_ActionTable,*Container.state_machine.size_ActionTable,&Container.state_machine.state,CONTAINER_STATE_INIT_DATA);   
}

void Container_statemachine_RUN(STATE_event_t ev, Active_object* container)
{
    STATE_processEvent(*container->state_machine.p_TransitionTable,*container->state_machine.size_TransitionTable,*container->state_machine.p_ActionTable,*container->state_machine.size_ActionTable,ev,&container->state_machine.state);
}


void Widget_Hour_statemachine_INIT()
{   
   STATE_initState(*widget_HOUR.state_machine.p_ActionTable,*widget_HOUR.state_machine.size_ActionTable,&widget_HOUR.state_machine.state,WIDGET_HOUR_INIT_DATA);   
}

void Widget_Hour_statemachine_RUN(STATE_event_t ev, Active_object* widget_Hour)
{
    STATE_processEvent(*widget_Hour->state_machine.p_TransitionTable,*widget_Hour->state_machine.size_TransitionTable,*widget_Hour->state_machine.p_ActionTable,*widget_Hour->state_machine.size_ActionTable,ev,&widget_Hour->state_machine.state);
}

void Widget_Minute_statemachine_INIT()
{
    STATE_initState(*widget_MINUTE.state_machine.p_ActionTable,*widget_MINUTE.state_machine.size_ActionTable,&widget_MINUTE.state_machine.state,WIDGET_MINUTE_INIT_DATA);   
}

void Widget_Minute_statemachine_RUN(STATE_event_t ev, Active_object* widget_Minute)
{
    STATE_processEvent(*widget_Minute->state_machine.p_TransitionTable,*widget_Minute->state_machine.size_TransitionTable,*widget_Minute->state_machine.p_ActionTable,*widget_Minute->state_machine.size_ActionTable,ev,&widget_Minute->state_machine.state);
}

/*
 * component: swc_Control
 * cycletime: 0
 * description: Runnable for Control runnable containing state machine
 * events: ev_Button_OnData
 * name: CONTROL_Clock_Control_run
 * shortname: Clock_Control
 * signalIN: so_Button_Event
 * signalOUT: so_Control_Out
 * task: tsk_realtime
 */
void CONTROL_Clock_Control_run(RTE_event ev){
	
	/* USER CODE START CONTROL_Clock_Control_run */
    
   SC_BUTTON_EVENT_data_t button_event = RTE_SC_BUTTON_EVENT_get(&SO_BUTTON_EVENT_signal);

    
   
   if(button_event.ev == EV_KEYLEFT)
    {
        Container_statemachine_RUN(EV_KEYLEFT,&Container);
        
    }
   else if(button_event.ev == EV_KEYRIGHT)
    {
        Container_statemachine_RUN(EV_KEYRIGHT,&Container);
    }
   else if(button_event.ev == EV_KEYRIGHTLONGPRESS)
    {
        Container_statemachine_RUN(EV_KEYRIGHTLONGPRESS,&Container);
    }
    else if(button_event.ev == EV_250MS)
    {
        Container_statemachine_RUN(EV_250MS,&Container);
    }
    else if(button_event.ev == EV_1MIN)
    {
        Container_statemachine_RUN(EV_1MIN,&Container);
    }
    
    

    /* USER CODE END CONTROL_Clock_Control_run */
}
