
/*
 * Filename: swc_input.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Software components for Button input events for left short and right short/long press
 */

#ifndef _H_DEFINE_SWC_INPUT
#define _H_DEFINE_SWC_INPUT

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_INPUT_INCLUDES */

/* USER CODE END SWC_INPUT_INCLUDES */



/* USER CODE START SWC_INPUT_USERDEFINITIONS */

/* USER CODE END SWC_INPUT_USERDEFINITIONS */


/*
 * component: swc_Input
 * cycletime: 50
 * description: Runnable for  Button input events for left short and right short/long press
 * events: 
 * name: INPUT_Clock_Input_run
 * shortname: Clock_Input
 * signalIN: 
 * signalOUT: so_Button_Event
 * task: tsk_realtime
 */
void INPUT_Clock_Input_run(RTE_event ev);


#endif