/*
 * Filename: swc_input.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software components for Button input events for left short and right short/long press
 * name: swc_Input
 * shortname: Input
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_input.h"



/* USER CODE START SWC_INPUT_INCLUDE */
#include "sp_common.h"
/* USER CODE END SWC_INPUT_INCLUDE */




/* USER CODE START SWC_INPUT_USERDEFINITIONS */

/* USER CODE END SWC_INPUT_USERDEFINITIONS */



/*
 * component: swc_Input
 * cycletime: 50
 * description: Runnable for  Button input events for left short and right short/long press
 * events: 
 * name: INPUT_Clock_Input_run
 * shortname: Clock_Input
 * signalIN: 
 * signalOUT: so_Button_Event
 * task: tsk_realtime
 */
void INPUT_Clock_Input_run(RTE_event ev){
	
	/* USER CODE START INPUT_Clock_Input_run */
    
    RTE_SC_BUTTON_EVENT_pullPort(&SO_BUTTON_EVENT_signal);
    

    /* USER CODE END INPUT_Clock_Input_run */
}

/* USER CODE START SWC_INPUT_FUNCTIONS */

/* USER CODE END SWC_INPUT_FUNCTIONS */

