/*
 * Filename: swc_display.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component for HMI runnable
 * name: swc_Display
 * shortname: Display
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_display.h"
#include "stdlib.h"
#include "tft.h"



/* USER CODE START SWC_DISPLAY_INCLUDE */

/* USER CODE END SWC_DISPLAY_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_DISPLAY_USERDEFINITIONS */

/* USER CODE END SWC_DISPLAY_USERDEFINITIONS */



/*
 * component: swc_Display
 * cycletime: 250
 * description: Runnable for HMI runnable 
 * events: 
 * name: DISPLAY_Clock_Display_run
 * shortname: Clock_Display
 * signalIN: so_Control_Out
 * signalOUT: so_Display
 * task: tsk_HMI
 */
void DISPLAY_Clock_Display_run(RTE_event ev){
	
	/* USER CODE START DISPLAY_Clock_Display_run */
    
    SC_CONTROL_OUT_data_t display_cmd = RTE_SC_CONTROL_OUT_get(&SO_CONTROL_OUT_signal);
    
    SC_DISPLAY_data_t tft_cmd;
    
    tft_cmd.hour = display_cmd.time.Hour;
    tft_cmd.minute = display_cmd.time.Minute;
    if(display_cmd.mode == DISPLAYING_MODE)
    {
        tft_cmd.Mode = TFT_IS_DISPLAYING;
    }
    else if((display_cmd.mode == EDITING_MODE_HOUR) || (display_cmd.mode == EDITING_MODE_MINUTE))
    {
        tft_cmd.Mode = TFT_IS_EDITING;
    }
    
    RTE_SC_DISPLAY_set(&SO_DISPLAY_signal, tft_cmd);
    RTE_SC_DISPLAY_pushPort(&SO_DISPLAY_signal);
      
    /* USER CODE END DISPLAY_Clock_Display_run */
}

/* USER CODE START SWC_DISPLAY_FUNCTIONS */

/* USER CODE END SWC_DISPLAY_FUNCTIONS */

