
/*
 * Filename: swc_age.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Software component for calculating age of the signals
 */

#ifndef _H_DEFINE_SWC_AGE
#define _H_DEFINE_SWC_AGE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_AGE_INCLUDES */

/* USER CODE END SWC_AGE_INCLUDES */



/* USER CODE START SWC_AGE_USERDEFINITIONS */

/* USER CODE END SWC_AGE_USERDEFINITIONS */


/*
 * component: swc_age
 * cycletime: 1
 * description: Runnable calculating age of the signals
 * events: 
 * name: AGE_IncAge_run
 * shortname: IncAge
 * signalIN: so_Button_Event|so_Control_Out|so_Display
 * signalOUT: so_Button_Event|so_Control_Out|so_Display
 * task: tsk_system
 */
void AGE_IncAge_run(RTE_event ev);


#endif