/*
 * Filename: swc_age.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component for calculating age of the signals
 * name: swc_age
 * shortname: age
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_age.h"



/* USER CODE START SWC_AGE_INCLUDE */

/* USER CODE END SWC_AGE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_AGE_USERDEFINITIONS */

/* USER CODE END SWC_AGE_USERDEFINITIONS */



/*
 * component: swc_age
 * cycletime: 1
 * description: Runnable calculating age of the signals
 * events: 
 * name: AGE_IncAge_run
 * shortname: IncAge
 * signalIN: so_Button_Event|so_Control_Out|so_Display
 * signalOUT: so_Button_Event|so_Control_Out|so_Display
 * task: tsk_system
 */
void AGE_IncAge_run(RTE_event ev){
	
	/* USER CODE START AGE_IncAge_run */

    /* USER CODE END AGE_IncAge_run */
}

/* USER CODE START SWC_AGE_FUNCTIONS */

/* USER CODE END SWC_AGE_FUNCTIONS */

