/*
 * event_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */



#ifndef EVENT_TYPE_H_
#define EVENT_TYPE_H_

#include "global.h"

/*****************************************************************************************
 *************** Type Definition for EVENT signal                     **************************
 *****************************************************************************************/


typedef enum {
    EVENT_none,
    
    EVENT_tick,
    EVENT_error,
    
    EVENT_ignitionPressed,
    EVENT_ignitionDepressed,
    EVENT_brakePressed,
    EVENT_brakeDepressed,
    EVENT_directionPressed,
    EVENT_directionDepressed
    
    } EVENT_mask_t;
typedef struct
{
    EVENT_mask_t m_ev;
} EVENT_data_t;


#define EVENT_INIT_DATA ((EVENT_data_t){EVENT_none})


/**
 * Default IN driver API - may be deleted if not required
 * \param EVENT_data_t *const data : [OUT] scaled data read from the driver
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t EVENT_driverIn(EVENT_data_t *const data);


/**
 * Default IN driver API - may be deleted if not required
 * \param const EVENT_data_t  *const data : [IN] signal data for the driver, will be scaled in this function
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t EVENT_driverOut(const EVENT_data_t  *const data);



#endif /* EVENT_TYPE_H_ */

