/*
 * speed_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */



#ifndef SPEED_TYPE_H_
#define SPEED_TYPE_H_

#include "global.h"

/*****************************************************************************************
 *************** Type Definition for SPEED signal                     **************************
 *****************************************************************************************/



typedef struct
{
    sint16_t m_rpm;     /**< \brief speed in rpm */
} SPEED_data_t;

#define SPEED_INIT_DATA ((SPEED_data_t){0})


/**
 * Default IN driver API - may be deleted if not required
 * \param SPEED_data_t *const data : [OUT] scaled data read from the driver
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t SPEED_driverIn(SPEED_data_t *const data);


/**
 * Default IN driver API - may be deleted if not required
 * \param const SPEED_data_t  *const data : [IN] signal data for the driver, will be scaled in this function
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t SPEED_driverOut(const SPEED_data_t  *const data);



#endif /* SPEED_TYPE_H_ */

