
/*
 * Filename: swc_remote.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Remote control, reading / sending XBee protocols
 */

#ifndef _H_DEFINE_SWC_REMOTE
#define _H_DEFINE_SWC_REMOTE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_REMOTE_INCLUDES */

/* USER CODE END SWC_REMOTE_INCLUDES */



/* USER CODE START SWC_REMOTE_USERDEFINITIONS */

/* USER CODE END SWC_REMOTE_USERDEFINITIONS */


/*
 * component: swc_remote
 * cycletime: 0
 * description: Receives outgoing event and creates and XBee protocol
 * events: ev_eventout_onData
 * name: REMOTE_transmit_run
 * shortname: transmit
 * signalIN: so_eventOut
 * signalOUT: so_protocolTx
 * task: tsk_io
 */
void REMOTE_transmit_run(RTE_event ev);

/*
 * component: swc_remote
 * cycletime: 0
 * description: Receive an incoming protocol and translates the content into joystick or event signal
 * events: ev_xbee_rx
 * name: REMOTE_receive_run
 * shortname: receive
 * signalIN: so_protocolRx
 * signalOUT: so_joystick|so_eventIn
 * task: tsk_io
 */
void REMOTE_receive_run(RTE_event ev);

/*
 * component: swc_remote
 * cycletime: 100
 * description: Error handler for Remote. Triggers on invalid data and wrong age. Will call central error handler as escalation.
 * events: ev_protocolrx_onError
 * name: REMOTE_error_run
 * shortname: error
 * signalIN: so_protocolRx|so_protocolTx
 * signalOUT: 
 * task: tsk_io
 */
void REMOTE_error_run(RTE_event ev);


#endif