/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "TFT_DC_aliases.h"
#include "TFT_DC.h"
#include "TFT_CS_aliases.h"
#include "TFT_CS.h"
#include "TFT_RES_aliases.h"
#include "TFT_RES.h"
#include "wTFT_SDA_aliases.h"
#include "wTFT_SDA.h"
#include "wTFT_SCL_aliases.h"
#include "wTFT_SCL.h"
#include "TFT_SPI.h"
#include "TFT_SPI_PVT.h"
#include "TFT_LED_aliases.h"
#include "TFT_LED.h"
#include "UART_LOG.h"
#include "TFT_BackLight.h"
#include "Clock_1.h"
#include "JOYSTICK_ADC_Y_aliases.h"
#include "JOYSTICK_ADC_Y.h"
#include "ErikaOS_1_ee.h"
#include "ErikaOS_1_ee_tracing.h"
#include "JOYSTICK_ADC_X_aliases.h"
#include "JOYSTICK_ADC_X.h"
#include "JOYSTICK_ADC_XY.h"
#include "isr_Button.h"
#include "BUTTON_1_aliases.h"
#include "BUTTON_1.h"
#include "BUTTON_2_aliases.h"
#include "BUTTON_2.h"
#include "BUTTON_3_aliases.h"
#include "BUTTON_3.h"
#include "BUTTON_4_aliases.h"
#include "BUTTON_4.h"
#include "seg_A_aliases.h"
#include "seg_A.h"
#include "seg_B_aliases.h"
#include "seg_B.h"
#include "seg_C_aliases.h"
#include "seg_C.h"
#include "seg_D_aliases.h"
#include "seg_D.h"
#include "seg_E_aliases.h"
#include "seg_E.h"
#include "seg_F_aliases.h"
#include "seg_F.h"
#include "seg_G_aliases.h"
#include "seg_G.h"
#include "SEVEN_DP_aliases.h"
#include "SEVEN_DP.h"
#include "SEVEN_SELECT_aliases.h"
#include "SEVEN_SELECT.h"
#include "SEVEN_reg.h"
#include "CAN_RX_aliases.h"
#include "CAN_RX.h"
#include "CAN_TX_aliases.h"
#include "CAN_TX.h"
#include "CAN.h"
#include "TFT_SPI_IntClock.h"
#include "UART_LOG_IntClock.h"
#include "JOYSTICK_ADC_XY_SAR.h"
#include "JOYSTICK_ADC_XY_IntClock.h"
#include "JOYSTICK_ADC_XY_TempBuf_dma.h"
#include "JOYSTICK_ADC_XY_FinalBuf_dma.h"
#include "JOYSTICK_ADC_XY_IRQ.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

