/*
 * button_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */



#ifndef BUTTON_TYPE_H_
#define BUTTON_TYPE_H_

#include "global.h"
#include "button.h"

/*****************************************************************************************
 *************** Type Definition for BUTTON signal              **************************
 *****************************************************************************************/


typedef enum {
    BUTTON_LOW,         /**< \brief 0 -> 0 */
    BUTTON_HIGH,        /**< \brief 1 -> 1 */
    BUTTON_PRESSED,     /**< \brief 0 -> 1 */
    BUTTON_DEPRESSED,   /**< \brief 1 -> 0 */
} button_state_t;
    
typedef struct
{
    button_state_t m_button;
} BUTTON_data_t;


#define BUTTON_INIT_DATA ((BUTTON_data_t){BUTTON_LOW})


/**
 * Default IN driver API - may be deleted if not required
 * \param BUTTON_data_t *const data : [OUT] scaled data read from the driver
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t BUTTON_1_driverIn(BUTTON_data_t *const data);

/**
 * Default IN driver API - may be deleted if not required
 * \param BUTTON_data_t *const data : [OUT] scaled data read from the driver
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t BUTTON_2_driverIn(BUTTON_data_t *const data);

/**
 * Default IN driver API - may be deleted if not required
 * \param BUTTON_data_t *const data : [OUT] scaled data read from the driver
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t BUTTON_3_driverIn(BUTTON_data_t *const data);



/**
 * Default IN driver API - may be deleted if not required
 * \param const BUTTON_data_t  *const data : [IN] signal data for the driver, will be scaled in this function
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t BUTTON_driverOut(const BUTTON_data_t  *const data);



#endif /* BUTTON_TYPE_H_ */

