/*
 * drivingParam_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */



#ifndef DRIVINGPARAM_TYPE_H_
#define DRIVINGPARAM_TYPE_H_

#include "global.h"
#include "engine_cfg.h"
/*****************************************************************************************
 *************** Type Definition for DRIVINGPARAM signal                     **************************
 *****************************************************************************************/


typedef enum {
    ERROR_ALLOK,
    
    ERROR_PEDAL,
    ERROR_LOGIC,
    ERROR_ACTOR,
    ERROR_SYSTEM,
} CAR_error_t;
    
typedef enum {
    DIRECTION_NEUTRAL,
    DIRECTION_FORWARD,
    DIRECTION_REVERSE
} CAR_direction_t;
    
typedef struct
{
    sint16_t        m_maxSpeed;         /**< \brief in RPM, always positive. Direction will be added in engine SWC */
    CAR_direction_t m_direction;
    CAR_error_t     m_error;
} DRIVINGPARAM_data_t;


#define DRIVINGPARAM_INIT_DATA ((DRIVINGPARAM_data_t){0, DIRECTION_NEUTRAL, ERROR_ALLOK})


/**
 * Default IN driver API - may be deleted if not required
 * \param DRIVINGPARAM_data_t *const data : [OUT] scaled data read from the driver
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t DRIVINGPARAM_driverIn(DRIVINGPARAM_data_t *const data);


/**
 * Default IN driver API - may be deleted if not required
 * \param const DRIVINGPARAM_data_t  *const data : [IN] signal data for the driver, will be scaled in this function
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t DRIVINGPARAM_driverOut(const DRIVINGPARAM_data_t  *const data);



#endif /* DRIVINGPARAM_TYPE_H_ */

