/*
 * drivingParam_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */


#include "project.h"
#include "global.h"
#include "ssd1306.h"

#include "logging.h"

#include "drivingParam_type.h"
#include "rte_signalpool.h"
#include "config.h"

/*****************************************************************************************
 *************** Port Wrapper Implementation for DRIVINGPARAM signal                     **************************
 *****************************************************************************************/


/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t DRIVINGPARAM_driverIn(DRIVINGPARAM_data_t *const data)
{


	//Read data from the MCAL driver

	//Scale it to the application type

	return RC_SUCCESS;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t DRIVINGPARAM_driverOut(const DRIVINGPARAM_data_t  *const data)
{
    
#if OLED == ACTIVE

    if (ERROR_ALLOK != data->m_error)
    {
        switch (data->m_error)
        {
            case ERROR_PEDAL    : SSD1306_write_line(1,"ERROR: PEDAL"); break;
            case ERROR_LOGIC    : SSD1306_write_line(1,"ERROR: LOGIC"); break;
            case ERROR_ACTOR    : SSD1306_write_line(1,"ERROR: ACTOR"); break;
            case ERROR_SYSTEM    : SSD1306_write_line(1,"ERROR: SYSTEM"); break;
        }
        
        SSD1306_write_line(2,"Engine Stopped");
        
        //No additional output required;
        return RC_ERROR;
    }

        
    
    //A bit hacky, might also be placed in a CCD
    CARSTATE_data_t state = RTE_CARSTATE_get(&SO_CARSTATE_signal);
    switch (state.m_state)
    {
        case ISIDLE                 : SSD1306_write_line(1,"IDLE"); break;
        case ISPRESSEDIGNITION      : SSD1306_write_line(1,"IGNITION"); break;
        case ISIGNITIONSELFTEST_1   : SSD1306_write_line(1,"SELFTEST 1"); break;
        case ISIGNITIONSELFTEST_2   : SSD1306_write_line(1,"SELFTEST 2"); break;
        case ISDRIVING              : SSD1306_write_line(1,"DRIVE"); break;
        case ISBRAKING              : SSD1306_write_line(1,"BRAKING"); break;
        case ISERROR                : SSD1306_write_line(1,"ERROR"); break;
    }
    
    //LOG_I("DRIVINGPARAM_driverOut", "DIrection %d", data->m_direction);
    //Hacky, but it seems that driver requires it
    CyDelay(1);
    switch (data->m_direction)
    {
        case DIRECTION_NEUTRAL      : SSD1306_write_line(2," Engine:   Stopped"); break;
        case DIRECTION_FORWARD      : SSD1306_write_line(2," Engine:   Forward"); break;
        case DIRECTION_REVERSE      : SSD1306_write_line(2," Engine:   Reverse"); break;
    }
    
    CyDelay(1);
    char sspeed[20];
    sprintf(sspeed," MaxSpeed: %d RPM", data->m_maxSpeed);
    
    SSD1306_write_line(3,sspeed);
    
  
#endif

	return RC_SUCCESS;
}
