/*
 * led_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */


#include "project.h"
#include "global.h"

#include "led_type.h"
#include "logging.h"

#include "config.h"

/*****************************************************************************************
 *************** Port Wrapper Implementation for LED signal     **************************
 *****************************************************************************************/


/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t LED_driverIn(LED_data_t *const data)
{


	//Read data from the MCAL driver

	//Scale it to the application type

	return RC_SUCCESS;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t LED_driverOut(const LED_data_t  *const data)
{

    //LOG_I("LED_driverOut","");
#if LED == ACTIVE

	//Scale application data to drive format
    if (LED_TOGGLE == data->m_led_1)
    {
        LED_Toggle(LED_1);
    }
    else
    {
        LED_Set(LED_1, data->m_led_1);
    }
    
    if (LED_TOGGLE == data->m_led_2)
    {
        LED_Toggle(LED_2);
    }
    else
    {
        LED_Set(LED_2, data->m_led_2);
    }

    if (LED_TOGGLE == data->m_led_3)
    {
        LED_Toggle(LED_3);
    }
    else
    {
        LED_Set(LED_3, data->m_led_3);
    }

    if (LED_TOGGLE == data->m_led_4)
    {
        LED_Toggle(LED_4);
    }
    else
    {
        LED_Set(LED_4, data->m_led_4);
    }

#endif

	return RC_SUCCESS;
}
