/*
 * led_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */



#ifndef LED_TYPE_H_
#define LED_TYPE_H_

#include "global.h"
#include "led.h"

/*****************************************************************************************
 *************** Type Definition for LED signal                     **************************
 *****************************************************************************************/



typedef struct
{
    LED_mode_t m_led_1;     /**< \brief operational mode of the LED 1*/
    LED_mode_t m_led_2;     /**< \brief operational mode of the LED 2*/
    LED_mode_t m_led_3;     /**< \brief operational mode of the LED 3*/
    LED_mode_t m_led_4;     /**< \brief operational mode of the LED 4*/
} LED_data_t;

#define LED_INIT_DATA ((LED_data_t){LED_OFF, LED_OFF, LED_OFF, LED_OFF})


/**
 * Default IN driver API - may be deleted if not required
 * \param LED_data_t *const data : [OUT] scaled data read from the driver
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t LED_driverIn(LED_data_t *const data);


/**
 * Default IN driver API - may be deleted if not required
 * \param const LED_data_t  *const data : [IN] signal data for the driver, will be scaled in this function
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t LED_driverOut(const LED_data_t  *const data);



#endif /* LED_TYPE_H_ */

