/*
 * pedal_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */


#include "project.h"
#include "global.h"

#include "poti.h"
#include "logging.h"

#include "pedal_type.h"

/*****************************************************************************************
 ****************************** Pedal configuration   ************************************
 *****************************************************************************************/

    //Max ADC values for GND and Vdd signal on pin
    #define POTI_MIN_ADC            0       /**< \brief ADC range - min value */
    #define POTI_MAX_ADC            255     /**< \brief ADC range - max value */

    //Values indicating the valid range (caused by the diagnostic resistors)
    #define POTI_MIN_VALID_ADC      5      /**< \brief ADC error detection - min valid value */
    #define POTI_MAX_VALID_ADC      250     /**< \brief ADC error detection - max valid value */
    
    #define POTI_SUM_MIN            200     /**< \brief tolerance range for potentiometer sum value - min valid value */
    #define POTI_SUM_MAX            300     /**< \brief tolerance range for potentiometer sum value - max valid value */

    //Values indication the ramp direction of the signal
    #define POTI_1_RAMP            1    
    #define POTI_2_RAMP           -1

/*****************************************************************************************
 *************** Port Wrapper Implementation for PEDAL signal   **************************
 *****************************************************************************************/


/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t PEDAL_driverIn(PEDAL_data_t *const data)
{

  
	//Read data from the MCAL driver
    uint8_t poti_1, poti_2 = 0;
    RC_t result = RC_ERROR;
    
    //Channel 1
    result = POTI_ReadPosition(POTI_1, &poti_1);
    
    //Escalate driver error
    if (RC_SUCCESS != result) 
    {
        //Safe state
        data->m_value = 0; //will not be written to signal according to signal spec
        return result;
    }

    //Channel 2
    result = POTI_ReadPosition(POTI_2, &poti_2);
    
    //Escalate driver error
    if (RC_SUCCESS != result) 
    {
        //Safe state
        data->m_value = 0; //will not be written to signal according to signal spec
        return result;
    }
   
    //Check for short circuit against GND or VDD and broken link, using the resistor diagnostics
    if (poti_1 < POTI_MIN_VALID_ADC || 
        poti_2 < POTI_MIN_VALID_ADC ||
        poti_1 > POTI_MAX_VALID_ADC || 
        poti_2 > POTI_MAX_VALID_ADC )
    {
        data->m_value = 0;
        LOG_I("PEDAL_driverIn","range pot_1 %d pot_2 %d", poti_1, poti_2);
        return RC_ERROR_RANGE;
    }
    
    //Compare the 2 channels
    uint16_t sum = poti_1 + poti_2;
    if (sum < POTI_SUM_MIN || sum > POTI_SUM_MAX)
    {
        data->m_value = 0; // will not be written to signal according to signal spec
        LOG_I("PEDAL_driverIn","sum pot_1 %d pot_2 %d", poti_1, poti_2);
        return RC_ERROR_RANGE;
    }
        
	//Scale it to the application type    
    sint16_t value1 = (poti_1 - POTI_MIN_VALID_ADC) * 100 / (POTI_MAX_VALID_ADC - POTI_MIN_VALID_ADC);
    sint16_t value2 = ((255-poti_2) - POTI_MIN_VALID_ADC) * 100 / (POTI_MAX_VALID_ADC - POTI_MIN_VALID_ADC);

    
    sint16_t value = (value1 + value2) / 2;
    
    //check for valid resulting range
    if (value < 0) value = 0;
    if (value > 100) value = 100;
    
    //Write back to signal
    data->m_value = (uint8_t)value;

    //Debugging
    //LOG_I("PEDAL_driverIn","Ch1 : %d Ch2 : %d Scale: %d %d %d ",poti_1, poti_2, value1, value2, value);
    
	return RC_SUCCESS;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t PEDAL_driverOut(const PEDAL_data_t  *const data)
{


	//Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
}
