/*
 * speed_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */


#include "project.h"
#include "global.h"

#include "rte_activation.h"
#include "swc_engine.h"

#include "engine.h"

#include "speed_type.h"

/*****************************************************************************************
 *************** Port Wrapper Implementation for SPEED signal   **************************
 *****************************************************************************************/


/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t SPEED_driverIn(SPEED_data_t *const data)
{

	//Read data from the MCAL driver
    //Bit hacky - Get the ticktime of the runnable calling the driver for the correct calculation of the RPM
    uint16_t ticktime = RTE_getTickTime(RTE_cyclicActivationTable, RTE_cyclicActivation_size, ENGINE_setControlSpeed_run);
    
    sint16_t rpm = 0;
    RC_t result = ENG_GetSpeed(ENG_1,ticktime, &rpm);
    
    if (RC_SUCCESS != result)
    {
        return result;
    }

	//Scale it to the application type
    data->m_rpm = rpm;

	return RC_SUCCESS;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t SPEED_driverOut(const SPEED_data_t  *const data)
{


	//Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
}
