/*
 * uartprot_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */



#ifndef UARTPROT_TYPE_H_
#define UARTPROT_TYPE_H_

#include "global.h"
    
#include "ringbuffer.h"
#include "carstate_type.h"

/*****************************************************************************************
 *************** Type Definition for UARTPROT signal                     **************************
 *****************************************************************************************/

#define PROT_SIZERXBUF   100             /**< \brief Size of the UART reception buffer */
#define UARTPROT_SOP     'S'
#define UARTPROT_EOP1    0x0D
#define UARTPROT_EOP2    0x0E
    
/**
 * This data structure will contain all relevant data to be exchanged between the PSOC 2 (Control) and PSOC (1) Monitor controller
 */
typedef struct
{
    CAR_state_t     m_state;
    sint16_t        m_targetspeed;
    sint16_t        m_currentspeed;
} UARTPROT_data_t;

#define UARTPROT_INIT_DATA ((UARTPROT_data_t){0})


//We have to declare them external to make them visible for the isr and REMOTE_init
extern ringbuffer_hdl_t REMOTE_rx_buffer;
uint8_t REMOTE_uartBuffer[PROT_SIZERXBUF];  


/**
 * As the sender and receiver possibly do not start at the same time and we might suffer from boot-bytes, 
 * all bytes are ignored until we find the first true byte in the sequence
 * later on, this concept may also be used for resynchronisation
 * \param uint8_t data  : IN Byte currently received
 * \ return: TRUE if system is in sync, false otherwise
 */
boolean_t UARTPROT_SyncProtocol(uint8_t data);

/**
 * Default IN driver API - may be deleted if not required
 * \param UARTPROT_data_t *const data : [OUT] scaled data read from the driver
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t UARTPROT_driverIn(UARTPROT_data_t *const data);


/**
 * Default IN driver API - may be deleted if not required
 * \param const UARTPROT_data_t  *const data : [IN] signal data for the driver, will be scaled in this function
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t UARTPROT_driverOut(const UARTPROT_data_t  *const data);



#endif /* UARTPROT_TYPE_H_ */

