-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\PWM\PWM_ip_src_Triangle_Carrier.vhd
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip_src_Triangle_Carrier
-- Source Path: PWM/Triangle Carrier
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PWM_ip_src_Triangle_Carrier IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        PeriodCmp                         :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        Carrier                           :   OUT   std_logic_vector(12 DOWNTO 0);  -- ufix13
        Dir                               :   OUT   std_logic;
        Trigger_Pwm                       :   OUT   std_logic;
        Trigger_Pos_Vel                   :   OUT   std_logic
        );
END PWM_ip_src_Triangle_Carrier;


ARCHITECTURE rtl OF PWM_ip_src_Triangle_Carrier IS

  -- Component Declarations
  COMPONENT PWM_ip_src_Counter_Direction
    PORT( clk                             :   IN    std_logic;
          PeriodCmp                       :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          Carrier                         :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          Trigger                         :   OUT   std_logic;
          Dir                             :   OUT   std_logic;
          CmpHighMatch                    :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : PWM_ip_src_Counter_Direction
    USE ENTITY work.PWM_ip_src_Counter_Direction(rtl);

  -- Signals
  SIGNAL PeriodCmp_unsigned               : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL Minus_out1                       : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL Carrier_tmp                      : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL Dir_1                            : std_logic;
  SIGNAL CmpHighMatch                     : std_logic;
  SIGNAL Delay6_out1                      : std_logic := '0';
  SIGNAL HDL_Counter_count_step           : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL NOT_out1                         : std_logic;
  SIGNAL Equal_relop1                     : std_logic;

BEGIN
  u_Counter_Direction : PWM_ip_src_Counter_Direction
    PORT MAP( clk => clk,
              PeriodCmp => PeriodCmp,  -- ufix13
              Carrier => std_logic_vector(Carrier_tmp),  -- ufix13
              Trigger => Trigger_Pwm,
              Dir => Dir_1,
              CmpHighMatch => CmpHighMatch
              );

  PeriodCmp_unsigned <= unsigned(PeriodCmp);

  Minus_out1 <= PeriodCmp_unsigned - to_unsigned(16#0001#, 13);

  Delay6_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      Delay6_out1 <= CmpHighMatch;
    END IF;
  END PROCESS Delay6_process;


  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  HDL_Counter_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Carrier_tmp <= to_unsigned(16#0000#, 13);
      ELSE 
        IF Delay6_out1 = '1' THEN 
          Carrier_tmp <= Minus_out1;
        ELSE 
          Carrier_tmp <= Carrier_tmp + HDL_Counter_count_step;
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter_process;

  
  HDL_Counter_count_step <= to_unsigned(16#0001#, 13) WHEN Dir_1 = '1' ELSE
      to_unsigned(16#1FFF#, 13);

  Carrier <= std_logic_vector(Carrier_tmp);

  NOT_out1 <=  NOT Dir_1;

  
  Equal_relop1 <= '1' WHEN Carrier_tmp = to_unsigned(16#0400#, 13) ELSE
      '0';

  Trigger_Pos_Vel <= NOT_out1 AND Equal_relop1;

  Dir <= Dir_1;

END rtl;

