-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\PWM\PWM_ip_src_PWM.vhd
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1.5625e-08
-- Target subsystem base rate: 1.5625e-08
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip_src_PWM
-- Source Path: PWM
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.PWM_ip_src_PWM_pkg.ALL;

ENTITY PWM_ip_src_PWM IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dead_time                         :   IN    std_logic_vector(6 DOWNTO 0);  -- ufix7
        enable                            :   IN    std_logic;
        period_compare                    :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        pwm_compare_uvw_0                 :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        pwm_compare_uvw_1                 :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        pwm_compare_uvw_2                 :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        pwm_select_dead_time_calc         :   IN    std_logic;
        trigger_pwm                       :   OUT   std_logic;
        trigger_pos_vel                   :   OUT   std_logic;
        pwm_uvw_high_0                    :   OUT   std_logic;  -- boolean
        pwm_uvw_high_1                    :   OUT   std_logic;  -- boolean
        pwm_uvw_high_2                    :   OUT   std_logic;  -- boolean
        pwm_uvw_low_0                     :   OUT   std_logic;  -- boolean
        pwm_uvw_low_1                     :   OUT   std_logic;  -- boolean
        pwm_uvw_low_2                     :   OUT   std_logic;  -- boolean
        carrier_dir                       :   OUT   std_logic;
        carrier                           :   OUT   std_logic_vector(12 DOWNTO 0);  -- ufix13
        sample_time                       :   OUT   std_logic_vector(12 DOWNTO 0)  -- ufix13
        );
END PWM_ip_src_PWM;


ARCHITECTURE rtl OF PWM_ip_src_PWM IS

  -- Component Declarations
  COMPONENT PWM_ip_src_Triangle_Carrier
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          PeriodCmp                       :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          Carrier                         :   OUT   std_logic_vector(12 DOWNTO 0);  -- ufix13
          Dir                             :   OUT   std_logic;
          Trigger_Pwm                     :   OUT   std_logic;
          Trigger_Pos_Vel                 :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT PWM_ip_src_PWM_with_deadtime
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          pwm_compare_uvw                 :   IN    vector_of_std_logic_vector13(0 TO 2);  -- ufix13 [3]
          carrier                         :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          dead_time                       :   IN    std_logic_vector(6 DOWNTO 0);  -- ufix7
          pwm_select_dead_time_calc       :   IN    std_logic;
          pwm_high_low                    :   OUT   std_logic_vector(0 TO 5)  -- boolean [6]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : PWM_ip_src_Triangle_Carrier
    USE ENTITY work.PWM_ip_src_Triangle_Carrier(rtl);

  FOR ALL : PWM_ip_src_PWM_with_deadtime
    USE ENTITY work.PWM_ip_src_PWM_with_deadtime(rtl);

  -- Signals
  SIGNAL period_compare_unsigned          : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL Trigger                          : std_logic;
  SIGNAL S_H_period_compare_out1          : unsigned(12 DOWNTO 0) := to_unsigned(16#1F40#, 13);  -- ufix13
  SIGNAL carrier_1                        : std_logic_vector(12 DOWNTO 0);  -- ufix13
  SIGNAL Triangle_Carrier_out2            : std_logic;
  SIGNAL Trigger_Pos_Vel_1                : std_logic;
  SIGNAL Data_Type_Conversion5_out1       : std_logic;
  SIGNAL S_H_enable_out1                  : std_logic := '0';
  SIGNAL Delay7_out1                      : std_logic := '0';
  SIGNAL Delay8_out1                      : std_logic := '0';
  SIGNAL Constant_out1                    : std_logic;
  SIGNAL Constant_out1_scalarexpand       : std_logic_vector(0 TO 5);  -- boolean [6]
  SIGNAL pwm_compare_uvw                  : vector_of_unsigned13(0 TO 2);  -- ufix13 [3]
  SIGNAL S_H_pwm_compare_uvw_out1         : vector_of_unsigned13(0 TO 2) := (OTHERS => to_unsigned(16#0000#, 13));  -- ufix13 [3]
  SIGNAL Delay2_out1                      : vector_of_unsigned13(0 TO 2) := (OTHERS => to_unsigned(16#0000#, 13));  -- ufix13 [3]
  SIGNAL Delay2_out1_1                    : vector_of_std_logic_vector13(0 TO 2);  -- ufix13 [3]
  SIGNAL NOT1_out1                        : std_logic;
  SIGNAL dead_time_unsigned               : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL S_H_deadtime_out1                : unsigned(6 DOWNTO 0) := to_unsigned(16#00#, 7);  -- ufix7
  SIGNAL Data_Type_Conversion4_out1       : std_logic;
  SIGNAL S_H_select_deadtime_calc_out1    : std_logic := '0';
  SIGNAL pwm_high_low                     : std_logic_vector(0 TO 5);  -- boolean [6]
  SIGNAL Switch_out1                      : std_logic_vector(0 TO 5);  -- boolean [6]
  SIGNAL Delay1_out1                      : std_logic_vector(0 TO 5) := (OTHERS => '0');  -- boolean [6]
  SIGNAL pwm_uvw_high                     : std_logic_vector(0 TO 2);  -- boolean [3]
  SIGNAL pwm_uvw_low                      : std_logic_vector(0 TO 2);  -- boolean [3]
  SIGNAL carrier_unsigned                 : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL carrier_tmp                      : unsigned(12 DOWNTO 0) := to_unsigned(16#0000#, 13);  -- ufix13
  SIGNAL sample_time_tmp                  : unsigned(12 DOWNTO 0) := to_unsigned(16#0000#, 13);  -- ufix13

BEGIN
  -- Copy generated code to repository
  -- 
  -- Generate Code

  u_Triangle_Carrier : PWM_ip_src_Triangle_Carrier
    PORT MAP( clk => clk,
              reset => reset,
              PeriodCmp => std_logic_vector(S_H_period_compare_out1),  -- ufix13
              Carrier => carrier_1,  -- ufix13
              Dir => Triangle_Carrier_out2,
              Trigger_Pwm => Trigger,
              Trigger_Pos_Vel => Trigger_Pos_Vel_1
              );

  u_PWM_with_deadtime : PWM_ip_src_PWM_with_deadtime
    PORT MAP( clk => clk,
              reset => reset,
              pwm_compare_uvw => Delay2_out1_1,  -- ufix13 [3]
              carrier => carrier_1,  -- ufix13
              dead_time => std_logic_vector(S_H_deadtime_out1),  -- ufix7
              pwm_select_dead_time_calc => S_H_select_deadtime_calc_out1,
              pwm_high_low => pwm_high_low  -- boolean [6]
              );

  period_compare_unsigned <= unsigned(period_compare);

  S_H_period_compare_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF Trigger = '1' THEN
        S_H_period_compare_out1 <= period_compare_unsigned;
      END IF;
    END IF;
  END PROCESS S_H_period_compare_process;


  Delay3_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      trigger_pwm <= Trigger;
    END IF;
  END PROCESS Delay3_process;


  Delay9_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      trigger_pos_vel <= Trigger_Pos_Vel_1;
    END IF;
  END PROCESS Delay9_process;


  
  Data_Type_Conversion5_out1 <= '1' WHEN enable /= '0' ELSE
      '0';

  S_H_enable_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF Trigger = '1' THEN
        S_H_enable_out1 <= Data_Type_Conversion5_out1;
      END IF;
    END IF;
  END PROCESS S_H_enable_process;


  Delay7_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      Delay7_out1 <= S_H_enable_out1;
    END IF;
  END PROCESS Delay7_process;


  Delay8_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      Delay8_out1 <= Delay7_out1;
    END IF;
  END PROCESS Delay8_process;


  Constant_out1 <= '0';

  Constant_out1_scalarexpand(0) <= Constant_out1;
  Constant_out1_scalarexpand(1) <= Constant_out1;
  Constant_out1_scalarexpand(2) <= Constant_out1;
  Constant_out1_scalarexpand(3) <= Constant_out1;
  Constant_out1_scalarexpand(4) <= Constant_out1;
  Constant_out1_scalarexpand(5) <= Constant_out1;

  pwm_compare_uvw(0) <= unsigned(pwm_compare_uvw_0);
  pwm_compare_uvw(1) <= unsigned(pwm_compare_uvw_1);
  pwm_compare_uvw(2) <= unsigned(pwm_compare_uvw_2);

  S_H_pwm_compare_uvw_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF Trigger = '1' THEN
        S_H_pwm_compare_uvw_out1 <= pwm_compare_uvw;
      END IF;
    END IF;
  END PROCESS S_H_pwm_compare_uvw_process;


  Delay2_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      Delay2_out1 <= S_H_pwm_compare_uvw_out1;
    END IF;
  END PROCESS Delay2_process;


  outputgen: FOR k IN 0 TO 2 GENERATE
    Delay2_out1_1(k) <= std_logic_vector(Delay2_out1(k));
  END GENERATE;

  NOT1_out1 <=  NOT S_H_enable_out1;

  dead_time_unsigned <= unsigned(dead_time);

  S_H_deadtime_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF NOT1_out1 = '1' THEN
        S_H_deadtime_out1 <= dead_time_unsigned;
      END IF;
    END IF;
  END PROCESS S_H_deadtime_process;


  
  Data_Type_Conversion4_out1 <= '1' WHEN pwm_select_dead_time_calc /= '0' ELSE
      '0';

  S_H_select_deadtime_calc_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF NOT1_out1 = '1' THEN
        S_H_select_deadtime_calc_out1 <= Data_Type_Conversion4_out1;
      END IF;
    END IF;
  END PROCESS S_H_select_deadtime_calc_process;


  
  Switch_out1 <= Constant_out1_scalarexpand WHEN Delay8_out1 = '0' ELSE
      pwm_high_low;

  Delay1_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      Delay1_out1 <= Switch_out1;
    END IF;
  END PROCESS Delay1_process;


  pwm_uvw_high(0) <= Delay1_out1(0);
  pwm_uvw_high(1) <= Delay1_out1(1);
  pwm_uvw_high(2) <= Delay1_out1(2);

  pwm_uvw_high_0 <= pwm_uvw_high(0);

  pwm_uvw_high_1 <= pwm_uvw_high(1);

  pwm_uvw_high_2 <= pwm_uvw_high(2);

  pwm_uvw_low(0) <= Delay1_out1(3);
  pwm_uvw_low(1) <= Delay1_out1(4);
  pwm_uvw_low(2) <= Delay1_out1(5);

  pwm_uvw_low_0 <= pwm_uvw_low(0);

  pwm_uvw_low_1 <= pwm_uvw_low(1);

  pwm_uvw_low_2 <= pwm_uvw_low(2);

  Delay5_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      carrier_dir <= Triangle_Carrier_out2;
    END IF;
  END PROCESS Delay5_process;


  carrier_unsigned <= unsigned(carrier_1);

  Delay6_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      carrier_tmp <= carrier_unsigned;
    END IF;
  END PROCESS Delay6_process;


  carrier <= std_logic_vector(carrier_tmp);

  Delay4_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      sample_time_tmp <= S_H_period_compare_out1;
    END IF;
  END PROCESS Delay4_process;


  sample_time <= std_logic_vector(sample_time_tmp);


END rtl;

