-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\PWM\PWM_ip_src_dead_time_compare.vhd
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip_src_dead_time_compare
-- Source Path: PWM/PWM with deadtime/dead_time_compare
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.PWM_ip_src_PWM_pkg.ALL;

ENTITY PWM_ip_src_dead_time_compare IS
  PORT( pwm_compare_uvw                   :   IN    vector_of_std_logic_vector13(0 TO 2);  -- ufix13 [3]
        dead_time                         :   IN    std_logic_vector(6 DOWNTO 0);  -- ufix7
        Carrier                           :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        PWM_UVW_DeadtimeSymmetrical       :   OUT   std_logic_vector(0 TO 5)  -- boolean [6]
        );
END PWM_ip_src_dead_time_compare;


ARCHITECTURE rtl OF PWM_ip_src_dead_time_compare IS

  -- Signals
  SIGNAL pwm_compare_uvw_unsigned         : vector_of_unsigned13(0 TO 2);  -- ufix13 [3]
  SIGNAL dead_time_unsigned               : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL Gain_cast                        : unsigned(13 DOWNTO 0);  -- ufix14_En7
  SIGNAL Gain_out1                        : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL SubtractDeadtimeHalf_v           : signed(13 DOWNTO 0);  -- sfix14
  SIGNAL SubtractDeadtimeHalf_sub_cast    : vector_of_signed14(0 TO 2);  -- sfix14 [3]
  SIGNAL SubtractDeadtimeHalf_sub_temp    : vector_of_signed14(0 TO 2);  -- sfix14 [3]
  SIGNAL SubtractDeadtimeHalf_out1        : vector_of_unsigned13(0 TO 2);  -- ufix13 [3]
  SIGNAL SubtractDeadtimeHalf_out1_0      : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL Carrier_unsigned                 : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL GreaterThan1_relop1              : std_logic;
  SIGNAL SubtractDeadtimeHalf_out1_1      : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL GreaterThan1_relop2              : std_logic;
  SIGNAL SubtractDeadtimeHalf_out1_2      : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL GreaterThan1_relop3              : std_logic;
  SIGNAL PWM_H                            : std_logic_vector(0 TO 2);  -- boolean [3]
  SIGNAL AddDeadtimeHalf_v                : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL AddDeadtimeHalf_out1             : vector_of_unsigned13(0 TO 2);  -- ufix13 [3]
  SIGNAL AddDeadtimeHalf_out1_0           : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL GreaterThan2_relop1              : std_logic;
  SIGNAL AddDeadtimeHalf_out1_1           : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL GreaterThan2_relop2              : std_logic;
  SIGNAL AddDeadtimeHalf_out1_2           : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL GreaterThan2_relop3              : std_logic;
  SIGNAL PWM_L                            : std_logic_vector(0 TO 2);  -- boolean [3]
  SIGNAL Mux2_out1                        : std_logic_vector(0 TO 5);  -- boolean [6]

BEGIN
  outputgen: FOR k IN 0 TO 2 GENERATE
    pwm_compare_uvw_unsigned(k) <= unsigned(pwm_compare_uvw(k));
  END GENERATE;

  dead_time_unsigned <= unsigned(dead_time);

  Gain_cast <= resize(dead_time_unsigned & "000000", 14);
  Gain_out1 <= Gain_cast(13 DOWNTO 7);

  SubtractDeadtimeHalf_v <= signed(resize(Gain_out1, 14));

  SubtractDeadtimeHalf_out1_gen: FOR t_0 IN 0 TO 2 GENERATE
    SubtractDeadtimeHalf_sub_cast(t_0) <= signed(resize(pwm_compare_uvw_unsigned(t_0), 14));
    SubtractDeadtimeHalf_sub_temp(t_0) <= SubtractDeadtimeHalf_sub_cast(t_0) - SubtractDeadtimeHalf_v;
    
    SubtractDeadtimeHalf_out1(t_0) <= "0000000000000" WHEN SubtractDeadtimeHalf_sub_temp(t_0)(13) = '1' ELSE
        unsigned(SubtractDeadtimeHalf_sub_temp(t_0)(12 DOWNTO 0));
  END GENERATE SubtractDeadtimeHalf_out1_gen;


  SubtractDeadtimeHalf_out1_0 <= SubtractDeadtimeHalf_out1(0);

  Carrier_unsigned <= unsigned(Carrier);

  
  GreaterThan1_relop1 <= '1' WHEN SubtractDeadtimeHalf_out1_0 > Carrier_unsigned ELSE
      '0';

  SubtractDeadtimeHalf_out1_1 <= SubtractDeadtimeHalf_out1(1);

  
  GreaterThan1_relop2 <= '1' WHEN SubtractDeadtimeHalf_out1_1 > Carrier_unsigned ELSE
      '0';

  SubtractDeadtimeHalf_out1_2 <= SubtractDeadtimeHalf_out1(2);

  
  GreaterThan1_relop3 <= '1' WHEN SubtractDeadtimeHalf_out1_2 > Carrier_unsigned ELSE
      '0';

  PWM_H(0) <= GreaterThan1_relop1;
  PWM_H(1) <= GreaterThan1_relop2;
  PWM_H(2) <= GreaterThan1_relop3;

  AddDeadtimeHalf_v <= resize(Gain_out1, 14);

  AddDeadtimeHalf_out1_gen: FOR t_01 IN 0 TO 2 GENERATE
    AddDeadtimeHalf_out1(t_01) <= resize(resize(pwm_compare_uvw_unsigned(t_01), 14) + AddDeadtimeHalf_v, 13);
  END GENERATE AddDeadtimeHalf_out1_gen;


  AddDeadtimeHalf_out1_0 <= AddDeadtimeHalf_out1(0);

  
  GreaterThan2_relop1 <= '1' WHEN AddDeadtimeHalf_out1_0 < Carrier_unsigned ELSE
      '0';

  AddDeadtimeHalf_out1_1 <= AddDeadtimeHalf_out1(1);

  
  GreaterThan2_relop2 <= '1' WHEN AddDeadtimeHalf_out1_1 < Carrier_unsigned ELSE
      '0';

  AddDeadtimeHalf_out1_2 <= AddDeadtimeHalf_out1(2);

  
  GreaterThan2_relop3 <= '1' WHEN AddDeadtimeHalf_out1_2 < Carrier_unsigned ELSE
      '0';

  PWM_L(0) <= GreaterThan2_relop1;
  PWM_L(1) <= GreaterThan2_relop2;
  PWM_L(2) <= GreaterThan2_relop3;

  Mux2_out1(0) <= PWM_H(0);
  Mux2_out1(1) <= PWM_H(1);
  Mux2_out1(2) <= PWM_H(2);
  Mux2_out1(3) <= PWM_L(0);
  Mux2_out1(4) <= PWM_L(1);
  Mux2_out1(5) <= PWM_L(2);

  PWM_UVW_DeadtimeSymmetrical <= Mux2_out1;

END rtl;

