-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\PWM\PWM_ip_src_PWM_pkg.vhd
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE PWM_ip_src_PWM_pkg IS
  TYPE vector_of_std_logic_vector13 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(12 DOWNTO 0);
  TYPE vector_of_signed14 IS ARRAY (NATURAL RANGE <>) OF signed(13 DOWNTO 0);
  TYPE vector_of_unsigned13 IS ARRAY (NATURAL RANGE <>) OF unsigned(12 DOWNTO 0);
END PWM_ip_src_PWM_pkg;

