-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\PWM\PWM_ip_src_Counter_Direction.vhd
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip_src_Counter_Direction
-- Source Path: PWM/Triangle Carrier/Counter Direction
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PWM_ip_src_Counter_Direction IS
  PORT( clk                               :   IN    std_logic;
        PeriodCmp                         :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        Carrier                           :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        Trigger                           :   OUT   std_logic;
        Dir                               :   OUT   std_logic;
        CmpHighMatch                      :   OUT   std_logic
        );
END PWM_ip_src_Counter_Direction;


ARCHITECTURE rtl OF PWM_ip_src_Counter_Direction IS

  -- Signals
  SIGNAL Carrier_unsigned                 : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL CmpLow                           : std_logic;
  SIGNAL PeriodCmp_unsigned               : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL Minus_out1                       : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL Equal_relop1                     : std_logic;
  SIGNAL CmpHigh                          : std_logic;
  SIGNAL Dir_1                            : std_logic := '1';
  SIGNAL CmpHighMatch_1                   : std_logic;
  SIGNAL Trigger_1                        : std_logic;
  SIGNAL CmpLowMatch                      : std_logic;
  SIGNAL AND1_out1                        : std_logic;

BEGIN
  Carrier_unsigned <= unsigned(Carrier);

  
  CmpLow <= '1' WHEN Carrier_unsigned = to_unsigned(16#0001#, 13) ELSE
      '0';

  PeriodCmp_unsigned <= unsigned(PeriodCmp);

  Minus_out1 <= PeriodCmp_unsigned - to_unsigned(16#0001#, 13);

  
  Equal_relop1 <= '1' WHEN Carrier_unsigned = Minus_out1 ELSE
      '0';

  CmpHigh <= Equal_relop1;

  CmpHighMatch_1 <= Dir_1 AND CmpHigh;

  Unit_Delay_Enabled_Synchronous_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF Trigger_1 = '1' THEN
        Dir_1 <= CmpLowMatch;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous_process;


  AND1_out1 <=  NOT Dir_1;

  CmpLowMatch <= AND1_out1 AND CmpLow;

  Trigger_1 <= CmpLowMatch OR CmpHighMatch_1;

  Trigger <= Trigger_1;

  Dir <= Dir_1;

  CmpHighMatch <= CmpHighMatch_1;

END rtl;

