-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\PWM\PWM_ip_dut.vhd
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip_dut
-- Source Path: PWM_ip/PWM_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PWM_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dead_time                         :   IN    std_logic_vector(6 DOWNTO 0);  -- ufix7
        enable                            :   IN    std_logic;  -- ufix1
        period_compare                    :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        pwm_compare_uvw_0                 :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        pwm_compare_uvw_1                 :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        pwm_compare_uvw_2                 :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        pwm_select_dead_time_calc         :   IN    std_logic;  -- ufix1
        trigger_pwm                       :   OUT   std_logic;  -- ufix1
        trigger_pos_vel                   :   OUT   std_logic;  -- ufix1
        pwm_uvw_high_0                    :   OUT   std_logic;  -- ufix1
        pwm_uvw_high_1                    :   OUT   std_logic;  -- ufix1
        pwm_uvw_high_2                    :   OUT   std_logic;  -- ufix1
        pwm_uvw_low_0                     :   OUT   std_logic;  -- ufix1
        pwm_uvw_low_1                     :   OUT   std_logic;  -- ufix1
        pwm_uvw_low_2                     :   OUT   std_logic;  -- ufix1
        carrier_dir                       :   OUT   std_logic;  -- ufix1
        carrier                           :   OUT   std_logic_vector(12 DOWNTO 0);  -- ufix13
        sample_time                       :   OUT   std_logic_vector(12 DOWNTO 0)  -- ufix13
        );
END PWM_ip_dut;


ARCHITECTURE rtl OF PWM_ip_dut IS

  -- Component Declarations
  COMPONENT PWM_ip_src_PWM
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          dead_time                       :   IN    std_logic_vector(6 DOWNTO 0);  -- ufix7
          enable                          :   IN    std_logic;  -- ufix1
          period_compare                  :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          pwm_compare_uvw_0               :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          pwm_compare_uvw_1               :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          pwm_compare_uvw_2               :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          pwm_select_dead_time_calc       :   IN    std_logic;  -- ufix1
          trigger_pwm                     :   OUT   std_logic;  -- ufix1
          trigger_pos_vel                 :   OUT   std_logic;  -- ufix1
          pwm_uvw_high_0                  :   OUT   std_logic;  -- ufix1
          pwm_uvw_high_1                  :   OUT   std_logic;  -- ufix1
          pwm_uvw_high_2                  :   OUT   std_logic;  -- ufix1
          pwm_uvw_low_0                   :   OUT   std_logic;  -- ufix1
          pwm_uvw_low_1                   :   OUT   std_logic;  -- ufix1
          pwm_uvw_low_2                   :   OUT   std_logic;  -- ufix1
          carrier_dir                     :   OUT   std_logic;  -- ufix1
          carrier                         :   OUT   std_logic_vector(12 DOWNTO 0);  -- ufix13
          sample_time                     :   OUT   std_logic_vector(12 DOWNTO 0)  -- ufix13
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : PWM_ip_src_PWM
    USE ENTITY work.PWM_ip_src_PWM(rtl);

  -- Signals
  SIGNAL enable_sig                       : std_logic;  -- ufix1
  SIGNAL pwm_select_dead_time_calc_sig    : std_logic;  -- ufix1
  SIGNAL trigger_pwm_sig                  : std_logic;  -- ufix1
  SIGNAL trigger_pos_vel_sig              : std_logic;  -- ufix1
  SIGNAL pwm_uvw_high_0_sig               : std_logic;  -- ufix1
  SIGNAL pwm_uvw_high_1_sig               : std_logic;  -- ufix1
  SIGNAL pwm_uvw_high_2_sig               : std_logic;  -- ufix1
  SIGNAL pwm_uvw_low_0_sig                : std_logic;  -- ufix1
  SIGNAL pwm_uvw_low_1_sig                : std_logic;  -- ufix1
  SIGNAL pwm_uvw_low_2_sig                : std_logic;  -- ufix1
  SIGNAL carrier_dir_sig                  : std_logic;  -- ufix1
  SIGNAL carrier_sig                      : std_logic_vector(12 DOWNTO 0);  -- ufix13
  SIGNAL sample_time_sig                  : std_logic_vector(12 DOWNTO 0);  -- ufix13

BEGIN
  u_PWM_ip_src_PWM : PWM_ip_src_PWM
    PORT MAP( clk => clk,
              reset => reset,
              dead_time => dead_time,  -- ufix7
              enable => enable_sig,  -- ufix1
              period_compare => period_compare,  -- ufix13
              pwm_compare_uvw_0 => pwm_compare_uvw_0,  -- ufix13
              pwm_compare_uvw_1 => pwm_compare_uvw_1,  -- ufix13
              pwm_compare_uvw_2 => pwm_compare_uvw_2,  -- ufix13
              pwm_select_dead_time_calc => pwm_select_dead_time_calc_sig,  -- ufix1
              trigger_pwm => trigger_pwm_sig,  -- ufix1
              trigger_pos_vel => trigger_pos_vel_sig,  -- ufix1
              pwm_uvw_high_0 => pwm_uvw_high_0_sig,  -- ufix1
              pwm_uvw_high_1 => pwm_uvw_high_1_sig,  -- ufix1
              pwm_uvw_high_2 => pwm_uvw_high_2_sig,  -- ufix1
              pwm_uvw_low_0 => pwm_uvw_low_0_sig,  -- ufix1
              pwm_uvw_low_1 => pwm_uvw_low_1_sig,  -- ufix1
              pwm_uvw_low_2 => pwm_uvw_low_2_sig,  -- ufix1
              carrier_dir => carrier_dir_sig,  -- ufix1
              carrier => carrier_sig,  -- ufix13
              sample_time => sample_time_sig  -- ufix13
              );

  enable_sig <= enable;

  pwm_select_dead_time_calc_sig <= pwm_select_dead_time_calc;

  trigger_pwm <= trigger_pwm_sig;

  trigger_pos_vel <= trigger_pos_vel_sig;

  pwm_uvw_high_0 <= pwm_uvw_high_0_sig;

  pwm_uvw_high_1 <= pwm_uvw_high_1_sig;

  pwm_uvw_high_2 <= pwm_uvw_high_2_sig;

  pwm_uvw_low_0 <= pwm_uvw_low_0_sig;

  pwm_uvw_low_1 <= pwm_uvw_low_1_sig;

  pwm_uvw_low_2 <= pwm_uvw_low_2_sig;

  carrier_dir <= carrier_dir_sig;

  carrier <= carrier_sig;

  sample_time <= sample_time_sig;

END rtl;

