-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\PWM\PWM_ip.vhd
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: -1
-- Target subsystem base rate: -1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip
-- Source Path: PWM_ip
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PWM_ip IS
  PORT( IPCORE_CLK                        :   IN    std_logic;  -- ufix1
        IPCORE_RESETN                     :   IN    std_logic;  -- ufix1
        dead_time                         :   IN    std_logic_vector(6 DOWNTO 0);  -- ufix7
        enable                            :   IN    std_logic;  -- ufix1
        period_compare                    :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        pwm_compare_uvw_0                 :   IN    std_logic_vector(38 DOWNTO 0);  -- ufix39
        pwm_select_dead_time_calc         :   IN    std_logic;  -- ufix1
        trigger_pwm                       :   OUT   std_logic;  -- ufix1
        trigger_pos_vel                   :   OUT   std_logic;  -- ufix1
        pwm_uvw_high_0                    :   OUT   std_logic_vector(2 DOWNTO 0);  -- ufix3
        pwm_uvw_low_0                     :   OUT   std_logic_vector(2 DOWNTO 0);  -- ufix3
        carrier_dir                       :   OUT   std_logic;  -- ufix1
        carrier                           :   OUT   std_logic_vector(12 DOWNTO 0);  -- ufix13
        sample_time                       :   OUT   std_logic_vector(12 DOWNTO 0)  -- ufix13
        );
END PWM_ip;


ARCHITECTURE rtl OF PWM_ip IS

  -- Component Declarations
  COMPONENT PWM_ip_reset_sync
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset_in                        :   IN    std_logic;  -- ufix1
          reset_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT PWM_ip_dut
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset                           :   IN    std_logic;
          dead_time                       :   IN    std_logic_vector(6 DOWNTO 0);  -- ufix7
          enable                          :   IN    std_logic;  -- ufix1
          period_compare                  :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          pwm_compare_uvw_0               :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          pwm_compare_uvw_1               :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          pwm_compare_uvw_2               :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          pwm_select_dead_time_calc       :   IN    std_logic;  -- ufix1
          trigger_pwm                     :   OUT   std_logic;  -- ufix1
          trigger_pos_vel                 :   OUT   std_logic;  -- ufix1
          pwm_uvw_high_0                  :   OUT   std_logic;  -- ufix1
          pwm_uvw_high_1                  :   OUT   std_logic;  -- ufix1
          pwm_uvw_high_2                  :   OUT   std_logic;  -- ufix1
          pwm_uvw_low_0                   :   OUT   std_logic;  -- ufix1
          pwm_uvw_low_1                   :   OUT   std_logic;  -- ufix1
          pwm_uvw_low_2                   :   OUT   std_logic;  -- ufix1
          carrier_dir                     :   OUT   std_logic;  -- ufix1
          carrier                         :   OUT   std_logic_vector(12 DOWNTO 0);  -- ufix13
          sample_time                     :   OUT   std_logic_vector(12 DOWNTO 0)  -- ufix13
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : PWM_ip_reset_sync
    USE ENTITY work.PWM_ip_reset_sync(rtl);

  FOR ALL : PWM_ip_dut
    USE ENTITY work.PWM_ip_dut(rtl);

  -- Signals
  SIGNAL reset                            : std_logic;
  SIGNAL pwm_compare_uvw_0_unsigned       : unsigned(38 DOWNTO 0);  -- ufix39
  SIGNAL pwm_compare_uvw_0_slice          : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL pwm_compare_uvw_0_slice_1        : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL pwm_compare_uvw_0_slice_2        : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL reset_cm                         : std_logic;  -- ufix1
  SIGNAL trigger_pwm_sig                  : std_logic;  -- ufix1
  SIGNAL trigger_pos_vel_sig              : std_logic;  -- ufix1
  SIGNAL pwm_uvw_high_0_sig               : std_logic;  -- ufix1
  SIGNAL pwm_uvw_high_1_sig               : std_logic;  -- ufix1
  SIGNAL pwm_uvw_high_2_sig               : std_logic;  -- ufix1
  SIGNAL pwm_uvw_low_0_sig                : std_logic;  -- ufix1
  SIGNAL pwm_uvw_low_1_sig                : std_logic;  -- ufix1
  SIGNAL pwm_uvw_low_2_sig                : std_logic;  -- ufix1
  SIGNAL carrier_dir_sig                  : std_logic;  -- ufix1
  SIGNAL carrier_sig                      : std_logic_vector(12 DOWNTO 0);  -- ufix13
  SIGNAL sample_time_sig                  : std_logic_vector(12 DOWNTO 0);  -- ufix13
  SIGNAL pwm_uvw_high_0_tmp               : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL pwm_uvw_low_0_tmp                : unsigned(2 DOWNTO 0);  -- ufix3

BEGIN
  u_PWM_ip_reset_sync_inst : PWM_ip_reset_sync
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset_in => reset_cm,  -- ufix1
              reset_out => reset
              );

  u_PWM_ip_dut_inst : PWM_ip_dut
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset => reset,
              dead_time => dead_time,  -- ufix7
              enable => enable,  -- ufix1
              period_compare => period_compare,  -- ufix13
              pwm_compare_uvw_0 => std_logic_vector(pwm_compare_uvw_0_slice),  -- ufix13
              pwm_compare_uvw_1 => std_logic_vector(pwm_compare_uvw_0_slice_1),  -- ufix13
              pwm_compare_uvw_2 => std_logic_vector(pwm_compare_uvw_0_slice_2),  -- ufix13
              pwm_select_dead_time_calc => pwm_select_dead_time_calc,  -- ufix1
              trigger_pwm => trigger_pwm_sig,  -- ufix1
              trigger_pos_vel => trigger_pos_vel_sig,  -- ufix1
              pwm_uvw_high_0 => pwm_uvw_high_0_sig,  -- ufix1
              pwm_uvw_high_1 => pwm_uvw_high_1_sig,  -- ufix1
              pwm_uvw_high_2 => pwm_uvw_high_2_sig,  -- ufix1
              pwm_uvw_low_0 => pwm_uvw_low_0_sig,  -- ufix1
              pwm_uvw_low_1 => pwm_uvw_low_1_sig,  -- ufix1
              pwm_uvw_low_2 => pwm_uvw_low_2_sig,  -- ufix1
              carrier_dir => carrier_dir_sig,  -- ufix1
              carrier => carrier_sig,  -- ufix13
              sample_time => sample_time_sig  -- ufix13
              );

  pwm_compare_uvw_0_unsigned <= unsigned(pwm_compare_uvw_0);

  pwm_compare_uvw_0_slice <= pwm_compare_uvw_0_unsigned(12 DOWNTO 0);

  pwm_compare_uvw_0_slice_1 <= pwm_compare_uvw_0_unsigned(25 DOWNTO 13);

  pwm_compare_uvw_0_slice_2 <= pwm_compare_uvw_0_unsigned(38 DOWNTO 26);

  reset_cm <=  NOT IPCORE_RESETN;

  pwm_uvw_high_0_tmp <= unsigned'(pwm_uvw_high_2_sig & pwm_uvw_high_1_sig & pwm_uvw_high_0_sig);

  pwm_uvw_high_0 <= std_logic_vector(pwm_uvw_high_0_tmp);

  pwm_uvw_low_0_tmp <= unsigned'(pwm_uvw_low_2_sig & pwm_uvw_low_1_sig & pwm_uvw_low_0_sig);

  pwm_uvw_low_0 <= std_logic_vector(pwm_uvw_low_0_tmp);

  trigger_pwm <= trigger_pwm_sig;

  trigger_pos_vel <= trigger_pos_vel_sig;

  carrier_dir <= carrier_dir_sig;

  carrier <= carrier_sig;

  sample_time <= sample_time_sig;

END rtl;

