-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\PWM\PWM_ip_src_PWM_with_deadtime.vhd
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip_src_PWM_with_deadtime
-- Source Path: PWM/PWM with deadtime
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.PWM_ip_src_PWM_pkg.ALL;

ENTITY PWM_ip_src_PWM_with_deadtime IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        pwm_compare_uvw                   :   IN    vector_of_std_logic_vector13(0 TO 2);  -- ufix13 [3]
        carrier                           :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        dead_time                         :   IN    std_logic_vector(6 DOWNTO 0);  -- ufix7
        pwm_select_dead_time_calc         :   IN    std_logic;
        pwm_high_low                      :   OUT   std_logic_vector(0 TO 5)  -- boolean [6]
        );
END PWM_ip_src_PWM_with_deadtime;


ARCHITECTURE rtl OF PWM_ip_src_PWM_with_deadtime IS

  -- Component Declarations
  COMPONENT PWM_ip_src_dead_time_counter_foreach
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          pwm_in                          :   IN    std_logic;
          DeadTime                        :   IN    std_logic_vector(6 DOWNTO 0);  -- ufix7
          pwm_out                         :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT PWM_ip_src_dead_time_compare
    PORT( pwm_compare_uvw                 :   IN    vector_of_std_logic_vector13(0 TO 2);  -- ufix13 [3]
          dead_time                       :   IN    std_logic_vector(6 DOWNTO 0);  -- ufix7
          Carrier                         :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
          PWM_UVW_DeadtimeSymmetrical     :   OUT   std_logic_vector(0 TO 5)  -- boolean [6]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : PWM_ip_src_dead_time_counter_foreach
    USE ENTITY work.PWM_ip_src_dead_time_counter_foreach(rtl);

  FOR ALL : PWM_ip_src_dead_time_compare
    USE ENTITY work.PWM_ip_src_dead_time_compare(rtl);

  -- Signals
  SIGNAL pwm_compare_uvw_0                : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL carrier_unsigned                 : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL GreaterThan_relop1               : std_logic;
  SIGNAL pwm_compare_uvw_1                : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL GreaterThan_relop2               : std_logic;
  SIGNAL pwm_compare_uvw_2                : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL GreaterThan_relop3               : std_logic;
  SIGNAL pwm_high                         : std_logic_vector(0 TO 2);  -- boolean [3]
  SIGNAL pwm_high_0                       : std_logic;
  SIGNAL pwm_high_0_1                     : std_logic;
  SIGNAL pwm_high_1                       : std_logic;
  SIGNAL pwm_high_1_1                     : std_logic;
  SIGNAL pwm_high_2                       : std_logic;
  SIGNAL pwm_high_2_1                     : std_logic;
  SIGNAL pwm_inverted                     : std_logic_vector(0 TO 2);  -- boolean [3]
  SIGNAL Mux2_out1                        : std_logic_vector(0 TO 5);  -- boolean [6]
  SIGNAL PWM_WithRisingEdgeDelayDeadtime  : std_logic_vector(0 TO 5);  -- boolean [6]
  SIGNAL PWM_WithRisingEdgeDelayDeadtime_1 : std_logic_vector(0 TO 5);  -- boolean [6]
  SIGNAL PWM_WithSymmetricalDeadtime      : std_logic_vector(0 TO 5);  -- boolean [6]

BEGIN
  u_dead_time_compare : PWM_ip_src_dead_time_compare
    PORT MAP( pwm_compare_uvw => pwm_compare_uvw,  -- ufix13 [3]
              dead_time => dead_time,  -- ufix7
              Carrier => carrier,  -- ufix13
              PWM_UVW_DeadtimeSymmetrical => PWM_WithSymmetricalDeadtime  -- boolean [6]
              );

  pwm_compare_uvw_0 <= unsigned(pwm_compare_uvw(0));

  carrier_unsigned <= unsigned(carrier);

  
  GreaterThan_relop1 <= '1' WHEN pwm_compare_uvw_0 > carrier_unsigned ELSE
      '0';

  pwm_compare_uvw_1 <= unsigned(pwm_compare_uvw(1));

  
  GreaterThan_relop2 <= '1' WHEN pwm_compare_uvw_1 > carrier_unsigned ELSE
      '0';

  pwm_compare_uvw_2 <= unsigned(pwm_compare_uvw(2));

  
  GreaterThan_relop3 <= '1' WHEN pwm_compare_uvw_2 > carrier_unsigned ELSE
      '0';

  pwm_high(0) <= GreaterThan_relop1;
  pwm_high(1) <= GreaterThan_relop2;
  pwm_high(2) <= GreaterThan_relop3;

  pwm_high_0 <= pwm_high(0);

  pwm_high_0_1 <=  NOT pwm_high_0;

  pwm_high_1 <= pwm_high(1);

  pwm_high_1_1 <=  NOT pwm_high_1;

  pwm_high_2 <= pwm_high(2);

  pwm_high_2_1 <=  NOT pwm_high_2;

  pwm_inverted(0) <= pwm_high_0_1;
  pwm_inverted(1) <= pwm_high_1_1;
  pwm_inverted(2) <= pwm_high_2_1;

  Mux2_out1(0) <= pwm_inverted(0);
  Mux2_out1(1) <= pwm_inverted(1);
  Mux2_out1(2) <= pwm_inverted(2);
  Mux2_out1(3) <= pwm_high(0);
  Mux2_out1(4) <= pwm_high(1);
  Mux2_out1(5) <= pwm_high(2);

  GEN_LABEL: FOR k IN 0 TO 5 GENERATE
    u_dead_time_counter_foreach : PWM_ip_src_dead_time_counter_foreach
      PORT MAP( clk => clk,
                reset => reset,
                pwm_in => Mux2_out1(k),
                DeadTime => dead_time,  -- ufix7
                pwm_out => PWM_WithRisingEdgeDelayDeadtime(k)
                );
  END GENERATE;

  PWM_WithRisingEdgeDelayDeadtime_1 <= PWM_WithRisingEdgeDelayDeadtime;

  
  pwm_high_low <= PWM_WithRisingEdgeDelayDeadtime_1 WHEN pwm_select_dead_time_calc = '0' ELSE
      PWM_WithSymmetricalDeadtime;

END rtl;

