-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\PWM\PWM_ip_src_dead_time_counter_foreach.vhd
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_ip_src_dead_time_counter_foreach
-- Source Path: PWM/PWM with deadtime/dead_time_counter_foreach
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PWM_ip_src_dead_time_counter_foreach IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        pwm_in                            :   IN    std_logic;
        DeadTime                          :   IN    std_logic_vector(6 DOWNTO 0);  -- ufix7
        pwm_out                           :   OUT   std_logic
        );
END PWM_ip_src_dead_time_counter_foreach;


ARCHITECTURE rtl OF PWM_ip_src_dead_time_counter_foreach IS

  -- Signals
  SIGNAL DeadTime_unsigned                : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL Equal_relop1                     : std_logic;
  SIGNAL HDL_Counter_out1                 : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL NOT1_out1                        : std_logic;

BEGIN
  DeadTime_unsigned <= unsigned(DeadTime);

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  HDL_Counter_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        HDL_Counter_out1 <= to_unsigned(16#00#, 7);
      ELSE 
        IF pwm_in = '1' THEN 
          HDL_Counter_out1 <= to_unsigned(16#00#, 7);
        ELSIF Equal_relop1 = '1' THEN 
          HDL_Counter_out1 <= HDL_Counter_out1 + to_unsigned(16#01#, 7);
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter_process;


  
  Equal_relop1 <= '1' WHEN HDL_Counter_out1 /= DeadTime_unsigned ELSE
      '0';

  NOT1_out1 <=  NOT Equal_relop1;

  pwm_out <= NOT1_out1;

END rtl;

