/**************************************************
 ** Software Component SWC_HMI
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#include "rte.h"
#include "rte_signalpool.h"

#include "ssd1306.h"
#include "logging.h"

#include "swc_hmi.h"

/* Runnables */

void HMI_init_run()
{
    RC_t result = RC_ERROR;
    I2C_Start();
    result = SSD1306_init();
}

void HMI_display_run()
{
    //Write driving parameters to OLED
    RTE_DRIVINGPARAM_pushPort(&SO_DRIVINGPARAM_signal);

}

void HMI_injectError_run()
{
    //Read DIP register
    DIP_data_t dip = DIP_INIT_DATA;
    RTE_DIP_pullPort(&SO_DIP_signal);
    dip = RTE_DIP_get(&SO_DIP_signal);
    
    //LOG_I("HMI_injectError_run","DIP = %x", dip.byte);
    
    if (1 == dip.bit.d0)
    {
        //Error Injection shutdown
        LOG_E("HMI_injectError_run","Shutting system down");
        ShutdownOS(E_OK);
        
    }
    
    if (1 == dip.bit.d1)
    {
        //Error Injection slow down system
        LOG_E("HMI_injectError_run","Corrupted time base");
        CancelAlarm(alrm_10ms);
        SetRelAlarm(alrm_10ms,100,100);
        
    }
    
    if (1 == dip.bit.d2)
    {
        //Error Injection while 1
        LOG_E("HMI_injectError_run","while(1)");
        while(1){;}        
    }
    
    if (1 == dip.bit.d3)
    {
        //Error Injection wild pointer
        LOG_E("HMI_injectError_run","wild pointer violoating state variable");
        CARSTATE_data_t state;
        state.m_state = ISBRAKING;
        RTE_CARSTATE_set(&SO_CARSTATE_signal, state);
    }
    
    
    
}


