/**************************************************
 ** Software Component SWC_Engine
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#include "rte.h"
#include "rte_signalpool.h"
#include "rte_activation.h"

#include "logging.h"
#include "engine.h"
#include "error.h"

#include "swc_engine.h"


static uint8_t ENGINE__errorCounter = 0;

void ENGINE_init_run()
{
    RC_t result = ENG_Init();
}

void ENGINE_setControlSpeed_run()
{
    RC_t result = RC_SUCCESS;
    
    //Get the ticktime of this runnable
    uint16_t ticktime = RTE_getTickTime(RTE_cyclicActivationTable, RTE_cyclicActivation_size, ENGINE_setControlSpeed_run);
    
    //Get the targetspeed
    SPEED_data_t targetSpeed = SPEED_INIT_DATA;
    targetSpeed = RTE_SPEED_get(&SO_TARGETSPEED_signal);
    
    DRIVINGPARAM_data_t allowedTargetSpeed = RTE_DRIVINGPARAM_get(&SO_DRIVINGPARAM_signal);
    
    //LOG_I("ENGINE_setControlSpeed_run","Max allowed: %d",allowedTargetSpeed.m_maxSpeed);
    
    //Limit speed if required
    if (abs(targetSpeed.m_rpm) > allowedTargetSpeed.m_maxSpeed)
    {
        if (targetSpeed.m_rpm < 0) 
        {
            targetSpeed.m_rpm = - allowedTargetSpeed.m_maxSpeed; 
        }
        else
        {
            targetSpeed.m_rpm = allowedTargetSpeed.m_maxSpeed; 
        }
    }
    
    //Calculate the controlspeed 
    PWM_data_t controlSpeed = PWM_INIT_DATA;
    
    //And get the measured speed
    result = RTE_SPEED_pullPort(&SO_CURRENTSPEED_signal);
    if (RC_SUCCESS != result)
    {
        //Signal status will be set invalid and error handler will be called
        LOG_E("ENGINE_setControlSpeed_run","RTE_SPEED_pullPort");
        RTE_PWM_setStatus(&SO_CONTROLSPEED_signal, RTE_SIGNALSTATUS_INVALID);           
        return;
    }
        
    SPEED_data_t measuredSpeed = RTE_SPEED_get(&SO_CURRENTSPEED_signal);
    
    //Calculate controlvalue and get measured speed
    result = ENG_SetEngineClosedLoopPID(ENG_1,ticktime, targetSpeed.m_rpm, measuredSpeed.m_rpm, &controlSpeed.m_dutycycle);
    if (RC_SUCCESS != result)
    {
        //Signal status will be set invalid and error handler will be called
        LOG_E("ENGINE_setControlSpeed_run","ENG_SetEngineClosedLoopPID");
        RTE_PWM_setStatus(&SO_CONTROLSPEED_signal, RTE_SIGNALSTATUS_INVALID);
        return;
    }

    
    //Let's check the plausibility of the values
    result = ENG_checkControlspeedPlausibility(measuredSpeed.m_rpm, controlSpeed.m_dutycycle);
    if (RC_SUCCESS != result)
    {
        //Signal status will be set invalid and error handler will be called
        LOG_E("ENGINE_setControlSpeed_run","ENG_checkControlspeedPlausibility");
        RTE_PWM_setStatus(&SO_CONTROLSPEED_signal, RTE_SIGNALSTATUS_INVALID);
        //We may not return here, as otherwise the controlspeed has no chance to follow a fast targetspeed increase
    }
    else
    {
        //Reset Error counter
        ENGINE__errorCounter = 0;
    }
    
    //LOG_I("ENG_setControlSpeed_run"," T: %d, M: %d, C: %d",targetSpeed.m_rpm, measuredSpeed.m_rpm, controlSpeed.m_dutycycle);
    
    //And write controlspeed to the engine
    result = RTE_PWM_set(&SO_CONTROLSPEED_signal, controlSpeed);
    result = RTE_PWM_pushPort(&SO_CONTROLSPEED_signal);
    
 
}

#define ERRORCOUNT_MAX 5

void ENGINE_errorHandler_run()
{
    
    if (ENGINE__errorCounter >= ERRORCOUNT_MAX)
    {
        PWM_data_t controlSpeed = PWM_INIT_DATA;
        controlSpeed.m_dutycycle = 0;
        RC_t result = RTE_PWM_set(&SO_CONTROLSPEED_signal, controlSpeed);
        result = RTE_PWM_pushPort(&SO_CONTROLSPEED_signal);
        
        //Fire event to central state machine
        EVENT_data_t ev = EVENT_INIT_DATA;
        ev.m_ev = EVENT_error;
        result = RTE_EVENT_set(&SO_EVENT_signal, ev);

        ERROR_centralHandler(ERROR_ACTOR);
    }
    else
    {
        ENGINE__errorCounter++;
    }
        
   LOG_I("ENG_errorHandler_run","Error engine");
}
