/**************************************************
 ** Software Component SWC_COM
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#include "rte.h"
#include "rte_signalpool.h"

#include "swc_com.h"

/* Runnables */

void COM_init_run()
{
    UART_PSOC_Start();   
}

void COM_send_run()
{
    
    
    //Read in all signals we want to have monitored
    CARSTATE_data_t state = RTE_CARSTATE_get(&SO_CARSTATE_signal);
    SPEED_data_t targetspeed = RTE_SPEED_get(&SO_TARGETSPEED_signal);
    SPEED_data_t currentspeed = RTE_SPEED_get(&SO_CURRENTSPEED_signal);
    
    UARTPROT_data_t prot = UARTPROT_INIT_DATA;
    
    //Build the protocol
    prot.m_state = state.m_state;
    prot.m_targetspeed = targetspeed.m_rpm;
    prot.m_currentspeed = currentspeed.m_rpm;
    
    RTE_UARTPROT_set(&SO_UARTPROT_TX_signal, prot);
    RTE_UARTPROT_pushPort(&SO_UARTPROT_TX_signal);

}
