/*
 * Filename: sc_display_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Signalclass for display runnable
 * name: sc_Display
 * shortname: Display
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_display_type.h"



/* USER CODE START SC_DISPLAY_INCLUDE */
#include "sp_common.h"
#include "tft.h"
#include "stdlib.h"

/* USER CODE END SC_DISPLAY_INCLUDE */




/* USER CODE START SC_DISPLAY_USERDEFINITIONS */

/* USER CODE END SC_DISPLAY_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_DISPLAY signal  ****************
 *****************************************************************************************/
 
 
/**
 * Default OUT driver API
 */
inline RC_t SC_DISPLAY_driverOut(const SC_DISPLAY_data_t  *const data)
{
	/* USER CODE START driverOutSC_DISPLAY */
//#error "Add your code here"

	//Scale application data to drive format
    
    char display[sizeof(int)*8+1];
    char display2[sizeof(int)*8+1];
    char display3[sizeof(int)*8+1];
    
    TFT_setCursor(20,50);
    TFT_setTextSize(3);
    
    static uint8_t previous_hour_value;
    static uint8_t previous_minute_value;
    
    SC_DISPLAY_data_t tft_cmd = RTE_SC_DISPLAY_get(&SO_DISPLAY_signal);
    
    if(((tft_cmd.hour == 0) && (previous_hour_value == 23)) || ((tft_cmd.minute == 0) && (previous_minute_value == 59)))
    TFT_clearScreen();
    
    previous_hour_value = tft_cmd.hour;
    previous_minute_value = tft_cmd.minute;
    
    if(tft_cmd.Mode == TFT_IS_DISPLAYING)
    {
        TFT_setColors(WHITE,BLACK);
        itoa(tft_cmd.hour,display,10);
        TFT_print(display);
        TFT_print(":");
        itoa(tft_cmd.minute,display2,10);
        TFT_print(display2);
        
    }
    else if(tft_cmd.Mode == TFT_IS_EDITING)
    {
        TFT_setColors(BLACK,WHITE);
        itoa(tft_cmd.hour,display,10);
        TFT_print(display);
        TFT_print(":");
        itoa(tft_cmd.minute,display2,10);
        TFT_print(display2);
    }
    
    

	//Write scaled data to driver

	return RC_SUCCESS;
	/* USER CODE END driverOutSC_DISPLAY */
}



