/*
 * Filename: sp_common.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: The common global signal pool. All signals will be stored here
 * endaddr: ADR_SP_COMMON_END
 * name: sp_common
 * shortname: common
 * startaddr: ADR_SP_COMMON_START
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sp_common.h"



/* USER CODE START SP_COMMON_INCLUDE */

//boolean_t global__count = FALSE;

/* USER CODE END SP_COMMON_INCLUDE */

#include "sc_button_event.h"
#include "sc_button_event_type.h"
#include "sc_control_out.h"
#include "sc_control_out_type.h"
#include "sc_display.h"
#include "sc_display_type.h"



/* signal configuration */
/*
 * description: A Signal object containing event information of leftbutton for short press and rightbutton for short / long press)
 * indriver: default
 * name: so_Button_Event
 * onDataError: 0
 * onDataUpdate: ev_Button_OnData
 * outdriver: 0
 * resource: None
 * shortname: Button_Event
 * signalclass: sc_Button_Event
 * signalpool: sp_common
 */


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_Button_Event_updTasks = { tsk_realtime };
 

static const SC_BUTTON_EVENT_cfg_t SO_BUTTON_EVENT_cfg = 
{
   /* indriver           */  SC_BUTTON_EVENT_driverIn,
   /* outdriver          */  0,

   /* onUpdate           */  ev_Button_OnData,
   /* onError            */  0,
   /* taskCount onUpdate */  1,
   /* task list onUpdate */  &so_Button_Event_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_button_event */


/* signal data */

SC_BUTTON_EVENT_t SO_BUTTON_EVENT_signal= 
{
   /* init value    */  SC_BUTTON_EVENT_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_BUTTON_EVENT_cfg,
}; /* data so_button_event */

/* signal configuration */
/*
 * description: Signal object which consists of statemachine output, that is nothing but data of the minute and hour widget given for the display_runnable
 * indriver: 0
 * name: so_Control_Out
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: 0
 * resource: None
 * shortname: Control_Out
 * signalclass: sc_Control_Out
 * signalpool: sp_common
 */

 

static const SC_CONTROL_OUT_cfg_t SO_CONTROL_OUT_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  0,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_control_out */


/* signal data */

SC_CONTROL_OUT_t SO_CONTROL_OUT_signal= 
{
   /* init value    */  SC_CONTROL_OUT_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_CONTROL_OUT_cfg,
}; /* data so_control_out */

/* signal configuration */
/*
 * description: A signal for TFT commands type
 * indriver: 0
 * name: so_Display
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: default
 * resource: None
 * shortname: Display
 * signalclass: sc_Display
 * signalpool: sp_common
 */

 

static const SC_DISPLAY_cfg_t SO_DISPLAY_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  SC_DISPLAY_driverOut,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_display */


/* signal data */

SC_DISPLAY_t SO_DISPLAY_signal= 
{
   /* init value    */  SC_DISPLAY_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_DISPLAY_cfg,
}; /* data so_display */



/*
 * Increments the age of the signals in this pool 
 */
void RTE_timertick_sp_common_tick(uint32_t tick){
   RTE_SC_BUTTON_EVENT_incAge( &SO_BUTTON_EVENT_signal, tick); 
   RTE_SC_CONTROL_OUT_incAge( &SO_CONTROL_OUT_signal, tick); 
   RTE_SC_DISPLAY_incAge( &SO_DISPLAY_signal, tick); 
   
}

/*
 * Reset all signals in this pool
 */
void RTE_reset_sp_common(){
   RTE_SC_BUTTON_EVENT_init( &SO_BUTTON_EVENT_signal); 
   RTE_SC_CONTROL_OUT_init( &SO_CONTROL_OUT_signal); 
   RTE_SC_DISPLAY_init( &SO_DISPLAY_signal); 
   
}		


