/*
 * Filename: swc_brake.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Based on engine speed, set the Red LED.
 * name: swc_brake
 * shortname: brake
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_brake.h"
#include "watchdog.h"


/* USER CODE START SWC_BRAKE_INCLUDE */

/* USER CODE END SWC_BRAKE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_BRAKE_USERDEFINITIONS */

/* USER CODE END SWC_BRAKE_USERDEFINITIONS */



/*
 * component: swc_brake
 * cycletime: 0
 * description: Breake representing Runnable
 * events: ev_engine_speed_onData
 * name: BRAKE_setBrakeLight_run
 * shortname: setBrakeLight
 * signalIN: so_engine_speed
 * signalOUT: so_breaklight
 * task: tsk_realtime
 */
void BRAKE_setBrakeLight_run(RTE_event ev){
	
	/* USER CODE START BRAKE_setBrakeLight_run */


    SC_BRAKELIGHT_data_t break_light;
    SC_SPEED_data_t engine_speed =  RTE_SC_SPEED_get(&SO_ENGINE_SPEED_signal);
     
    if(engine_speed.value == 0 )
    {
    break_light.red_led = TRUE;
    RTE_SC_BRAKELIGHT_set(&SO_BREAKLIGHT_signal,break_light);
    RTE_SC_BRAKELIGHT_pushPort(&SO_BREAKLIGHT_signal);
    }
    else
    {
     break_light.red_led = FALSE;
     RTE_SC_BRAKELIGHT_set(&SO_BREAKLIGHT_signal,break_light);
     RTE_SC_BRAKELIGHT_pushPort(&SO_BREAKLIGHT_signal);
    }
     
    WD_Alive(4);
 
    /* USER CODE END BRAKE_setBrakeLight_run */
}

/* USER CODE START SWC_BRAKE_FUNCTIONS */

/* USER CODE END SWC_BRAKE_FUNCTIONS */

