/*
 * Filename: swc_engine.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Set the RGB Led brightness based on the engine speed
 * name: swc_engine
 * shortname: engine
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_engine.h"
#include "stdlib.h"
#include "watchdog.h"


/* USER CODE START SWC_ENGINE_INCLUDE */

/* USER CODE END SWC_ENGINE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_ENGINE_USERDEFINITIONS */

/* USER CODE END SWC_ENGINE_USERDEFINITIONS */



/*
 * component: swc_engine
 * cycletime: 100
 * description: Engine representing Runnable
 * events: 
 * name: ENGINE_setEngine_run
 * shortname: setEngine
 * signalIN: so_engine_speed
 * signalOUT: so_rgb_led
 * task: tsk_realtime
 */
void ENGINE_setEngine_run(RTE_event ev)
{
	
	/* USER CODE START ENGINE_setEngine_run */


    SC_PWM_data_t PWM_signal;
    
    
    if(SO_ENGINE_SPEED_signal.age < 100)
    {
     SC_SPEED_data_t engine_speed =  RTE_SC_SPEED_get(&SO_ENGINE_SPEED_signal);
     PWM_signal.duty_cycle = engine_speed.value;
      
     RTE_SC_PWM_set(&SO_RGB_LED_signal,PWM_signal);
    
     RTE_SC_PWM_pushPort(&SO_RGB_LED_signal);
    }
    else
    {
      
     PWM_signal.duty_cycle = 0;
      
     RTE_SC_PWM_set(&SO_RGB_LED_signal,PWM_signal);
    
     RTE_SC_PWM_pushPort(&SO_RGB_LED_signal);
    
    
    }
    
    WD_Alive(2);

    
    /* USER CODE END ENGINE_setEngine_run */
}

/* USER CODE START SWC_ENGINE_FUNCTIONS */

/* USER CODE END SWC_ENGINE_FUNCTIONS */

