/*
 * Filename: swc_joystick.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Recieve Analog signals from the Joystick hardware and send out the joystick commands (XY coordinates)
 * name: swc_joystick
 * shortname: joystick
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_joystick.h"
#include "watchdog.h"



/* USER CODE START SWC_JOYSTICK_INCLUDE */

#include "stdlib.h"

/* USER CODE END SWC_JOYSTICK_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_JOYSTICK_USERDEFINITIONS */

/* USER CODE END SWC_JOYSTICK_USERDEFINITIONS */



/*
 * component: swc_joystick
 * cycletime: 10
 * description: Joystick representing Runnable
 * events: 
 * name: JOYSTICK_readJoystick_run
 * shortname: readJoystick
 * signalIN: 
 * signalOUT: so_joystick
 * task: tsk_realtime
 */
void JOYSTICK_readJoystick_run(RTE_event ev){
	
	/* USER CODE START JOYSTICK_readJoystick_run */
    
        
    RTE_SC_JOYSTICK_pullPort(&SO_JOYSTICK_signal);
    
    WD_Alive(1);
    

    /* USER CODE END JOYSTICK_readJoystick_run */
}

/* USER CODE START SWC_JOYSTICK_FUNCTIONS */

/* USER CODE END SWC_JOYSTICK_FUNCTIONS */

