/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_ledRed_aliases.h"
#include "Pin_ledRed.h"
#include "Pin_ledYellow_aliases.h"
#include "Pin_ledYellow.h"
#include "Pin_LedGreen_aliases.h"
#include "Pin_LedGreen.h"
#include "PWM_ledRed.h"
#include "PWM_ledYellow.h"
#include "PWM_ledGreen.h"
#include "Clock_1.h"
#include "Pin_RGB_RED_aliases.h"
#include "Pin_RGB_RED.h"
#include "Pin_RGB_Blue_aliases.h"
#include "Pin_RGB_Blue.h"
#include "Pin_RGB_Green_aliases.h"
#include "Pin_RGB_Green.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

